"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"VSHeight"= 1.25in'Spec
"VSLength"= 450mm
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"VSBottomSideRailHoleY1FromBottomOfLowerRail"= "V1 BottomOfLowerRail" + "HoleOffsetFromSide"'Equals 70.1125
"VSSideRailHoleX1FromSide"= "HoleOffsetFromSide" + "RailThickness"
"FasteningHoleDiameter"= .125in
"VSBottomSideRailHoleY2FromY1"= "LowerRailHeight" - "HoleOffsetFromSide" - "HoleOffsetFromEdge"'Equals 6.35
"VSTopSideRailHoleY1FromEdge"= "HoleOffsetFromEdge" + "RailThickness"
"D4@BackSideHoles-Sketch3" = "FasteningHoleDiameter"
"D1@BackSideHoles-Sketch3" = "VSBottomSideRailHoleY1FromBottomOfLowerRail"
"D2@BackSideHoles-Sketch3" = "VSSideRailHoleX1FromSide"
"D1@Boss-Extrude1"="VSLength"
"D4@RightSideHoles-Sketch4"="FasteningHoleDiameter"
"D3@RightSideHoles-Sketch4" = "VSBottomSideRailHoleY1FromBottomOfLowerRail"
"D2@RightSideHoles-Sketch4"="VSSideRailHoleX1FromSide"
"D8@BackSideHoles-Sketch3" = "VSTopSideRailHoleY1FromEdge"
"D6@RightSideHoles-Sketch4"="VSTopSideRailHoleY1FromEdge"
"VSMidSideRailHoleY1FromV8TopOfMidSideRail"= "V8 ToTopOfMidSideRail" - "HoleOffsetFromEdge"'Equals 308.2875
"LowerRailHeight"= 1.00in
"D2@Sketch2"="VSWidth"
"D1@Sketch2"="VSHeight"
"MidBackRailHeight"= 1.00in
"VSMidBackRailHoleY1FromV7TopOfMidBackRail"= "V7 ToTopOfMidBackRail" - "HoleOffsetFromSide"'Equals 308.2875
"TopRailHeight"= 1.25in
"MidSideRailHeight"= 1.25in
"D8@RightSideHoles-Sketch4"="HoleOffsetFromEdge"
"D5@BackSideHoles-Sketch3"="VSBottomSideRailHoleY2FromY1"
"D5@RightSideHoles-Sketch4"="VSBottomSideRailHoleY2FromY1"
"VSMidBackRailHoleY2FromY1"= "MidBackRailHeight" - "HoleOffsetFromSide" - "HoleOffsetFromEdge"'Equals 6.35
"VSMidSideRailHoleY2FromY1"= "MidSideRailHeight" - "HoleOffsetFromSide" - "HoleOffsetFromEdge"'Equals 12.7
"D7@BackSideHoles-Sketch3"="VSMidBackRailHoleY2FromY1"
"D9@RightSideHoles-Sketch4"="VSMidSideRailHoleY2FromY1"
"VSTopSideRailHoleY2FromY1"= "TopRailHeight" - "VSTopSideRailHoleY1FromEdge" - "HoleOffsetFromEdge"'Equals 12.7
"D9@BackSideHoles-Sketch3"="VSTopSideRailHoleY2FromY1"
"VSSideRailHoleX2FromX1"= "VSWidth" - "VSSideRailHoleX1FromSide" - "HoleOffsetFromEdge"
"D3@BackSideHoles-Sketch3"="VSSideRailHoleX2FromX1"
"D7@RightSideHoles-Sketch4"="VSTopSideRailHoleY2FromY1"
"D11@RightSideHoles-Sketch4"="VSSideRailHoleX2FromX1"
"V1 BottomOfLowerRail"= "LegHeight"
"V1 BottomOfLowerRail"= "LegHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"ZAxisLeadScrewLength"= 200mm
"HotEndToTopOfXAxisGB"= 63.315144mm'Measured from the100.Should be 63.315144
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"
"LinearRailWidth"= 12mm'Spec
"V6 ToBottomOfGantryPulley"= "V5 ToBottomOfXAxisLinearRail" - "DistanceFromGABTopToLowerPulley"
"GABUpperHeight"= 6mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"GABRiserBossOffset"= 0.8mm'Aligns Pulleys
"DistanceFromGABTopToLowerPulley"= "GABUpperHeight" + "GABMidWallHeight" - "GABMidShortRiserHeight" + "GABRiserBossOffset" / 2
"V7 ToTopOfMidBackRail"= "V6 ToBottomOfGantryPulley" + "StepperShaftLength"
"D10@BackSideHoles-Sketch3" = "VSMidBackRailHoleY1FromV7TopOfMidBackRail"
"D10@RightSideHoles-Sketch4"="VSMidSideRailHoleY1FromV8TopOfMidSideRail"
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"V2 ToBedAtTopOfZAxis"= "V1 BottomOfLowerRail" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2
"LM8UUHeight"= 24mm'Spec
"V8 ToTopOfMidSideRail"= "V7 ToTopOfMidBackRail" - "RailThickness"
"VSEnclosureOffsets"= ( "VSLength" - "LegHeight" ) / 4
"D11@BackSideHoles-Sketch3"="LegHeight" + "VSEnclosureOffsets"
"D12@BackSideHoles-Sketch3"="VSEnclosureOffsets"
"D13@BackSideHoles-Sketch3"="VSEnclosureOffsets"
"D12@RightSideHoles-Sketch4"="LegHeight" + "VSEnclosureOffsets"
"D13@RightSideHoles-Sketch4"="VSEnclosureOffsets"
"D14@RightSideHoles-Sketch4"="VSEnclosureOffsets"
