"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"VSHeight"= 1.25in'Spec
"VSLength"= 20.0in
"VSBottomSideRailHoleYFromBottomOfLowerRailYSValue"= 95.4mm
"FasteningHoleDiameter"= .125in
"VSTopSideRailHoleYFromEdge"= "TopRailHeight" / 2
"D1@LeftSideHoles-Sketch3"="VSBottomSideRailHoleYFromBottomOfLowerRailYSValue"
"D2@LeftSideHoles-Sketch3"="FrameFastenerHoleOffsetFromSide"
"D1@Boss-Extrude1"="VSLength"
"D4@BackSideHoles-Sketch4"="FrameFastenerHoleDiameter"
"VSMidSideRailHoleYFromV8TopOfMidSideRailYSValue"= 351.58487mm
"D1@Sketch2"="VSHeight"
"D2@Sketch2"="VSWidth"
"TopRailHeight"= 1.25in
"D11@LeftSideHoles-Sketch3"="VSMidSideRailHoleYFromV8TopOfMidSideRailYSValue"
"D3@BackSideHoles-Sketch4"="VSBottomSideRailHoleYFromBottomOfLowerRailYSValue"
"D8@LeftSideHoles-Sketch3"="VSTopSideRailHoleYFromEdge"
"D5@Sketch2"="FasteningHoleDiameter"
"FrameFastenerHoleDiameter"= 8mm
"FrameFastenerHoleOffsetFromSide"= "VSWidth" / 2 + "GapBetweenVerticalSupportsAndRails"
"D2@BackSideHoles-Sketch4"="FrameFastenerHoleOffsetFromSide"
"D3@LeftSideHoles-Sketch3"="FrameFastenerHoleDiameter"
"D5@BackSideHoles-Sketch4"="TopBackRailHeight"/2
"TopBackRailHeight"= 2.5in
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
