"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"VSHeight"= 1.25in'Spec
"VSLength"= 450mm
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"VSBottomSideRailHoleY1FromBottomOfLowerRail"= "V1 BottomOfLowerRail" + "HoleOffsetFromSide"'Equals 81.1125
"VSSideRailHoleX1FromSide"= "HoleOffsetFromSide" + "RailThickness"
"FasteningHoleDiameter"= .125in
"VSBottomSideRailHoleY2FromY1"= "LowerRailHeight" - "HoleOffsetFromSide" - "HoleOffsetFromEdge"'Equals 6.35
"VSTopSideRailHoleY1FromEdge"= "HoleOffsetFromEdge" + "RailThickness"
"D4@LeftSideHoles-Sketch3"="FasteningHoleDiameter"
"D1@LeftSideHoles-Sketch3"="VSBottomSideRailHoleY1FromBottomOfLowerRail"
"D2@LeftSideHoles-Sketch3"="VSSideRailHoleX1FromSide"
"D1@Boss-Extrude1"="VSLength"
"D4@BackSideHoles-Sketch4" = "FasteningHoleDiameter"
"VSMidSideRailHoleY1FromV8TopOfMidSideRail"= "V8 ToTopOfMidSideRail" - "HoleOffsetFromEdge"'Equals 332.37764
"LowerRailHeight"= 1.00in
"D1@Sketch2"="VSHeight"
"D2@Sketch2"="VSWidth"
"MidBackRailHeight"= 1.00in
"VSMidBackRailHoleY1FromV7TopOfMidBackRail"= "V7 ToTopOfMidBackRail" - "HoleOffsetFromEdge"'Equals 330.77764
"TopRailHeight"= 1.25in
"MidLeftOrRightSideRailHeight"= 2.0in
"D10@LeftSideHoles-Sketch3"="HoleOffsetFromEdge"
"VSMidBackRailHoleY2FromY1"= "MidBackRailHeight" - "HoleOffsetFromSide" - "HoleOffsetFromEdge"'Equals 6.35
"VSMidSideRailHoleY2FromY1"= "MidLeftOrRightSideRailHeight" - "HoleOffsetFromEdge" * 2'Equals 34.925
"D7@LeftSideHoles-Sketch3"="VSMidSideRailHoleY2FromY1"
"D8@BackSideHoles-Sketch4"="VSMidBackRailHoleY2FromY1"
"D6@BackSideHoles-Sketch4"="VSTopSideRailHoleY1FromEdge"
"VSTopSideRailHoleY2FromY1"= "TopRailHeight" - "VSTopSideRailHoleY1FromEdge" - "HoleOffsetFromEdge"'Equals 12.7
"D7@BackSideHoles-Sketch4"="VSTopSideRailHoleY2FromY1"
"VSBottomSideRailHoleX2FromX1"= "VSWidth" - "VSSideRailHoleX1FromSide" - "HoleOffsetFromEdge"
"D3@LeftSideHoles-Sketch3"="VSBottomSideRailHoleX2FromX1"
"V1 BottomOfLowerRail"= "LegHeight"
"V1 BottomOfLowerRail"= "LegHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"ZAxisLeadScrewLength"= 200mm
"LM8UUHeight"= 24mm'Spec
"V2 ToBedAtTopOfZAxis"= "V1 BottomOfLowerRail" - "LowerEnclosureThickness" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2
"HotEndToTopOfXAxisGB"= 63.315144mm'Measured from the100.Should be 63.315144
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"
"LinearRailWidth"= 12mm'Spec
"GABUpperHeight"= 6mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"V7 ToBottomOfMidBackRail"= "V6 ToMiddleOfYAxisGantryBlock" - "StepperShaftLength" / 2
"D1@BackSideHoles-Sketch4" = "VSMidBackRailHoleY1FromV7TopOfMidBackRail"
"D11@LeftSideHoles-Sketch3"="VSMidSideRailHoleY1FromV8TopOfMidSideRail"
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V8 ToTopOfMidSideRail" = "V6 ToMiddleOfYAxisGantryBlock" + "MidSideRailVerticalOffset"
"VSEnclosureOffsets"= ( "VSLength" - "LegHeight" ) / 4
"D12@LeftSideHoles-Sketch3"="LegHeight" + "VSEnclosureOffsets"
"D13@LeftSideHoles-Sketch3"="VSEnclosureOffsets"
"D10@BackSideHoles-Sketch4"="LegHeight" + "VSEnclosureOffsets"
"D11@BackSideHoles-Sketch4"="VSEnclosureOffsets"
"D13@BackSideHoles-Sketch4"="HoleOffsetFromEdge"
"D5@BackSideHoles-Sketch4"="VSBottomSideRailHoleY2FromY1"
"D3@BackSideHoles-Sketch4"="VSBottomSideRailHoleY1FromBottomOfLowerRail"
"D2@BackSideHoles-Sketch4"="VSSideRailHoleX1FromSide"
"D5@LeftSideHoles-Sketch3"="VSBottomSideRailHoleY2FromY1"
"D6@LeftSideHoles-Sketch3"="VSTopSideRailHoleY2FromY1"
"D8@LeftSideHoles-Sketch3"="VSTopSideRailHoleY1FromEdge"
"LowerEnclosureThickness"= 5mm
"V7 ToTopOfMidBackRail"= "V7 ToBottomOfMidBackRail" + "MidBackRailHeight"
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"GABLowerHeight"= 3mm
"V6 ToMiddleOfYAxisGantryBlock"= "V5 ToBottomOfXAxisLinearRail" - "GABHeight" / 2'Equals 325.31514
"D9@LeftSideHoles-Sketch3"="VSEnclosureOffsets"
"D12@BackSideHoles-Sketch4"="VSEnclosureOffsets"
"MidSideRailVerticalOffset"= "LinearRailWidth" + 3mm'Allows space for RodStabilizer to attach to bottom of MidSideRail
