"RailThickness"= .125in'Spec
"StepperMountingHoleDistance"= 31mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"'Spec
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"LeadScrewNutMountingHoleDiameter"=3
"D9@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDiameter"
"D10@ThreadedRod'Holes-Sketch2" = "LeadScrewNutInnerShaftFlangeDiameter"
"D1@Boss-Extrude1" = "BasePlateLength"
"BedThirdSize"= 70mm
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"BedInnerSquareLength"= "BedInnerSquareWidth"
"BedLWidth"= "BedThirdSize"'Equals 70
"BedLength"= "BedInnerSquareLength" + "BedLWidth" * 2 + "BedIncreasedByLength"'Equals 350
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 316
"DistanceFromBedFrontToFirstLeftStepperHole"= "LeadScrewNutPadSize" + 10mm'Equals 34
"BedIncreasedByLength"= 0mm
"D17@ThreadedRod'Holes-Sketch2" = "DistanceBetweenFrontToBackStepperHoles"
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"BaseThickness"= 5mm
"FrontBackRailLength"= 510mm
"D1@Sketch1"= "BasePlateWidth"
"D2@Sketch1"="BaseThickness"
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm
"D3@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D4@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D5@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D6@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D7@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D8@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D11@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D12@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D13@ThreadedRod'Holes-Sketch2" = "LeadScrewNutPadSize" / 2 + 1mm
"D14@ThreadedRod'Holes-Sketch2" = "LeadScrewNutPadSize" / 2 + 1mm
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperMountingHoleDistance"'Equals 461.65
"BasePlateWidth"= "DistanceBetweenLeftToRightStepperHoles" + "LeadScrewNutPadSize" + 2mm
"BasePlateLength"= "DistanceBetweenFrontToBackStepperHoles" + "LeadScrewNutPadSize" + 2mm
"D2@ThreadedRod'Holes-Sketch2" = "DistanceBetweenLeftToRightStepperHoles"
"BuildPlateWidth"= 352mm
"BuildPlateLength"= 352mm
"BuildPlateStandoffHoleDistanceFromLeftOrRight"= 7mm
"BuildPlateStandoffHoleDistanceFromFrontOrBack"= 40mm
"D1@BaseOlateMountHolesSketch2"=( "BasePlateWidth" - "BuildPlateWidth" + "BuildPlateStandoffHoleDistanceFromLeftOrRight" * 2)  / 2
"D2@BaseOlateMountHolesSketch2"=( "BasePlateWidth" - "BuildPlateWidth"  + "BuildPlateStandoffHoleDistanceFromLeftOrRight" * 2)  / 2
"D3@BaseOlateMountHolesSketch2"=("BasePlateLength" - ("BuildPlateLength" - "BuildPlateStandoffHoleDistanceFromFrontOrBack"*2))/2
"D4@BaseOlateMountHolesSketch2"=("BasePlateLength" -("BuildPlateLength" -"BuildPlateStandoffHoleDistanceFromFrontOrBack"*2))/2
