"RailThickness"= .125in'Spec
"StepperMountingHoleDistance"= 31mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"FrontBackRailLength"= 510mm
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperMountingHoleDistance"'Equals 461.65
"BedThickness"= 20mm
"BedLLongSide"= "BedThirdSize" * 3'Equals 210
"BedLShortSide"= "BedThirdSize" * 2'Equals 140
"BedLWidth"= "BedThirdSize"'Equals 70
"D4@CornerrSketch1"="BedLWidth" + "BedIncreasedByWidth"/2
"D1@CornerrSketch1" = "BedLLongSide" + "BedIncreasedByWidth" / 2
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"BedWidth"= "BedInnerSquareWidth" + "BedLWidth" * 2 + "BedIncreasedByWidth"'Equals 370
"BedIncreasedByWidth"= 20mm
"BedIncreasedByLength"= 0mm
"BedThirdSize"= 70mm
"D1@TRPegCapSketch2"="BedPegCapWidth"
"StandardWallThickness"= 3mm
"D2@TRPegCapSketch2" = "StandardWallThickness"
"D3@TRPegCapSketch2"="BedPegCapHeight"
"D1@TRPegCapBoss-Extrude2" = "StandardWallThickness"
"D1@BottomPegHoleCut-Extrude1"="StandardWallThickness"
"D1@Shell2"="StandardWallThickness"
"D2@TRPegSketch1"="BedPegHeight"
"D5@CornerrSketch1"="DistanceFromBedSideToStepperHole"
"DistanceFromBedFrontToStepperHole"= "LeadScrewNutPadSize" + 10mm
"DistanceFromBedSideToStepperHole"= ( "DistanceBetweenLeftToRightStepperHoles" - "BedWidth" ) / 2'Equals 45.825
"D7@CornerrSketch1"= "BedLShortSide" + "BedIncreasedByLength" / 2
"D3@CornerrSketch1"="DistanceFromBedFrontToStepperHole"
"BedToBuildPlateStandoffPadSize"= 10mm
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"D1@PadSketch3" = "LeadScrewNutPadSize"
"D1@StepperShaftHoleSketch4"="LeadScrewNutInnerShaftFlangeDiameter"
"D11@CornerrSketch1"="BedLWidth"
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountHoleDiameter"= "M3HeatInsertHoleDiameter"
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm'Spec
"D2@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance" / 2
"D3@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"
"D5@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"
"D4@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"/2
"D1@ThreadedNutMountHolesSketch5"="LeadScrewNutMountHoleDiameter"
"LeadScrewNutPadDepth"= "BedThickness" / 2'Equals 10
"D1@ThreadedNutMountHolesCut-Extrude4"="LeadScrewNutPadDepth"
"D2@PadSketch3"="BedToBuildPlateStandoffPadSize"
"D3@PadSketch3"="BedToBuildPlateStandoffHolesDistanceFromFront"
"BuildPlateWidth" = 352mm'Spec
"D4@PadSketch3"="BedIncreasedByWidth"/2 + "BuildPlateWidth"/2
"D2@StepperShaftHoleSketch4"="M3HeatInsertHoleDiameter"
"BuildPlateStandoffHolesDistanceFromFront"= 7mm
"BedToBuildPlateStandoffHolesDistanceFromFront"= "BuildPlateStandoffHolesDistanceFromFront" + "BedIncreasedByLength" / 2'Equals 7
"BedPegHoleWidth"= 10mm
"BedPegHoleHeight"= "BedThickness" - "StandardWallThickness" * 2'Equals 14
"BedPegWidth"= "BedPegHoleWidth" - .1mm * 2'For easier assembly
"BedPegHeight"= "BedPegHoleHeight" - .1mm'For easier assembly
"BedTopPegOffsetFromSide"= 10mm
"BedPegBoss"= "StandardWallThickness" + .1mm'For easier assembly
"BedPegCapHeight"= "BedThickness" - "StandardWallThickness"'Equals 17
"BedPegCapWidth"= "BedThickness" / 2 + "StandardWallThickness" * 2'Equals 16
"D1@TRPegSketch1"="BedTopPegOffsetFromSide" + .1mm
"D3@TRPegSketch1"= "BedPegWidth"
"D1@TRPegBoss-Extrude1"="BedPegBoss"
"D3@BottomPegHoleSketch3"="BedTopPegOffsetFromSide"
"D2@BottomPegHoleSketch3"="BedPegHoleWidth"
"D1@BedCenterPegHoleCutSketch1" = "BedPegHoleHeight"
"D2@BedCenterPegHoleCutSketch1" = "BedPegHoleWidth"
"D3@BedCenterPegHoleCutSketch1" = "BedInnerSquareWidth" / 2 - "BedPegHoleWidth" / 2
"D1@BedCenterPegHoleCut-Extrude1"="StandardWallThickness"
"M3HeatInsertHoleDiameter"= 4mm'Spec
