"RailThickness"= .125in'Spec
"StepperMountingHoleDistance"= 31mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"FrontBackRailLength"= 510mm
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperMountingHoleDistance"'Equals 461.65
"BedThickness"= 20mm
"BedLLongSide"= "BedThirdSize" * 3'Equals 210
"BedLShortSide"= "BedThirdSize" * 2'Equals 140
"BedLWidth"= "BedThirdSize"'Equals 70
"D4@CornerrSketch1"="BedLWidth" + "BedIncreasedByLength"/2
"BedIncreasedByWidth"= 20mm
"BedIncreasedByLength"= 0mm
"BedThirdSize"= 70mm
"BedWidth"= "BedInnerSquareWidth" + "BedLWidth" * 2 + "BedIncreasedByWidth"'Equals 370
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"StandardWallThickness"= 3mm
"D2@BRPegHoleSketch1"="BedPegHoleWidth"
"D1@BRPegHoleSketch1"="BedTopPegOffsetFromSide" 
"D3@BRPegHoleSketch1"="BedPegHoleHeight"
"D1@BRPegHoleCut-Extrude1" = "StandardWallThickness"
"D2@TopPegSketch2"="BedPegHeight"
"D1@TopPegBoss-Extrude1" = "StandardWallThickness"
"D3@TopPegCapSketch3"="BedPegCapHeight"
"D1@TopPegCapSketch3"="BedPegCapWidth"
"D1@TopPegCapBoss-Extrude2"="BedPegBoss"
"D2@TopPegCapSketch3"="StandardWallThickness"
"DistanceFromBedSideToStepperHole"= ( "DistanceBetweenLeftToRightStepperHoles" - "BedWidth" ) / 2'Equals 45.825
"DistanceFromBedFrontToFirstLeftStepperHole"= "LeadScrewNutPadSize" + 10mm'Equals 34
"D3@CornerrSketch1"="DistanceFromBedFrontToFirstLeftStepperHole"
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"D1@PadSketch2" = "LeadScrewNutPadSize"
"D1@StepperShaftHoleCutSketch3"="LeadScrewNutInnerShaftFlangeDiameter"
"D2@CornerrSketch1"="BedLWidth" + "BedIncreasedByWidth"/2
"D6@CornerrSketch1"="BedLLongSide"
"D1@TopPegSketch2"="BedTopPegOffsetFromSide" + .1mm
"D1@CornerrSketch1"="DistanceFromBedSideToStepperHole"
"D5@CornerrSketch1"="BedLShortSide" + "BedIncreasedByWidth"/2
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountHoleDiameter"= 2mm'Spec is 4.1 but smaller for tapping
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm'Spec
"D1@ThreadedNutMountHolesSketch4"="LeadScrewNutMountHoleDiameter"
"D2@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"/2
"D3@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"
"D4@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"/2
"D5@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"
"LeadScrewNutPadDepth"= "BedThickness" / 2'Equals 10
"D1@PadBoss-Extrude2"="LeadScrewNutPadDepth"
"D1@ThreadedNutMountHolesCut-Extrude2"= "LeadScrewNutPadDepth"
"BedPegHoleWidth"= 10mm
"BedPegHoleHeight"= "BedThickness" - "StandardWallThickness" * 2'Equals 14
"BedPegWidth"= "BedPegHoleWidth" - .1mm * 2'For easier assembly
"BedPegHeight"= "BedPegHoleHeight" - .1mm'For easier assembly
"BedTopPegOffsetFromSide"= 10mm
"BedPegBoss"= "StandardWallThickness" + .1mm'For easier assembly
"BedPegCapHeight"= "BedThickness" - "StandardWallThickness"'Equals 17
"BedPegCapWidth"= "BedThickness" / 2 + "StandardWallThickness" * 2'Equals 16
"D3@TopPegSketch2"="BedPegWidth"
"D1@CenterPegHoleCutSketch1" = "BedPegHoleHeight"
"D2@CenterPegHoleCutSketch1" = "BedPegHoleWidth"
"D3@CenterPegHoleCutSketch1"= "BedInnerSquareWidth"/2 - "BedPegHoleWidth"/2
"D1@CenterPegHoleCut-Extrude1"="StandardWallThickness"
