"RailThickness"= .125in'Spec
"StepperMountingHoleDistance"= 31mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"FrontBackRailLength"= 510mm
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperMountingHoleDistance"'Equals 461.65
"BedThickness"= 20mm
"BedLLongSide"= "BedThirdSize" * 3'Equals 210
"BedLShortSide"= "BedThirdSize" * 2'Equals 140
"BedLWidth"= "BedThirdSize" + "BedOverlap"'Equals 90
"D4@CornerrSketch1"="BedLWidth" + "BedIncreasedByLength"/2
"BedIncreasedByWidth"= 20mm
"BedIncreasedByLength"= 0mm
"BedThirdSize"= 70mm
"BedOverlap"= 20mm
"BedWidth"= "BedInnerSquareWidth" + "BedLWidth" * 2 - "BedOverlap" * 2 + "BedIncreasedByWidth"'Equals 370
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"StandardWallThickness"= 3mm
"D2@BRPegHoleSketch1"="BedTopPegHoleWidth"
"D1@BRPegHoleSketch1"="BedTopPegOffsetFromSide" 
"D3@BRPegHoleSketch1"="BedTopPegHoleHeight"
"D1@BRPegHoleCut-Extrude1" = "StandardWallThickness"
"D2@TopPegSketch2"="BedTopPegHeight"
"D1@TopPegBoss-Extrude1" = "StandardWallThickness"
"D3@TopPegCapSketch3"="BedTopPegCapHeight"
"D1@TopPegCapSketch3"="BedTopPegCapWidth"
"D1@TopPegCapBoss-Extrude2"="BedTopPegBoss"
"D2@TopPegCapSketch3"="StandardWallThickness"
"DistanceFromBedSideToStepperHole"= ( "DistanceBetweenLeftToRightStepperHoles" - "BedWidth" ) / 2'Equals 45.825
"DistanceFromBedFrontToFirstLeftStepperHole"= "LeadScrewNutPadSize" + 10mm'Equals 34
"D3@CornerrSketch1"="DistanceFromBedFrontToFirstLeftStepperHole"
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"D1@PadSketch2" = "LeadScrewNutPadSize"
"D1@StepperShaftHoleCutSketch3"="LeadScrewNutInnerShaftFlangeDiameter"
"D2@CornerrSketch1"="BedLWidth" + "BedIncreasedByWidth"/2
"D6@CornerrSketch1"="BedLLongSide"
"D1@TopPegSketch2"="BedTopPegOffsetFromSide" + .1mm
"D1@CornerrSketch1"="DistanceFromBedSideToStepperHole"
"D5@CornerrSketch1"="BedLShortSide" + "BedIncreasedByWidth"/2
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountHoleDiameter"= 2mm'Spec is 4.1 but smaller for tapping
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm'Spec
"D1@ThreadedNutMountHolesSketch4"="LeadScrewNutMountHoleDiameter"
"D2@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"/2
"D3@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"
"D4@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"/2
"D5@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"
"LeadScrewNutPadDepth"= "BedThickness" / 2'Equals 10
"D1@PadBoss-Extrude2"="LeadScrewNutPadDepth"
"D1@ThreadedNutMountHolesCut-Extrude2"= "LeadScrewNutPadDepth"
"BedTopPegHoleWidth"= 10mm
"BedTopPegHoleHeight"= "BedThickness"- "StandardWallThickness"* 2' Equals 14
"BedTopPegWidth"= "BedTopPegHoleWidth"- .1mm* 2'For easier assembly
"BedTopPegHeight"= "BedTopPegHoleHeight"- .1mm'For easier assembly
"BedTopPegOffsetFromSide"= 10mm
"BedTopPegBoss"= "StandardWallThickness"+ .1mm'For easier assembly
"BedTopPegCapHeight"= "BedThickness"- "StandardWallThickness"'Equals 17
"BedTopPegCapWidth"= "BedThickness"/2 + "StandardWallThickness"*2'Equals 16
"D3@TopPegSketch2"="BedTopPegWidth"
"D5@TabHoleCutsSketch1"="BedOverlap"/2
"D1@TabHoleCutsSketch1"="BedOverlap"
"D4@TabHoleCutsSketch1"="BedOverlap"
"D2@TabHoleCutsSketch1"="BedOverlap"/2
"D1@PutPartialShellbackSketch1"="BedOverlap" + "StandardWallThickness"
"D2@PutPartialShellbackSketch1"="BedOverlap" + "StandardWallThickness"
"D3@OverLapChamfer1"="BedOverlap"
"D1@OverLapChamfer1"="BedThickness"
"D1@PutPartialShellBackBoss-Extrude1"="BedThickness" - "StandardWallThickness"
