"RailThickness"= .125in'Spec
"LeadScrewNutMountingHoleDiameter"= 3mm
"D9@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDiameter"
"D10@ThreadedRod'Holes-Sketch2" = "LeadScrewNutInnerShaftFlangeDiameter"
"D1@Boss-Extrude1" = "BedLength"
"BedLength"= "BuildPlateLength"
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "BuildPlateStandoffHolesDistanceFromFrontOrBackSide" * 2'Equals 270
"LeadScrewNutFlangeDiameter"= 22mm'Spec
"BedThickness"= 5mm
"FrontOrBackRailLength"= 20.5in
"D1@Sketch1"= "BedWidth"
"D2@Sketch1"="BedThickness"
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm
"D3@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D4@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D5@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D6@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D11@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"D12@ThreadedRod'Holes-Sketch2" = "LeadScrewNutMountingHoleDistance" / 2
"DistanceBetweenLeftToRightStepperHoles" = "FrontOrBackRailLength" - "Nema17MountStepperHoleDistanceFromBack" * 2 + "GapBetweenVerticalSupportsAndRails"'Equals 467.05
"BedWidth"= "DistanceBetweenLeftToRightStepperHoles" + "LeadScrewNutFlangeDiameter" + "BedWidthBeyondFlangeNut" * 2'Equals 493.05
"D2@ThreadedRod'Holes-Sketch2" = "DistanceBetweenLeftToRightStepperHoles"
"BuildPlateWidth"= 352mm'Spec
"BuildPlateLength"= 352mm'Spec
"BuildPlateStandoffHolesDistanceFromLeftOrRightSide"= 7mm
"BuildPlateStandoffHolesDistanceFromFrontOrBackSide"= 41mm
"D1@BaseOlateMountHolesSketch2"=( "BedWidth" - "BuildPlateWidth" + "BuildPlateStandoffHolesDistanceFromLeftOrRightSide" * 2)  / 2
"D2@BaseOlateMountHolesSketch2"=( "BedWidth" - "BuildPlateWidth"  + "BuildPlateStandoffHolesDistanceFromLeftOrRightSide" * 2)  / 2
"D3@BaseOlateMountHolesSketch2"= ( "BedLength" - ( "BuildPlateLength" - "BuildPlateStandoffHolesDistanceFromFrontOrBackSide" * 2 ) ) / 2
"D4@BaseOlateMountHolesSketch2" = ( "BedLength" - ( "BuildPlateLength" - "BuildPlateStandoffHolesDistanceFromFrontOrBackSide" * 2 ) ) / 2
"Nema17MountStepperHoleDistanceFromBack"= 30mm'Spec
"D7@ThreadedRod'Holes-Sketch2"="LeadScrewNutMountingHoleDistance"/2
"D8@ThreadedRod'Holes-Sketch2"="LeadScrewNutMountingHoleDistance"/2
"D13@ThreadedRod'Holes-Sketch2"="LeadScrewNutMountingHoleDistance"/2
"D14@ThreadedRod'Holes-Sketch2"="LeadScrewNutMountingHoleDistance"/2
"D15@ThreadedRod'Holes-Sketch2" = "BedLength" / 2
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
"D17@ThreadedRod'Holes-Sketch2"="DistanceFromLeadScrewNutToBedSide"
"DistanceFromLeadScrewNutToBedSide"= "LeadScrewNutFlangeDiameter" / 2 + "BedWidthBeyondFlangeNut"
"D21@ThreadedRod'Holes-Sketch2"="DistanceBetweenFrontToBackStepperHoles"
"D16@ThreadedRod'Holes-Sketch2"="BuildPlateStandoffHolesDistanceFromFrontOrBackSide"
"BedWidthBeyondFlangeNut"= 2mm
