"BedThickness"= 20mm
"BedToBuildPlateStandoffHolesDistanceFromLeftOrRight"= "BuildPlateStandoffHolesDistanceFromLeftOrRight" + "BedIncreasedByWidth" / 2'Equals 17
"BedToBuildPlateStandoffHolesDistanceFromBack"= "BuildPlateStandoffHolesDistanceFromBack" + "BedIncreasedByLength" / 2'Equals 41
"BedLLongSide"= "BedThirdSize" * 3'Equals 210
"BedLShortSide"= "BedThirdSize" * 2'Equals 140
"BedIncreasedByWidth"= 20mm
"BedIncreasedByLength"= 0mm
"BedThirdSize"= 70mm
"BedOverlap"= 20mm
"D3@TLPegHoleSketch1"="BedPegHoleHeight"
"StandardWallThickness"= 3mm
"D1@CornerBoss-Extrude1"="BedThickness"
"D1@TLPegHoleCut-Extrude1" = "StandardWallThickness"
"D1@BottomPegBoss-Extrude1"="BedPegBoss"
"D2@BottomPegCapSketch3"="StandardWallThickness"
"D1@BottomPegCapBoss-Extrude2" = "StandardWallThickness"
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"BedToBuildPlateStandoffPadSize"= 10mm
"D1@PadSketch2" = "LeadScrewNutPadSize"
"D2@PadSketch2" = "BedToBuildPlateStandoffPadSize"
"D3@PadSketch2"="BedToBuildPlateStandoffHolesDistanceFromBack"
"D4@PadSketch2"="BedToBuildPlateStandoffHolesDistanceFromLeftOrRight"
"D2@StepperRodHoleSketch3"="M3HeatInsertHoleDiameter"
"BuildPlateStandoffHolesDistanceFromLeftOrRight"= 7mm
"BuildPlateStandoffHolesDistanceFromBack"= 41mm
"D1@StepperRodHoleSketch3"="LeadScrewNutInnerShaftFlangeDiameter"
"BedLWidth"= "BedThirdSize"'Equals 70
"D4@CornerSketch1"="BedLWidth" + "BedIncreasedByLength"/2
"D2@CornerSketch1"="BedLLongSide"
"D7@CornerSketch1"="BedLWidth" +"BedOverlap"/2
"DistanceFromBedSideToStepperHole"= ( "DistanceBetweenLeftToRightStepperHoles" - "BedWidth" ) / 2'Equals 45.825
"RailThickness"= .125in'Spec
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperMountingHoleDistance"'Equals 461.65
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"FrontBackRailLength"= 510mm
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleDistance"= 31mm'Spec
"BedWidth"= "BedInnerSquareWidth" + "BedLWidth" * 2 + "BedIncreasedByWidth"'Equals 370
"D6@CornerSketch1"="DistanceFromBedSideToStepperHole"
"DistanceFromBedFrontToStepperHole"= "LeadScrewNutPadSize" + 10mm
"D3@CornerSketch1"="DistanceFromBedFrontToStepperHole"
"D5@CornerSketch1"="BedLShortSide" +"BedIncreasedByWidth"/2
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountHoleDiameter"= 2mm'Spec is 4.1 but smaller for tapping
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm'Spec
"D3@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"
"D4@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"/2
"D5@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"
"D2@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"/2
"D1@ThreadedNutMountHolesSketch4"="LeadScrewNutMountHoleDiameter"
"LeadScrewNutPadDepth"= "BedThickness" / 2'Equals 10
"D1@ThreadedNutMountHolesCut-Extrude2"="LeadScrewNutPadDepth"
"D1@PadBoss-Extrude2"= "LeadScrewNutPadDepth"
"BedPegHoleWidth"= 10mm
"BedPegHoleHeight"= "BedThickness" - "StandardWallThickness" * 2'Equals 14
"BedPegWidth"= "BedPegHoleWidth" - .1mm * 2'For easier assembly
"BedPegHeight"= "BedPegHoleHeight" - .1mm'For easier assembly
"BedTopPegOffsetFromSide"= 10mm
"BedPegBoss"= "StandardWallThickness" + .1mm'For easier assembly
"BedPegCapHeight"= "BedThickness" - "StandardWallThickness"'Equals 17
"BedPegCapWidth"= "BedThickness" / 2 + "StandardWallThickness" * 2'Equals 16
"D1@TLPegHoleSketch1"="BedTopPegOffsetFromSide"
"D2@TLPegHoleSketch1"="BedPegHoleWidth"
"D3@BottomPegSketch2"="BedPegWidth"
"D2@BottomPegSketch2"="BedPegHeight"
"D1@BottomPegCapSketch3"="BedPegCapWidth"
"D3@BottomPegCapSketch3"="BedPegCapHeight"
"D1@BedCenterHoleCutSketch1" = "BedPegHoleHeight"
"D2@BedCenterHoleCutSketch1" = "BedPegHoleWidth"
"D3@BedCenterHoleCutSketch1" = "BedInnerSquareWidth" / 2 - "BedPegHoleWidth" / 2
"D1@BedCenterHoleCut-Extrude1"="StandardWallThickness"
"M3HeatInsertHoleDiameter"= 4mm'Spec
