"BedThickness"= 20mm
"BedToBuildPlateStandoffHolesDistanceFromLeftOrRight"= "BuildPlateStandoffHolesDistanceFromLeftOrRight" + "BedIncreasedByWidth" / 2'Equals 17
"BedToBuildPlateStandoffHoleSize"= 3mm
"BedLLongSide"= "BedThirdSize" * 3'Equals 210
"BedLShortSide"= "BedThirdSize" * 2'Equals 140
"BedLWidth"= "BedThirdSize"'Equals 70
"D4@CornerrSketch1"="BedLWidth" + "BedIncreasedByWidth"/2
"BedIncreasedByWidth"= 20mm
"BedIncreasedByLength"= 0mm
"BedThirdSize"= 70mm
"StandardWallThickness"= 3mm
"D2@TopPegHoleSketch4"="BedPegHoleWidth"
"D3@TopPegHoleSketch4"="BedPegHoleHeight"
"D1@TopPegHoleCut-Extrude2" = "StandardWallThickness"
"D3@BLPegSketch5"="BedPegWidth"
"D1@BLPegBoss-Extrude3"="BedPegBoss"
"D2@BLPegSketch5"="BedPegHeight"
"D2@BLPegCapSketch6"="StandardWallThickness"
"D3@BLPegCapSketch6"="BedPegCapHeight"
"D1@BLPegCapBoss-Extrude4" = "StandardWallThickness"
"D3@CornerrSketch1"="BedLWidth" 
"D1@PadSketch1" = "BedToBuildPlateStandoffPadSize"
"D1@PadBoss-Extrude1"="LeadScrewNutPadDepth"
"BedToBuildPlateStandoffPadSize"= 10mm
"BedToBuildPlateStandoffHolesDistanceFromBack"= "BuildPlateStandoffHolesDistanceFromBack" + "BedIncreasedByLength" / 2'Equals 41
"BuildPlateStandoffHolesDistanceFromLeftOrRight"= 7mm
"BuildPlateStandoffHolesDistanceFromBack"= 41mm
"DistanceFromBedSideToStepperHole"= ( "DistanceBetweenLeftToRightStepperHoles" - "BedWidth" ) / 2'Equals 45.825
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperMountingHoleDistance"'Equals 461.65
"FrontBackRailLength"= 510mm
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleDistance"= 31mm'Spec
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"RailThickness"= .125in'Spec
"BedWidth"= "BedInnerSquareWidth" + "BedLWidth" * 2 + "BedIncreasedByWidth"'Equals 370
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"D1@CornerrSketch1"="BedLLongSide"  + "BedIncreasedByWidth"/2
"D2@CornerrSketch1"="DistanceFromBedSideToStepperHole"
"D3@PadSketch1"="BedToBuildPlateStandoffHolesDistanceFromLeftOrRight"
"D2@PadSketch1"="BedToBuildPlateStandoffHolesDistanceFromBack"
"D1@TopPegHoleSketch4"="BedTopPegOffsetFromSide"
"D1@BLPegSketch5"="BedTopPegOffsetFromSide" + .1mm
"D6@CornerrSketch1"="BedLShortSide" + "BedIncreasedByLength"/2
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"D4@PadSketch1"="LeadScrewNutPadSize"
"D1@StepperShaftCut-Sketch3"="LeadScrewNutInnerShaftFlangeDiameter"
"D2@StepperShaftCut-Sketch3" = "BedToBuildPlateStandoffHoleSize"
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountHoleDiameter"= 2mm'Spec is 4.1 but smaller for tapping
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm'Spec
"D1@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"/2
"D2@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"
"D4@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"/2
"D5@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"
"D3@ThreadedNutMountHolesSketch5"="LeadScrewNutMountHoleDiameter"
"LeadScrewNutPadDepth"= "BedThickness" / 2'Equals 10
"D1@ThreadedNutMountHolesCut-Extrude2"= "LeadScrewNutPadDepth"
"BedPegHoleWidth"= 10mm
"BedPegHoleHeight"= "BedThickness" - "StandardWallThickness" * 2'Equals 14
"BedPegWidth"= "BedPegHoleWidth" - .1mm * 2'For easier assembly
"BedPegHeight"= "BedPegHoleHeight" - .1mm'For easier assembly
"BedTopPegOffsetFromSide"= 10mm
"BedPegBoss"= "StandardWallThickness" + .1mm'For easier assembly
"BedPegCapHeight"= "BedThickness" - "StandardWallThickness"'Equals 17
"BedPegCapWidth"= "BedThickness" / 2 + "StandardWallThickness" * 2'Equals 16
"D1@BLPegCapSketch6"="BedPegCapWidth"
"D1@BedCenterPegHoleCutSketch1" = "BedPegHoleHeight"
"D3@BedCenterPegHoleCutSketch1" = "BedInnerSquareWidth" / 2 - "BedPegHoleWidth" / 2
"D2@BedCenterPegHoleCutSketch1" = "BedPegHoleWidth"
"D1@BedCenterPegHoleCut-Extrude1"="StandardWallThickness"
