"RailThickness"= .125in'Spec
"StepperMountingHoleDistance"= 31mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"FrontBackRailLength"= 510mm
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperMountingHoleDistance"'Equals 461.65
"BedThickness"= 20mm
"BedToBuildPlateStandoffHoleSize"= 3mm
"BedLLongSide"= "BedThirdSize" * 3'Equals 210
"BedLShortSide"= "BedThirdSize" * 2'Equals 140
"BedLWidth"= "BedThirdSize" + "BedOverlap"'Equals 90
"D4@CornerrSketch1"="BedLWidth" + "BedIncreasedByWidth"/2
"D1@CornerrSketch1" = "BedLLongSide" + "BedIncreasedByWidth" / 2
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"BedOverlap"= 20mm
"BedWidth"= "BedInnerSquareWidth" + "BedLWidth" * 2 - "BedOverlap" * 2 + "BedIncreasedByWidth"'Equals 370
"BedIncreasedByWidth"= 20mm
"BedIncreasedByLength"= 0mm
"BedThirdSize"= 70mm
"D3@Tab holes-Sketch1"=55mm
"D1@TRPegCapSketch2"="BedTopPegCapWidth"
"StandardWallThickness"= 3mm
"D2@TRPegCapSketch2" = "StandardWallThickness"
"D3@TRPegCapSketch2"="BedTopPegCapHeight"
"D1@TRPegCapBoss-Extrude2" = "StandardWallThickness"
"D1@BottomPegHoleCut-Extrude1"="StandardWallThickness"
"D1@Shell2"="StandardWallThickness"
"D2@TRPegSketch1"="BedTopPegHeight"
"D5@CornerrSketch1"="DistanceFromBedSideToStepperHole"
"DistanceFromBedFrontToStepperHole"= "LeadScrewNutPadSize" + 10mm
"DistanceFromBedSideToStepperHole"= ( "DistanceBetweenLeftToRightStepperHoles" - "BedWidth" ) / 2'Equals 45.825
"D7@CornerrSketch1"= "BedLShortSide" + "BedIncreasedByLength" / 2
"D3@CornerrSketch1"="DistanceFromBedFrontToStepperHole"
"BedToBuildPlateStandoffPadSize"= 10mm
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"D1@PadSketch3" = "LeadScrewNutPadSize"
"D1@StepperShaftHoleSketch4"="LeadScrewNutInnerShaftFlangeDiameter"
"D11@CornerrSketch1"="BedLWidth"
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountHoleDiameter"= 2mm'Spec is 4.1 but smaller for tapping
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm'Spec
"D2@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance" / 2
"D3@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"
"D5@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"
"D4@ThreadedNutMountHolesSketch5"="LeadScrewNutMountingHoleDistance"/2
"D1@ThreadedNutMountHolesSketch5"="LeadScrewNutMountHoleDiameter"
"LeadScrewNutPadDepth"= "BedThickness" / 2'Equals 10
"D1@ThreadedNutMountHolesCut-Extrude4"="LeadScrewNutPadDepth"
"D2@PadSketch3"="BedToBuildPlateStandoffPadSize"
"D3@PadSketch3"="BedToBuildPlateStandoffHolesDistanceFromFront"
"BuildPlateWidth"= 350mm'Spec
"D4@PadSketch3"="BedIncreasedByWidth"/2 + "BuildPlateWidth"/2
"D2@StepperShaftHoleSketch4"="BedToBuildPlateStandoffHoleSize"
"BuildPlateStandoffHolesDistanceFromFront"= 7mm
"BedToBuildPlateStandoffHolesDistanceFromFront"= "BuildPlateStandoffHolesDistanceFromFront" + "BedIncreasedByLength" / 2'Equals 7
"BedTopPegHoleWidth"= 10mm
"BedTopPegHoleHeight"= "BedThickness"- "StandardWallThickness"* 2' Equals 14
"BedTopPegWidth"= "BedTopPegHoleWidth"- .1mm* 2'For easier assembly
"BedTopPegHeight"= "BedTopPegHoleHeight"- .1mm'For easier assembly
"BedTopPegOffsetFromSide"= 10mm
"BedTopPegBoss"= "StandardWallThickness"+ .1mm'For easier assembly
"BedTopPegCapHeight"= "BedThickness"- "StandardWallThickness"'Equals 17
"BedTopPegCapWidth"= "BedThickness"/2 + "StandardWallThickness"*2'Equals 16
"D1@TRPegSketch1"="BedTopPegOffsetFromSide" + .1mm
"D3@TRPegSketch1"= "BedTopPegWidth"
"D1@TRPegBoss-Extrude1"="BedTopPegBoss"
"D3@BottomPegHoleSketch3"="BedTopPegOffsetFromSide"
"D2@BottomPegHoleSketch3"="BedTopPegHoleWidth"
"D6@Tab holes-Sketch1"="BedOverlap"
"D1@Tab holes-Sketch1"="BedOverlap"/2
"D4@Tab holes-Sketch1"="BedOverlap"
"D2@Tab holes-Sketch1"="BedOverlap"/2
"D1@PutBackShellSketch2"="BedOverlap" + "StandardWallThickness"
"D1@PutBackShellBoss-Extrude1"="BedThickness"- "StandardWallThickness"
"D1@OverlapChamfer1"="BedThickness"
"D3@OverlapChamfer1"="BedOverlap"
