"BedThickness"= 20mm
"BedToBuildPlateStandoffHolesDistanceFromLeftOrRight"= "BuildPlateStandoffHolesDistanceFromLeftOrRight" + "BedIncreasedByWidth" / 2'Equals 17
"BedToBuildPlateStandoffHolesDistanceFromBack"= "BuildPlateStandoffHolesDistanceFromBack" + "BedIncreasedByLength" / 2'Equals 41
"BedToBuildPlateStandoffHoleSize"= 3mm
"BedLLongSide"= "BedThirdSize" * 3'Equals 210
"BedLShortSide"= "BedThirdSize" * 2'Equals 140
"BedIncreasedByWidth"= 20mm
"BedIncreasedByLength"= 0mm
"BedThirdSize"= 70mm
"BedOverlap"= 20mm
"D2@TabHoleCutsSketch1"= 55mm
"D3@TabHoleCutsSketch1" = "BedOverlap"
"D5@TabHoleCutsSketch1" = "BedOverlap"
"D6@TabHoleCutsSketch1" = "BedOverlap" / 2
"D3@TLPegHoleSketch1"="BedTopPegHoleHeight"
"StandardWallThickness"= 3mm
"D1@CornerBoss-Extrude1"="BedThickness"
"D1@TLPegHoleCut-Extrude1" = "StandardWallThickness"
"D1@BottomPegBoss-Extrude1"="BedTopPegBoss"
"D2@BottomPegCapSketch3"="StandardWallThickness"
"D1@BottomPegCapBoss-Extrude2" = "StandardWallThickness"
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"BedToBuildPlateStandoffPadSize"= 10mm
"D1@PadSketch2" = "LeadScrewNutPadSize"
"D2@PadSketch2" = "BedToBuildPlateStandoffPadSize"
"D3@PadSketch2"="BedToBuildPlateStandoffHolesDistanceFromBack"
"D4@PadSketch2"="BedToBuildPlateStandoffHolesDistanceFromLeftOrRight"
"D2@StepperRodHoleSketch3"="BedToBuildPlateStandoffHoleSize"
"BuildPlateStandoffHolesDistanceFromLeftOrRight"= 7mm
"BuildPlateStandoffHolesDistanceFromBack"= 41mm
"D1@StepperRodHoleSketch3"="LeadScrewNutInnerShaftFlangeDiameter"
"BedLWidth"= "BedThirdSize" + "BedOverlap"'Equals 90
"D4@CornerSketch1"="BedLWidth" + "BedIncreasedByLength"/2
"D2@CornerSketch1"="BedLLongSide"
"D7@CornerSketch1"="BedLWidth" +"BedOverlap"/2
"DistanceFromBedSideToStepperHole"= ( "DistanceBetweenLeftToRightStepperHoles" - "BedWidth" ) / 2'Equals 45.825
"RailThickness"= .125in'Spec
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperMountingHoleDistance"'Equals 461.65
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"FrontBackRailLength"= 510mm
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleDistance"= 31mm'Spec
"BedWidth"= "BedInnerSquareWidth" + "BedLWidth" * 2 - "BedOverlap" * 2 + "BedIncreasedByWidth"'Equals 370
"D6@CornerSketch1"="DistanceFromBedSideToStepperHole"
"DistanceFromBedFrontToStepperHole"= "LeadScrewNutPadSize" + 10mm
"D3@CornerSketch1"="DistanceFromBedFrontToStepperHole"
"D5@CornerSketch1"="BedLShortSide" +"BedIncreasedByWidth"/2
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountHoleDiameter"= 2mm'Spec is 4.1 but smaller for tapping
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm'Spec
"D3@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"
"D4@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"/2
"D5@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"
"D2@ThreadedNutMountHolesSketch4"="LeadScrewNutMountingHoleDistance"/2
"D1@ThreadedNutMountHolesSketch4"="LeadScrewNutMountHoleDiameter"
"LeadScrewNutPadDepth"= "BedThickness" / 2'Equals 10
"D1@ThreadedNutMountHolesCut-Extrude2"="LeadScrewNutPadDepth"
"D1@PadBoss-Extrude2"= "LeadScrewNutPadDepth"
"BedTopPegHoleWidth"= 10mm
"BedTopPegHoleHeight"= "BedThickness"- "StandardWallThickness"* 2' Equals 14
"BedTopPegWidth"= "BedTopPegHoleWidth"- .1mm* 2'For easier assembly
"BedTopPegHeight"= "BedTopPegHoleHeight"- .1mm'For easier assembly
"BedTopPegOffsetFromSide"= 10mm
"BedTopPegBoss"= "StandardWallThickness"+ .1mm'For easier assembly
"BedTopPegCapHeight"= "BedThickness"- "StandardWallThickness"'Equals 17
"BedTopPegCapWidth"= "BedThickness"/2 + "StandardWallThickness"*2'Equals 16
"D1@TLPegHoleSketch1"="BedTopPegOffsetFromSide"
"D2@TLPegHoleSketch1"="BedTopPegHoleWidth"
"D3@BottomPegSketch2"="BedTopPegWidth"
"D2@BottomPegSketch2"="BedTopPegHeight"
"D1@BottomPegCapSketch3"="BedTopPegCapWidth"
"D3@BottomPegCapSketch3"="BedTopPegCapHeight"
"D1@PutBackPartOfShellSketch1"="BedOverlap" + "StandardWallThickness"
"D1@PutBackPartOfShellBoss-Extrude1"="BedThickness"- "StandardWallThickness"
"D1@OverlapChamfer1"="BedThickness"
"D3@OverlapChamfer1" = "BedOverlap"
