"ProbeMountHeight"= "ProbeMountDepth" + "ProbeMountUpperHeight"
"D1@ProfileSketch1" = "ProbeMountHeight"
"D1@Boss-Extrude1"= "ProbeBodyWidth"
"M3HeatInsertHoleDiameter"= 4.1mm'Spec
"ProbeBodyDepth"= 15mm
"ProbeBodyWidth"= 26mm
"BLTouchProbeMountHoleDistance"= 18mm
"ProbeMountUpperHeight"= "M3ScrewButtonHeadHeight" * 2 + "M3ScrewDiameter" * 5 + "M3ScrewButtonHeadHeight" * 2
"D2@ProfileSketch1"="ProbeBodyDepth"
"D3@ProfileSketch1"= "ProbeMountDepth"
"D4@ProfileSketch1"="ProbeMountDepth"+1mm
"D1@BLTouchProbeMountHolesSketch2" = "BLTouchProbeMountHoleDistance"
"D2@BLTouchProbeMountHolesSketch2" =  ( "ProbeBodyWidth" - "BLTouchProbeMountHoleDistance" )  / 2
"D4@BLTouchProbeMountHolesSketch2" = "M3HeatInsertHoleDiameter"
"M3ScrewButtonHeadHeight"= 2.4mm
"D1@ProbeSlidingMountSketch4" = "M3ScrewDiameter"
"D2@ProbeSlidingMountSketch4" = 3mm * 3
"M3ScrewDiameter"= 3.1mm
"D3@ProbeSlidingMountSketch4" = "M3ScrewButtonHeadHeight" * 2 + "M3ScrewDiameter"
"ProbeMountDepth"= 3mm
"M3ScrewButtonHeadDiameter"= 5.9mm
"D1@ProbeSlidingMountChannelSketch5"="M3ScrewButtonHeadDiameter"+ .5mm
"D2@CableChannelSketch1" =  ( "ProbeBodyWidth" - "BLTouchCableWidth" )  / 2
"BLTouchCableWidth"= 5.5mm
"D1@CableChannelSketch1" = "BLTouchCableWidth"
"BLTouchCableThickness"= 1.5mm
"D1@CableCut-Extrude1" = "BLTouchCableThickness"
"BLTouchMountingHoleOffsetFromBack"= 8.5mm
"D3@BLTouchProbeMountHolesSketch2" = "BLTouchMountingHoleOffsetFromBack"
"ProbeMountHolesDistance"=11.6
"D5@ProbeSlidingMountSketch4"=("ProbeBodyWidth" - "ProbeMountHolesDistance")/2
"D4@ProbeSlidingMountSketch4"="ProbeMountHolesDistance"
