"CarrierWidth"= "LinearGBWidthWithBumpers" - 2mm
"LinearGBWidth"= 27mm'Spec
"D10@BackFace-Sketch1"="CarrierWidth"
"LinearGBWidthWithBumpers"= 45.4mm
"LinearGBMountHolesXDistance"= 20mm'Spec
"LinearGBMountHolesYDistance"= 20mm'Spec
"D1@RearMountingHoles-Sketch2"="LinearGBMountHolesXDistance"
"D2@RearMountingHoles-Sketch2"="LinearGBMountHolesYDistance"
"D5@RearMountingHoles-Sketch2"= ( "LinearGBWidth" - "LinearGBMountHolesYDistance" ) / 2
"CarrierRibbonHoleWidth"= 7mm
"CarrierRibbonHoleHeight"= 2.7mm
"CarrierRibbonHoleDistance"= 2.5mm'Equals 2.5. Must equal distance created by GABRiserBossOffset
"CarrierRibbonHoleOffsetFromSide"= 3.0mm
"CarrierDepth"= 20mm
"D1@Boss-Extrude1"="CarrierDepth"
"D3@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleHeight"
"D4@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleWidth"
"D5@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleDistance"
"D9@BackFace-Sketch1"="LinearGBWidth"
"D2@RearRibbonHoles-Sketch2"="CarrierRibbonHoleOffsetFromSide"
"D1@RearRibbonHoles-Sketch2"="CarrierRibbonHoleOffsetFromSide"
"D1@RightRibbonHoles-Cut-Extrude2" = "CarrierRibbonHoleOffsetFromSide" + "CarrierRibbonHoleHeight"
"LinearRailHeight"= 8mm'Spec
"LinearGBDepth"= 10mm'Spec
"D1@BlockUnderRail-Boss-Extrude2"="MiddleOfGBAndLinearRail" +  "CarrierRibbonHoleHeight"
"D1@LeftRibbonHoles-Cut-Extrude2" = "CarrierRibbonHoleOffsetFromSide" + "CarrierRibbonHoleHeight"
"D1@RightRibbonHoles-Sketch4"="CarrierRibbonHoleHeight"
"D1@RearRibbonHoles-Cut-Extrude1"="MiddleOfGBAndLinearRail" - "CarrierRibbonHoleHeight"/2mm
"D1@LeftRibbonHoles-Sketch3"="CarrierRibbonHoleHeight"
"MiddleOfGBAndLinearRail"= "LinearGBDepth" / 2 + "LinearRailHeight" / 2
"CarrierUpperBodyLength"= "CarrierBodyLength" - "LinearGBWidth" - "CarrierLowerBodyLength"
"CarrierLowerBodyLength"= "CarrierRibbonHoleWidth" * 2 + "CarrierRibbonHoleDistance" + 5mm * 2
"D3@BackFace-Sketch1"="CarrierLowerBodyLength"
"D11@BackFace-Sketch1"="CarrierUpperBodyLength"
"CarrierBodyLength"= 59.3mm - 1.39mm'From the 100 1.39 accounts for the little slant
"M3HeatInsertHoleDiamter"=4
"LM8UUHeight"= 24mm'Spec
"ZAxisLeadScrewLength"= 200mm
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"V1 BottomOfLowerRail"= "LegHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"V2 ToBedAtTopOfZAxis"= "V1 BottomOfLowerRail" - "LowerEnclosureThickness" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2'Equals 277
"HotEndToTopOfXAxisGB"= 71.68487mm'Equals 71.68487. Measured after installed onto X-Axis linear rail guide block
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2'Equals 19.5
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"'Equals 352.18487
"LinearRailWidth"= 12mm'Spec
"V6 ToMiddleOfYAxisGantryBlock"= "V5 ToBottomOfXAxisLinearRail" - "GABHeight" / 2'Equals 334.18487
"LowerEnclosureThickness"= 5mm
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"GABLowerHeight"= 4mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"GABUpperHeight"= 4mm
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"V5.1 ToBottomXAxisGBMountingHole"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "LinearGBWidth" / 2 - "LinearGBMountHolesYDistance" / 2
"DistanceFromBottomXAxisGBMountingHoleAndMiddleOfGantryBlock"= "V5.1 ToBottomXAxisGBMountingHole" - "V6 ToMiddleOfYAxisGantryBlock" - "CarrierRibbonHoleDistance" / 2
"D6@RearRibbonHoles-Sketch2"="DistanceFromBottomXAxisGBMountingHoleAndMiddleOfGantryBlock"
"D1@BottomClampMountingHolesSketch3"="M3HeatInsertHoleDiamter"
"M3HeatInsertHoleDepth"= 4.1mm'Spec
"D1@BottomClampMountHolesCut-Extrude1"="M3HeatInsertHoleDepth"
"D1@RibbonHoleFillet1" = "CarrierRibbonHoleHeight"
"D1@RibbonHoleFillet2"="CarrierRibbonHoleHeight"
"D1@RibbonHoleFillet3"="CarrierRibbonHoleHeight"
"D1@RibbonHoleFillet4"="CarrierRibbonHoleHeight"
