"CarrierWidth"= "LinearGBWidthWithBumpers" - 2mm
"LinearGBWidth"= 27mm'Spec
"D10@BackFace-Sketch1"="CarrierWidth"
"LinearGBWidthWithBumpers"= 45.4mm
"LinearGBMountHolesXDistance"= 20mm'Spec
"LinearGBMountHolesYDistance"= 20mm'Spec
"D1@RearMountingHoles-Sketch2"="LinearGBMountHolesXDistance"
"D2@RearMountingHoles-Sketch2"="LinearGBMountHolesYDistance"
"D5@RearMountingHoles-Sketch2"= ( "LinearGBWidth" - "LinearGBMountHolesYDistance" ) / 2
"CarrierRibbonHoleWidth"= 7mm
"CarrierRibbonHoleHeight"= 2.7mm
"CarrierRibbonHoleDistance"= 2mm
"CarrierRibbonHoleOffsetFromSide"= 3.0mm
"CarrierDepth"= 20mm
"D1@Boss-Extrude1"="CarrierDepth"
"D3@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleHeight"
"D4@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleWidth"
"D5@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleDistance"
"D9@BackFace-Sketch1"="LinearGBWidth"
"D2@RearRibbonHoles-Sketch2"="CarrierRibbonHoleOffsetFromSide"
"D1@RearRibbonHoles-Sketch2"="CarrierRibbonHoleOffsetFromSide"
"D1@RightRibbonHoles-Cut-Extrude2" = "CarrierRibbonHoleOffsetFromSide" + "CarrierRibbonHoleHeight"
"LinearRailHeight"= 8mm'Spec
"LinearGBDepth"= 10mm'Spec
"D1@BlockUnderRail-Boss-Extrude2"="MiddleOfGBAndLinearRail" +  "CarrierRibbonHoleHeight"
"D1@LeftRibbonHoles-Cut-Extrude2" = "CarrierRibbonHoleOffsetFromSide" + "CarrierRibbonHoleHeight"
"D1@RightRibbonHoles-Sketch4"="CarrierRibbonHoleHeight"
"D1@RearRibbonHoles-Cut-Extrude1"="MiddleOfGBAndLinearRail" - "CarrierRibbonHoleHeight"/2mm
"D1@LeftRibbonHoles-Sketch3"="CarrierRibbonHoleHeight"
"MiddleOfGBAndLinearRail"= "LinearGBDepth" / 2 + "LinearRailHeight" / 2
"CarrierUpperBodyLength"= 13mm
"CarrierLowerBodyLength"= 29mm
"D3@BackFace-Sketch1"="CarrierLowerBodyLength"
"D11@BackFace-Sketch1"="CarrierUpperBodyLength"
"CarrierRibbonHoleOffsetFromBottom"= 7.4mm
"D6@RearRibbonHoles-Sketch2"="CarrierRibbonHoleOffsetFromBottom"
