"CarrierRibbonHoleWidth"= 7mm
"CarrierRibbonHoleHeight"= 2.7mm
"CarrierRibbonHoleDistance"= 2.5mm'Equals 2.5. Must equal distance created by GABRiserBossOffset
"CarrierRibbonHoleOffsetFromSide"= 3.0mm
"CarrierDepth"= 20mm'From the100
"D1@Boss-Extrude1"="CarrierDepth"
"D3@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleHeight"
"D4@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleWidth"
"D5@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleDistance"
"D1@RightRibbonHoles-Cut-Extrude2" = "CarrierRibbonHoleOffsetFromSide" + "CarrierRibbonHoleHeight"
"D1@LeftRibbonHoles-Cut-Extrude2" = "CarrierRibbonHoleOffsetFromSide" + "CarrierRibbonHoleHeight"
"D1@RightRibbonHoles-Sketch4"="CarrierRibbonHoleHeight"
"D1@RearRibbonHoles-Cut-Extrude1"="CarrierDepth" / 2 + "CarrierRibbonHoleHeight"/2
"D1@LeftRibbonHoles-Sketch3"="CarrierRibbonHoleHeight"
"AngledCarrierBodyLength"= "CarrierBodyLength" - 1.39mm'From the 100 1.39 accounts for the little slant
"M3HeatInsertHoleDiameter"= 4mm + .1mm'Add .1mm for printing
"D1@BottomClampMountingHolesSketch3"="M3HeatInsertHoleDiameter"
"M3HeatInsertHoleDepth"= 4mm
"D1@BottomClampMountHolesCut-Extrude1"="M3HeatInsertHoleDepth"
"D1@RibbonHoleFillet1" = "CarrierRibbonHoleHeight"
"D1@RibbonHoleFillet2"="CarrierRibbonHoleHeight"
"D1@RibbonHoleFillet3"="CarrierRibbonHoleHeight"
"D1@RibbonHoleFillet4"="CarrierRibbonHoleHeight"
"D4@TopHoles-Sketch3"="M3HeatInsertHoleDiameter"
"D2@FrontHoles-Sketch1"="M3HeatInsertHoleDiameter"
"D3@BackFace-Sketch1"= "AngledCarrierBodyLength"
"D1@RearRibbonHoles-Sketch2"="CarrierRibbonHoleOffsetFromSide"
"D2@RearRibbonHoles-Sketch2"="CarrierRibbonHoleOffsetFromSide"
"D2@LM8UUHolesSketch1"="CarrierDepth" / 2 
"GABDistanceBetweenXAxisRods"= 34.6mm'From the100
"D3@LM8UUHolesSketch1"="GABDistanceBetweenXAxisRods"
"LM8UUDiameter"= 15mm
"D1@LM8UUHolesSketch1"="LM8UUDiameter" + .1mm
"CarrierBodyLength"= 57.91mm
"D4@LM8UUHolesSketch1" = ( "AngledCarrierBodyLength" - "GABDistanceBetweenXAxisRods" ) / 2
"D6@RearRibbonHoles-Sketch2"=("AngledCarrierBodyLength" - "CarrierRibbonHoleWidth" * 2 - "CarrierRibbonHoleDistance")/2
"CarrierWidth"= 30mm
"D7@BackFace-Sketch1"="CarrierWidth"
"D2@ProbeMountingHolesSketch1" =  ( "CarrierWidth" - "ProbeDistanceBetweenMountingHoles" )  / 2
"M2HeatInsertHoleDiameter"= 3mm + .1mm'Add .1mm for printing
"M2HeatInsertHoleDepth"= 3.1mm'Spec
"D4@ProbeMountingHolesSketch1" = "M2HeatInsertHoleDiameter"
"D1@ProbeMountingHolesCut-Extrude1" = "M2HeatInsertHoleDepth"
"ProbeDistanceBetweenMountingHoles" = 11mm
"D1@ProbeMountingHolesSketch1" = "ProbeDistanceBetweenMountingHoles"
"LM8UUFasteningHoleDiameter"= 4.2mm'10/24 set screw hole diameter
"D1@LM8UUFasteningHoleSketch1" = "LM8UUDiameter" / 2 + "LM8UUFasteningHoleDiameter" / 2 - 1mm
"D2@LM8UUFasteningHoleSketch1" = "LM8UUDiameter" / 2 + "LM8UUFasteningHoleDiameter" / 2 - 1mm
"D3@LM8UUFasteningHoleSketch1" = "CarrierWidth" / 2
"D1@LM8UUFasteningHoleCut-Extrude1"= "CarrierDepth" / 2 + 4mm'Odd that up to next does not work properly
