"CarrierWidth"= "LinearGBWidthWithBumpers" - 2mm
"LinearGBWidth"= 27mm'Spec
"D10@BackFace-Sketch1"="CarrierWidth"
"LinearGBWidthWithBumpers"= 45.4mm
"LinearGBMountHolesXDistance"= 20mm'Spec
"LinearGBMountHolesYDistance"= 20mm'Spec
"D1@RearMountingHoles-Sketch2"="LinearGBMountHolesXDistance"
"D2@RearMountingHoles-Sketch2"="LinearGBMountHolesYDistance"
"D5@RearMountingHoles-Sketch2"= ( "LinearGBWidth" - "LinearGBMountHolesYDistance" ) / 2
"CarrierRibbonHoleWidth"= 7mm
"CarrierRibbonHoleHeight"= 2.7mm
"CarrierRibbonHoleDistance"= 2.5mm'Equals 2.5. Must equal distance created by GABRiserBossOffset
"CarrierRibbonHoleOffsetFromSide"= 3.0mm
"CarrierDepth"= 19mm
"D1@Boss-Extrude1"="CarrierDepth"
"D3@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleHeight"
"D4@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleWidth"
"D5@RearRibbonHoles-Sketch2" = "CarrierRibbonHoleDistance"
"D9@BackFace-Sketch1"="LinearGBWidth"
"D2@RearRibbonHoles-Sketch2"="CarrierRibbonHoleOffsetFromSide"
"D1@RearRibbonHoles-Sketch2"="CarrierRibbonHoleOffsetFromSide"
"D1@RightRibbonHoles-Cut-Extrude2" = "CarrierRibbonHoleOffsetFromSide" + "CarrierRibbonHoleHeight"
"LinearRailHeight"= 8mm'Spec
"LinearGBDepth"= 10mm'Spec
"D1@BlockUnderRail-Boss-Extrude2"="MiddleOfGBAndLinearRail" +  "CarrierRibbonHoleHeight"
"D1@LeftRibbonHoles-Cut-Extrude2" = "CarrierRibbonHoleOffsetFromSide" + "CarrierRibbonHoleHeight"
"D1@RightRibbonHoles-Sketch4"="CarrierRibbonHoleHeight"
"D1@RearRibbonHoles-Cut-Extrude1"="MiddleOfGBAndLinearRail" - "CarrierRibbonHoleHeight"/2mm
"D1@LeftRibbonHoles-Sketch3"="CarrierRibbonHoleHeight"
"MiddleOfGBAndLinearRail"= "LinearGBDepth" / 2 + "LinearRailHeight" / 2
"CarrierUpperBodyLength"= "CarrierBodyLength" - "LinearGBWidth" - "CarrierLowerBodyLength"
"CarrierLowerBodyLength"= "CarrierRibbonHoleWidth" * 2 + "CarrierRibbonHoleDistance" + 5mm * 2
"D3@BackFace-Sketch1"="CarrierLowerBodyLength"
"D11@BackFace-Sketch1"="CarrierUpperBodyLength"
"CarrierBodyLength"= 59.3mm - 1.39mm'From the 100 1.39 accounts for the little slant
"M3HeatInsertHoleDiamter"=4
"LinearGBWidth"= 27mm'Spec
"D1@BottomClampMountingHolesSketch3"="M3HeatInsertHoleDiamter"
"M3HeatInsertHoleDepth"= 4.1mm'Spec
"D1@BottomClampMountHolesCut-Extrude1"="M3HeatInsertHoleDepth"
"D1@RibbonHoleFillet1" = "CarrierRibbonHoleHeight"
"D1@RibbonHoleFillet2"="CarrierRibbonHoleHeight"
"D1@RibbonHoleFillet3"="CarrierRibbonHoleHeight"
"D1@RibbonHoleFillet4"="CarrierRibbonHoleHeight"
"M3ScrewHoleDiameter"= 3mm
"M3ButtonHeadDiameter"= 5.5mm
"D6@RearMountingHoles-Sketch2"="M3ScrewHoleDiameter"
"D1@RearMountingHolesBoreSketch4"="M3ButtonHeadDiameter"
"D4@TopHoles-Sketch3"="M3HeatInsertHoleDiamter"
"D2@FrontHoles-Sketch1"="M3HeatInsertHoleDiamter"
