node SWECompare -v .\BackLeftVerticalSupportEquations.txt
node SWECompare -v .\BackRightVerticalSupportEquations.txt
node SWECompare -v .\BedBLEquations.txt
node SWECompare -v .\BedFLEquations.txt
node SWECompare -v .\BedCEquations.txt
node SWECompare -v .\BedBREquations.txt
node SWECompare -v .\BedFREquations.txt
node SWECompare -v .\LeftBeltTensionerEquations.txt
node SWECompare -v .\RightBeltTensionerEquations.txt
node SWECompare -v .\BuildPlateEquations.txt
node SWECompare -v .\FrontLeftVerticalSupportEquations.txt
node SWECompare -v .\FrontRightVerticalSupportEquations.txt
node SWECompare -v .\LeftGantryBlockEquations.txt
node SWECompare -v .\LinearGuideBlockEquations.txt
node SWECompare -v .\LeftXAxisLinearRailSupportEquations.txt
node SWECompare -v .\RightXAxisLinearRailSupportEquations.txt
node SWECompare -v .\XAxisLinearRailConnectingPlateEquations.txt
node SWECompare -v .\LowerBackRailEquations.txt
node SWECompare -v .\LowerFrontRailEquations.txt
node SWECompare -v .\LowerLeftRailEquations.txt
node SWECompare -v .\LowerRightRailEquations.txt
node SWECompare -v .\MGN12H-450Equations.txt
node SWECompare -v .\MidBackRailEquations.txt
node SWECompare -v .\MidLeftRailEquations.txt
node SWECompare -v .\MidRightRailEquations.txt
node SWECompare -v .\RightGantryBlockEquations.txt
node SWECompare -v .\UpperBackRailEquations.txt
node SWECompare -v .\UpperFrontRailEquations.txt
node SWECompare -v .\UpperLeftRailEquations.txt
node SWECompare -v .\UpperRightRailEquations.txt
node SWECompare -v .\CarrierEquations.txt
node SWECompare -v .\MicroSwitchEquations.txt
node SWECompare -v .\RodStabilizerEquations.txt
node SWECompare -v .\VerticalSupportYardStickEquations.txt
node SWECompare -v .\BedToBuildPlateStandoffEquations.txt
node SWECompare -v .\LowerEnclosureEquations.txt
node SWECompare -v .\PowerCableEquations.txt 
node SWECompare -v .\BallJointEquations.txt
node SWECompare -v .\BuildPlateZEndStopHolderEquations.txt
node SWECompare -v .\BLTouchProbeMountEquations.txt
node SWECompare -v .\InductiveProbeMountEquations.txt
