node SWECompare -v .\BackLeftVerticalSupportEquations.txt .\equations.txt
node SWECompare -v .\BackRightVerticalSupportEquations.txt .\equations.txt
node SWECompare -v .\BedBLEquations.txt .\equations.txt
node SWECompare -v .\BedBREquations.txt .\equations.txt
node SWECompare -v .\BedCEquations.txt .\equations.txt
node SWECompare -v .\BedTLEquations.txt .\equations.txt
node SWECompare -v .\BedTREquations.txt .\equations.txt
node SWECompare -v .\LeftBeltTensionerEquations.txt .\equations.txt
node SWECompare -v .\RightBeltTensionerEquations.txt .\equations.txt
node SWECompare -v .\BuildPlateEquations.txt .\equations.txt
node SWECompare -v .\FrontLeftVerticalSupportEquations.txt .\equations.txt
node SWECompare -v .\FrontRightVerticalSupportEquations.txt .\equations.txt
node SWECompare -v .\LeftGantryBlockEquations.txt .\equations.txt
node SWECompare -v .\LinearGuideBlockEquations.txt .\equations.txt
node SWECompare -v .\LinearRailClampEquations.txt .\equations.txt
node SWECompare -v .\LowerBackRailEquations.txt .\equations.txt
node SWECompare -v .\LowerFrontRailEquations.txt .\equations.txt
node SWECompare -v .\LowerCornerBlockEquations.txt .\equations.txt
node SWECompare -v .\LowerLeftRailEquations.txt .\equations.txt
node SWECompare -v .\LowerRightRailEquations.txt .\equations.txt
node SWECompare -v .\MGN12H-450Equations.txt .\equations.txt
node SWECompare -v .\MidBackRailEquations.txt .\equations.txt
node SWECompare -v .\MidLeftRailEquations.txt .\equations.txt
node SWECompare -v .\MidRightRailEquations.txt .\equations.txt
node SWECompare -v .\RightGantryBlockEquations.txt .\equations.txt
node SWECompare -v .\TopBackRailEquations.txt .\equations.txt
node SWECompare -v .\TopCornerBlockEquations.txt .\equations.txt
node SWECompare -v .\TopFrontRailEquations.txt .\equations.txt
node SWECompare -v .\TopLeftRailEquations.txt .\equations.txt
node SWECompare -v .\TopRightRailEquations.txt .\equations.txt
node SWECompare -v .\CarrierEquations.txt .\equations.txt
node SWECompare -v .\RodStabilizerEquations.txt .\equations.txt
node SWECompare -v .\VerticalSupportYardStickEquations.txt .\equations.txt
node SWECompare -v .\BedToBuildPlateStandoffEquations.txt .\equations.txt
