node SWECompare -v .\BackLeftVerticalSupportEquations.txt .\equations.txt
node SWECompare -v .\BackRightVerticalSupportEquations.txt .\equations.txt
node SWECompare -v .\BedBLEquations.txt .\equations.txt
node SWECompare -v .\BedFLEquations.txt .\equations.txt
node SWECompare -v .\BedCEquations.txt .\equations.txt
node SWECompare -v .\BedBREquations.txt .\equations.txt
node SWECompare -v .\BedFREquations.txt .\equations.txt
node SWECompare -v .\LeftBeltTensionerEquations.txt .\equations.txt
node SWECompare -v .\RightBeltTensionerEquations.txt .\equations.txt
node SWECompare -v .\BuildPlateEquations.txt .\equations.txt
node SWECompare -v .\FrontLeftVerticalSupportEquations.txt .\equations.txt
node SWECompare -v .\FrontRightVerticalSupportEquations.txt .\equations.txt
node SWECompare -v .\LeftGantryBlockEquations.txt .\equations.txt
node SWECompare -v .\LinearGuideBlockEquations.txt .\equations.txt
node SWECompare -v .\LeftXAxisLinearRailSupportEquations.txt .\equations.txt
node SWECompare -v .\RightXAxisLinearRailSupportEquations.txt .\equations.txt
node SWECompare -v .\XAxisLinearRailConnectingPlateEquations.txt .\equations.txt
node SWECompare -v .\LowerBackRailEquations.txt .\equations.txt
node SWECompare -v .\LowerFrontRailEquations.txt .\equations.txt
node SWECompare -v .\LowerLeftRailEquations.txt .\equations.txt
node SWECompare -v .\LowerRightRailEquations.txt .\equations.txt
node SWECompare -v .\MGN12H-450Equations.txt .\equations.txt
node SWECompare -v .\MidBackRailEquations.txt .\equations.txt
node SWECompare -v .\MidLeftRailEquations.txt .\equations.txt
node SWECompare -v .\MidRightRailEquations.txt .\equations.txt
node SWECompare -v .\RightGantryBlockEquations.txt .\equations.txt
node SWECompare -v .\UpperBackRailEquations.txt .\equations.txt
node SWECompare -v .\UpperFrontRailEquations.txt .\equations.txt
node SWECompare -v .\UpperLeftRailEquations.txt .\equations.txt
node SWECompare -v .\UpperRightRailEquations.txt .\equations.txt
node SWECompare -v .\CarrierEquations.txt .\equations.txt
node SWECompare -v .\RodStabilizerEquations.txt .\equations.txt
node SWECompare -v .\VerticalSupportYardStickEquations.txt .\equations.txt
node SWECompare -v .\BedToBuildPlateStandoffEquations.txt .\equations.txt
node SWECompare -v .\LowerEnclosureEquations.txt .\equations.txt
