"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"VSHeight"= 1.25in'Spec
"VSLength"= 450mm
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"VSBottomSideRailHoleY1FromBottomOfLowerRail"= "V1 BottomOfLowerRail" + "HoleOffsetFromSide"'Equals 81.1125
"VSSideRailHoleX1FromSide"= "HoleOffsetFromSide" + "RailThickness"
"FasteningHoleDiameter"= .125in
"VSBottomSideRailHoleY2FromY1"= "LowerRailHeight" - "HoleOffsetFromSide" - "HoleOffsetFromEdge"'Equals 6.35
"VSTopSideRailHoleY1FromEdge"= "HoleOffsetFromEdge" + "RailThickness"
"D4@RightSideHoles-Sketch3" = "FasteningHoleDiameter"
"D1@RightSideHoles-Sketch3" = "VSBottomSideRailHoleY1FromBottomOfLowerRail"
"D2@RightSideHoles-Sketch3" = "VSSideRailHoleX1FromSide"
"D1@Boss-Extrude1"="VSLength"
"D4@FrontSideHoles-Sketch4" = "FasteningHoleDiameter"
"D6@FrontSideHoles-Sketch4" = "VSTopSideRailHoleY1FromEdge"
"VSMidSideRailHoleY1FromV8TopOfMidSideRail"= "V8 ToTopOfMidSideRail" - "HoleOffsetFromEdge"'Equals 332.37764
"LowerRailHeight"= 1.00in
"D2@Sketch2"="VSWidth"
"D1@Sketch2"="VSHeight"
"TopRailHeight"= 1.25in
"MidLeftOrRightSideRailHeight"= 2.0in
"D12@RightSideHoles-Sketch3"="HoleOffsetFromEdge"
"VSMidSideRailHoleY2FromY1"= "MidLeftOrRightSideRailHeight" - "HoleOffsetFromEdge" * 2'Equals 34.925
"D7@RightSideHoles-Sketch3"="VSMidSideRailHoleY2FromY1"
"VSTopSideRailHoleY2FromY1"= "TopRailHeight" - "VSTopSideRailHoleY1FromEdge" - "HoleOffsetFromEdge"'Equals 12.7
"D7@FrontSideHoles-Sketch4"="VSTopSideRailHoleY2FromY1"
"VSSideRailHoleX2FromX1"= "VSWidth" - "VSSideRailHoleX1FromSide" - "HoleOffsetFromEdge"
"D3@RightSideHoles-Sketch3"="VSSideRailHoleX2FromX1"
"1mmSpacer"= 1mm
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"BeltTensionerInnerHeight"= "20TGT2PulleyWidth" * 2 + "1mmSpacer" * 3
"BeltTensionerHeight"= 60mm
"D9@FrontSideHoles-Sketch4"="VSBeltTensionerHoleY2FromY1"
"VSBeltTensionerHoleY1FromBottomAlignedWithYAxisGantryBlockMiddle"= "V6 ToMiddleOfYAxisGantryBlock" - "MidLeftOrRightSideRailHeight" / 2 + "BeltTensionerMountingHoleOffsetFromTopOrBottom"
"VSBeltTensionerHoleY2FromY1"= "BeltTensionerHeight" - "BeltTensionerMountingHoleOffsetFromTopOrBottom" * 2
"V1 BottomOfLowerRail"= "LegHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"ZAxisLeadScrewLength"= 200mm
"LM8UUHeight"= 24mm'Spec
"V2 ToBedAtTopOfZAxis"= "V1 BottomOfLowerRail" - "LowerEnclosureThickness" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2
"HotEndToTopOfXAxisGB"= 63.315144mm'Measured from the100.Should be 63.315144
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"
"LinearRailWidth"= 12mm'Spec
"V6 ToMiddleOfYAxisGantryBlock"= "V5 ToBottomOfXAxisLinearRail" - "GABHeight" / 2'Equals 325.31514
"GABUpperHeight"= 6mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"D10@RightSideHoles-Sketch3"="VSMidSideRailHoleY1FromV8TopOfMidSideRail"
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"D8@FrontSideHoles-Sketch4"="VSBeltTensionerHoleY1FromBottomAlignedWithYAxisGantryBlockMiddle"
"V8 ToTopOfMidSideRail"= "V6 ToMiddleOfYAxisGantryBlock" + "MidSideRailVerticalOffset"
"BeltTensionerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge"
"VSBeltTensionerXMountingHoleOffsetFromSide"= "BeltTensionerMountingHoleOffsetFromEdge" + "RailThickness" * 2
"D10@FrontSideHoles-Sketch4"="VSBeltTensionerXMountingHoleOffsetFromSide"
"VSEnclosureOffsets"= ( "VSLength" - "LegHeight" ) / 4
"D11@RightSideHoles-Sketch3"="LegHeight" + "VSEnclosureOffsets"
"D13@RightSideHoles-Sketch3"="VSEnclosureOffsets"
"D12@FrontSideHoles-Sketch4"= "LegHeight" + "VSEnclosureOffsets"
"D13@FrontSideHoles-Sketch4"="VSEnclosureOffsets"
"D15@FrontSideHoles-Sketch4"="HoleOffsetFromEdge"
"D2@FrontSideHoles-Sketch4"="VSSideRailHoleX1FromSide"
"D5@FrontSideHoles-Sketch4"="VSBottomSideRailHoleY2FromY1"
"D3@FrontSideHoles-Sketch4"="VSBottomSideRailHoleY1FromBottomOfLowerRail"
"D5@RightSideHoles-Sketch3"="VSBottomSideRailHoleY2FromY1"
"D6@RightSideHoles-Sketch3"="VSTopSideRailHoleY2FromY1"
"D8@RightSideHoles-Sketch3"="VSTopSideRailHoleY1FromEdge"
"BeltTensionerMountingHoleDiameter"= 4.0mm
"D16@FrontSideHoles-Sketch4"="BeltTensionerMountingHoleDiameter"
"LowerEnclosureThickness"= 5mm
"GABLowerHeight"= 3mm
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"D9@RightSideHoles-Sketch3"="VSEnclosureOffsets"
"BeltTensionerMountingHoleOffsetFromTopOrBottom"= ( "BeltTensionerHeight" - "BeltTensionerInnerHeight" ) / 4
"MidSideRailVerticalOffset"= "LinearRailWidth" + 3mm'Allows space for RodStabilizer to attach to bottom of MidSideRail
