"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"VSHeight"= 1.25in'Spec
"VSLength"= 20.0in
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"VSBottomSideRailHoleYFromBottomOfLowerRailYSValue"= 95.4mm
"VSTopSideRailHoleYFromEdge"= "TopRailHeight" / 2
"D1@RightSideHoles-Sketch3" = "VSBottomSideRailHoleYFromBottomOfLowerRailYSValue"
"D2@RightSideHoles-Sketch3"="FrameFastenerHoleOffsetFromSide"
"D1@Boss-Extrude1"="VSLength"
"D4@FrontSideHoles-Sketch4"="FrameFastenerHoleDiameter"
"D6@FrontSideHoles-Sketch4" = "VSTopSideRailHoleYFromEdge"
"VSMidSideRailHoleYFromV8TopOfMidSideRailYSValue"= 351.58487mm
"D2@Sketch2"="VSWidth"
"D1@Sketch2"="VSHeight"
"TopRailHeight"= 1.25in
"D9@FrontSideHoles-Sketch4"="VSBeltTensionerHoleY2FromY1YSValue"
"VSBeltTensionerHoleY1ToAlignedWithYAxisGantryBlockUpperPulleyYSValue"= 406.13487mm
"VSBeltTensionerHoleY2FromY1YSValue"= 40.2mm
"D10@RightSideHoles-Sketch3"="VSMidSideRailHoleYFromV8TopOfMidSideRailYSValue"
"BeltTensionerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge" + "RailThickness" * 2
"VSBeltTensionerXMountingHoleOffsetFromSide"= "BeltTensionerMountingHoleOffsetFromEdge" + "RailThickness"
"D10@FrontSideHoles-Sketch4"="VSBeltTensionerXMountingHoleOffsetFromSide"
"D3@FrontSideHoles-Sketch4"="VSBottomSideRailHoleYFromBottomOfLowerRailYSValue"
"D8@RightSideHoles-Sketch3"="VSTopSideRailHoleYFromEdge"
"BeltTensionerMountingHoleDiameter"= 4.0mm
"D16@FrontSideHoles-Sketch4"="BeltTensionerMountingHoleDiameter"
"D8@FrontSideHoles-Sketch4"="VSBeltTensionerHoleY1ToAlignedWithYAxisGantryBlockUpperPulleyYSValue"
"FrameFastenerHoleDiameter"= 8mm
"FrameFastenerHoleOffsetFromSide"= "VSWidth" / 2 + "GapBetweenVerticalSupportsAndRails"
"D3@RightSideHoles-Sketch3"="FrameFastenerHoleDiameter"
"D2@FrontSideHoles-Sketch4"="FrameFastenerHoleOffsetFromSide"
"D5@Sketch2"="RailThickness"
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
