"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"VSHeight"= 1.25in'Spec
"VSLength"= 450mm
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"VSBottomSideRailHoleY1FromBottomOfLowerRail"= "V1 BottomOfLowerRail" + "HoleOffsetFromSide"'Equals 70.1125
"VSSideRailHoleX1FromSide"= "HoleOffsetFromSide" + "RailThickness"
"FasteningHoleDiameter"= .125in
"VSBottomSideRailHoleY2FromY1"= "LowerRailHeight" - "HoleOffsetFromSide" - "HoleOffsetFromEdge"'Equals 6.35
"VSTopSideRailHoleY1FromEdge"= "HoleOffsetFromEdge" + "RailThickness"
"D4@RightSideHoles-Sketch3" = "FasteningHoleDiameter"
"D1@RightSideHoles-Sketch3" = "VSBottomSideRailHoleY1FromBottomOfLowerRail"
"D2@RightSideHoles-Sketch3" = "VSSideRailHoleX1FromSide"
"D1@Boss-Extrude1"="VSLength"
"D4@FrontSideHoles-Sketch4" = "FasteningHoleDiameter"
"D6@FrontSideHoles-Sketch4" = "VSTopSideRailHoleY1FromEdge"
"VSMidSideRailHoleY1FromV8TopOfMidSideRail"= "V8 ToTopOfMidSideRail" - "HoleOffsetFromEdge"'Equals 308.2875
"LowerRailHeight"= 1.00in
"D2@Sketch2"="VSWidth"
"D1@Sketch2"="VSHeight"
"TopRailHeight"= 1.25in
"MidSideRailHeight"= 1.25in
"D12@RightSideHoles-Sketch3"="HoleOffsetFromEdge"
"VSMidSideRailHoleY2FromY1"= "MidSideRailHeight" - "HoleOffsetFromSide" - "HoleOffsetFromEdge"'Equals 12.7
"D7@RightSideHoles-Sketch3"="VSMidSideRailHoleY2FromY1"
"VSTopSideRailHoleY2FromY1"= "TopRailHeight" - "VSTopSideRailHoleY1FromEdge" - "HoleOffsetFromEdge"'Equals 12.7
"D7@FrontSideHoles-Sketch4"="VSTopSideRailHoleY2FromY1"
"VSSideRailHoleX2FromX1"= "VSWidth" - "VSSideRailHoleX1FromSide" - "HoleOffsetFromEdge"
"D3@RightSideHoles-Sketch3"="VSSideRailHoleX2FromX1"
"1mmSpacer"= 1mm
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"BeltTensionerUpperLowerWallThickness"= 7mm
"BeltTensionerInnerHeight"= "20TGT2PulleyWidth" * 2 + "1mmSpacer" * 3
"BeltTensionerHeight"= "BeltTensionerInnerHeight" + "BeltTensionerUpperLowerWallThickness" * 2
"D9@FrontSideHoles-Sketch4"="VSBeltTensionerHoleY2FromY1"
"VSBeltTensionerHoleY1FromBottom"= "V9 FromBottomGantryPulleyToBottomOfBeltTensioner" + "HoleOffsetFromEdge"
"VSBeltTensionerHoleY2FromY1"= "BeltTensionerHeight" - "HoleOffsetFromEdge" * 2
"V1 BottomOfLowerRail"= "LegHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"ZAxisLeadScrewLength"= 200mm
"LM8UUHeight"= 24mm'Spec
"V2 ToBedAtTopOfZAxis" = "V1 BottomOfLowerRail" - "LowerEnclosureThickness" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2
"HotEndToTopOfXAxisGB"= 63.315144mm'Measured from the100.Should be 63.315144
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"
"LinearRailWidth"= 12mm'Spec
"V6 ToBottomOfGantryPulley"= "V5 ToBottomOfXAxisLinearRail" - "DistanceFromGABTopToLowerPulley"
"GABUpperHeight"= 6mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"GABRiserBossOffset"= 0.8mm'Aligns Pulleys
"DistanceFromGABTopToLowerPulley"= "GABUpperHeight" + "GABMidWallHeight" - "GABMidShortRiserHeight" + "GABRiserBossOffset" / 2
"V7 ToTopOfMidBackRail"= "V6 ToBottomOfGantryPulley" + "StepperShaftLength"
"D10@RightSideHoles-Sketch3"="VSMidSideRailHoleY1FromV8TopOfMidSideRail"
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V4 ToTopOfBuildPlate/HotEndTip" = "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"D8@FrontSideHoles-Sketch4"="VSBeltTensionerHoleY1FromBottom"
"V8 ToTopOfMidSideRail"= "V7 ToTopOfMidBackRail" - "RailThickness"
"V9 FromBottomGantryPulleyToBottomOfBeltTensioner"= "V6 ToBottomOfGantryPulley" - "BeltTensionerUpperLowerWallThickness" - "1mmSpacer"
"BeltTensionerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge"
"VSBeltTensionerXMountingHoleOffsetFromSide"= "BeltTensionerMountingHoleOffsetFromEdge" + "RailThickness" * 2
"D10@FrontSideHoles-Sketch4"="VSBeltTensionerXMountingHoleOffsetFromSide"
"VSEnclosureOffsets"= ( "VSLength" - "LegHeight" ) / 4
"D11@RightSideHoles-Sketch3"="LegHeight" + "VSEnclosureOffsets"
"D13@RightSideHoles-Sketch3"="VSEnclosureOffsets"
"D14@RightSideHoles-Sketch3"="VSEnclosureOffsets"
"D12@FrontSideHoles-Sketch4"= "LegHeight" + "VSEnclosureOffsets"
"D13@FrontSideHoles-Sketch4"="VSEnclosureOffsets"
"D14@FrontSideHoles-Sketch4"="VSEnclosureOffsets"
"D15@FrontSideHoles-Sketch4"="HoleOffsetFromEdge"
"D2@FrontSideHoles-Sketch4"="VSSideRailHoleX1FromSide"
"D5@FrontSideHoles-Sketch4"="VSBottomSideRailHoleY2FromY1"
"D3@FrontSideHoles-Sketch4"="VSBottomSideRailHoleY1FromBottomOfLowerRail"
"D5@RightSideHoles-Sketch3"="VSBottomSideRailHoleY2FromY1"
"D6@RightSideHoles-Sketch3"="VSTopSideRailHoleY2FromY1"
"D8@RightSideHoles-Sketch3"="VSTopSideRailHoleY1FromEdge"
"BeltTensionerMountingHoleDiameter"= 4.0mm
"D16@FrontSideHoles-Sketch4"="BeltTensionerMountingHoleDiameter"
"LowerEnclosureThickness"= 5mm
