"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"VSHeight"= 1.25in'Spec
"VSLength"= 20.0in
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"VSBottomSideRailHoleYFromBottomOfLowerRailYSValue"= 95.4mm
"VSTopSideRailHoleYFromEdge"= "TopRailHeight" / 2
"D4@FrontSideHoles-Sketch3"="FrameFastenerHoleDiameter"
"D1@Boss-Extrude1"="VSLength"
"D8@FrontSideHoles-Sketch3" = "VSTopSideRailHoleYFromEdge"
"D6@LeftSideHoles-Sketch4" = "VSTopSideRailHoleYFromEdge"
"VSMidSideRailHoleYFromV8TopOfMidSideRailYSValue"= 351.58487mm
"D1@Sketch2"="VSHeight"
"D2@Sketch2"="VSWidth"
"TopRailHeight"= 1.25in
"D11@FrontSideHoles-Sketch3"="VSBeltTensionerHoleY2FromY1YSValue"
"VSBeltTensionerHoleY1ToAlignWithYAxisGantryBlockUpperPulleyYSValue"= 406.13487mm
"D8@LeftSideHoles-Sketch4"= "VSMidSideRailHoleYFromV8TopOfMidSideRailYSValue"
"D14@FrontSideHoles-Sketch3"="VSBottomSideRailHoleYFromBottomOfLowerRailYSValue"
"BeltTensionerMountingHoleDiameter"= 4.0mm
"D15@FrontSideHoles-Sketch3"="BeltTensionerMountingHoleDiameter"
"VSBeltTensionerXMountingHoleOffsetFromSide"= "BeltTensionerMountingHoleOffsetFromEdge" + "RailThickness"
"BeltTensionerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge" + "RailThickness" * 2
"D16@FrontSideHoles-Sketch3"="VSBeltTensionerXMountingHoleOffsetFromSide"
"D9@FrontSideHoles-Sketch3"="VSBeltTensionerHoleY1ToAlignWithYAxisGantryBlockUpperPulleyYSValue"
"FrameFastenerHoleDiameter"= 8mm
"FrameFastenerHoleOffsetFromSide"= "VSWidth" / 2 + "GapBetweenVerticalSupportsAndRails"
"D2@FrontSideHoles-Sketch3"="FrameFastenerHoleOffsetFromSide"
"D2@LeftSideHoles-Sketch4"="FrameFastenerHoleOffsetFromSide"
"D3@LeftSideHoles-Sketch4"="VSBottomSideRailHoleYFromBottomOfLowerRailYSValue"
"D1@LeftSideHoles-Sketch4"="FrameFastenerHoleDiameter"
"VSBeltTensionerHoleY2FromY1YSValue"= 40.2mm
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
