"ProbeMountHeight"= + "ProbeMountUpperHeight" + "ProbeMountingHoleSlotLength" + "ProbeMountMiddleHeight" + "ProbeMountLowerHeight"
"D1@ProfileSketch1"="ProbeMountHeight" 
"D1@Boss-Extrude1"= "ProbeBodyWidth"
"ProbeBodyWidth"= "InductiveProbeWidth" + 8.3mm
"ProbeMountUpperHeight"= "M3ScrewDiameter" * 2
"D4@ProfileSketch1"="ProbeMountDepth"
"M3ScrewButtonHeadHeight"= 2.4mm
"D1@ProbeSlidingMountSketch4" = "M3ScrewDiameter"
"D2@ProbeSlidingMountSketch4"="ProbeMountingHoleSlotLength"
"M3ScrewDiameter"= 3.1mm
"ProbeMountDepth" = "M3HeatInsertHoleDepth" + 1mm
"M3ScrewButtonHeadDiameter"= 5.9mm
"D1@ProbeSlidingMountChannelSketch5"="M3ScrewButtonHeadDiameter"+ .5mm
"D7@ProbeSlidingMountSketch4"="ProbeMountMiddleHeight"
"InductiveProbeWidth"= 17.7mm
"D5@ProbeSlidingMountSketch4"=("ProbeBodyWidth" - "ProbeDistanceBetweenMountingHoles")/2
"ProbeDistanceBetweenMountingHoles"= 11.5mm
"D4@ProbeSlidingMountSketch4"="ProbeDistanceBetweenMountingHoles"
"M3HeatInsertHoleDepth"= 4mm
"InductiveProbeDistanceBetweenItsMountingHoles"= 10mm
"D12@ProbeSlidingMountSketch4"=("ProbeBodyWidth" - "InductiveProbeDistanceBetweenItsMountingHoles")/2
"D11@ProbeSlidingMountSketch4"="InductiveProbeDistanceBetweenItsMountingHoles"
"M3HeatInsertHoleDiameter"= 4mm + .1mm'Add .1mm for printing
"ProbeMountingHoleSlotLength"= 9mm
"D3@ProbeSlidingMountSketch4"="M3ScrewDiameter" * 2
"InductiveProbeTopHeight"= 12mm
"ProbeMountMiddleHeight"= "InductiveProbeTopHeight" + "M3ScrewDiameter" * 2 + .9mm
"ProbeMountLowerHeight"= "InductiveProbeTopHeight"
"D6@ProbeSlidingMountSketch4"="M3HeatInsertHoleDiameter"
"D1@ProbeSlidingMountChanelCut-Extrude4"="M3ScrewButtonHeadHeight"
