"ProbeMountHeight"= "ProbeMountDepth" + "ProbeMountUpperHeight"
"D1@ProfileSketch1"="ProbeMountHeight" + 30mm
"D1@Boss-Extrude1"= "ProbeBodyWidth"
"ProbeBodyWidth"= 26mm
"ProbeMountUpperHeight"= "M3ScrewButtonHeadHeight" * 2 + "M3ScrewDiameter" * 5 + "M3ScrewButtonHeadHeight" * 2
"D4@ProfileSketch1"="ProbeMountDepth"+1mm
"M3ScrewButtonHeadHeight"= 2.4mm
"D1@ProbeSlidingMountSketch4" = "M3ScrewDiameter"
"D2@ProbeSlidingMountSketch4" = 3mm * 3
"M3ScrewDiameter"= 3.1mm
"ProbeMountDepth"= 3mm
"M3ScrewButtonHeadDiameter"= 5.9mm
"D1@ProbeSlidingMountChannelSketch5"="M3ScrewButtonHeadDiameter"+ .5mm
"D7@ProbeSlidingMountSketch4"=13.5+10.9
"InductiveProbeWidth"= 17.7mm
"D1@InductiveProbeHolderSketch1" = "InductiveProbeWidth"
"ProbeMountingHoleDistance"=11.6
"D5@ProbeSlidingMountSketch4"=("ProbeBodyWidth" - "ProbeMountingHoleDistance")/2
