"BeltTensionerWidth"= "MidRailToAlignWithGantryBlock" + "BeltTensionerInnerWidth" / 2 + "RailThickness"
"BeltTensionerHeight"= 60mm
"BeltTensionerInnerWidth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"BeltTensionerBackWallThickness"= 4mm
"RailThickness"= .125in'Spec
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"MidRailToAlignWithGantryBlock"= "Nema17MountStepperHoleDistanceFromBack"'All outside cogs must align
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerMountingHoleDiameter"= 4.0mm
"BeltTensionerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge" + "RailThickness" * 2
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"1mmSpacer"= 1mm
"SteelShaft5mmHoleDiameter"= 5mm
"BeltTensionerMountingHoleOuterBoreDepth"= 2mm
"BeltTensionerMountingHoleOuterBoreDiameter"= 7.75mm
"7mmx1mmSpacerDiameter"= 7mm + .1mm'Add .1mm for printing
"7mmx1mmSpacerHeight"= 1mm
"D1@MainBlock" = "BeltTensionerWidth"
"D4@MainBlock" = "BeltTensionerMountingHoleDiameter"
"D5@MainBlock" = "BeltTensionerInnerWidth"
"D6@MainBlock" = "BeltTensionerMountingHoleOffsetFromEdge"
"D7@MainBlock"="BeltTensionerMountingHoleOffsetFromTopOrBottom"
"D1@MainBlockBoss-Extrude1" = "BeltTensionerDepth"
"D1@TopHoleCut-Sketch2" = "BeltTensionerDepth" / 2
"D3@TopHoleCut-Sketch2" = "SteelShaft5mmHoleDiameter"
"D1@TopSpacerSketch4" = "7mmx1mmSpacerDiameter"
"D1@TopSpacerBoss-Extrude2" = "7mmx1mmSpacerHeight"
"D1@LowerSpacerBoss-Extrude3" = "7mmx1mmSpacerHeight"
"D1@MountHoleBoreSketch1" = "BeltTensionerMountingHoleOuterBoreDiameter"
"D1@MountHoleBoreCut-Extrude1" = "BeltTensionerMountingHoleOuterBoreDepth"
"SteelPushPinHoleDiameter"= "SteelShaft5mmHoleDiameter" - 1mm
"D1@PushPinHoleSketch1" = "SteelPushPinHoleDiameter"
"D2@TopHoleCut-Sketch2"="BeltTensionerWidth" - "MidRailToAlignWithGantryBlock" - "RailThickness"
"BeltTensionerMountingHoleOffsetFromTopOrBottom"= ( "BeltTensionerHeight" - "BeltTensionerInnerHeight" ) / 4
"SteelShaftLength"= 30mm
"D1@TopHoleCut-Extrude1"="BeltTensionerSteelShaftHoleDepthFromTop"
"D2@MidRailInsetSketch1"="DistanceAboveMidSideRailToTopOfBeltTensioner"
"DistanceAboveMidSideRailToTopOfBeltTensioner"= "VSBeltTensionerY1ToAlignWithYAxisGantryUpperPulleyYSValue" + "BeltTensionerMountingHoleOffsetFromTopOrBottom" - "V8 ToTopOfMidSideRailYSValue"'Equals 39.05017
"D3@MainBlock"="BeltTensionerInnerHeight"
"D9@MainBlock"="BeltTensionerTopHeight"
"V8 ToTopOfMidSideRailYSValue"= 376.9847mm
"D1@VerticalSupportFillet1"="RailThickness"
"D1@MidRailInsetSketch1"="HoleOffsetFromEdge"
"BeltTensionerDistanceBetweenMountingHoles"= "BeltTensionerHeight" - "BeltTensionerMountingHoleOffsetFromTopOrBottom" * 2'Equals 40.2
"D2@MainBlock"="BeltTensionerHeight"
"D8@MainBlock" = "BeltTensionerDistanceBetweenMountingHoles"
"VSBeltTensionerY1ToAlignWithYAxisGantryUpperPulleyYSValue"= 406.13487mm
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"BeltTensionerInnerHeight"= "20TGT2PulleyWidth" * 2 + "1mmSpacer" * 3
"BeltTensionerTopHeight"= ( "BeltTensionerHeight" - "BeltTensionerInnerHeight" ) / 2'Equals 19.8
"BeltTensionerSteelShaftHoleDepthFromTop"= ( "SteelShaftLength" - "BeltTensionerInnerHeight" ) / 2 + ( "BeltTensionerHeight" - "BeltTensionerInnerHeight" ) / 2 + "BeltTensionerInnerHeight"'Equals 45
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"'Equals 19.4
"Nema17MountStepperHoleDistanceFromBack"= 30mm'Spec
