"GABDepth"= "GABDistanceFromBackToFirstPulley" + "GABPulleyDDistanceBetween" + "GABDistanceFromPulleyToFront"
"GABWidth"= "StandardWallThickness" + "GABDistanceFromLSideToPulley" + "GABPulleyWDistanceBetween" + "GABDistanceFromPulleyToRSide"
"GABLowerHeight"= 4mm
"GABUpperHeight"= 4mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"StandardWallThickness"= 3mm
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"LinearGBMountHolesXDistance"= 20mm'Spec
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"GBMountingHoleDiameter"= 2mm
"GABMidLongRiserHeight"= "GABMidWallHeight" - "GABMidShortRiserHeight" - "20TGT2PulleyWidth"'Equals 14
"GABLRClampHoleOffsetFromSide"= 5mm
"GABDistanceFromBackToFirstPulley"= 13.5mm
"GABPulleyDDistanceBetween"= 12.5mm'From the100
"GABPulleyWDistanceBetween"= 14.5mm'From the100
"GABDistanceFromPulleyToFront"= 8mm
"GABDistanceFromLSideToPulley"= 9.5mm + "StandardWallThickness"
"GABDistanceFromPulleyToRSide"= 7.5mm
"GABDistanceToFrontClampHoles"= 8.5mm
"SteelShaft5mmHoleDiameter"= 5mm
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"7mmx1mmSpacerDiameter"= 7mm
"7mmx1mmSpacerHeight"= 1mm
"GABRiserBossOffset" = 0.4mm'Aligns Pulleys inside edges to be 2.5mm (.5mm apart top to bottom)
"D1@Top-Sketch1" = "GABDistanceFromBackToFirstPulley"
"D2@Top-Sketch1" = "GABPulleyDDistanceBetween"
"D3@Top-Sketch1" = "SteelShaft5mmHoleDiameter"
"D4@Top-Sketch1" = "GABPulleyDDistanceBetween"
"D6@Top-Sketch1" = "GABDistanceFromPulleyToFront"
"D8@Top-Sketch1" = "GABDistanceFromLSideToPulley"
"D9@Top-Sketch1" = "GABLRClampHoleOffsetFromSide"
"D10@Top-Sketch1" = "GABLRClampHoleOffsetFromSide"
"D11@Top-Sketch1" = "GABWidth"
"D1@Boss-Extrude4"="GABUpperHeight"
"D1@TopRightRiserBoss-Extrude5" = "GABMidLongRiserHeight" + "GABRiserBossOffset"
"D1@TopLeftBoss-Extrude6" = "GABMidShortRiserHeight" - "GABRiserBossOffset"
"D1@MidWall" = "StandardWallThickness"
"D1@MidWallBoss-Extrude7" = "GABMidWallHeight"
"D1@BottomBoss-Extrude8" = "GABLowerHeight"
"D1@LowerLeftBoss-Extrude9" = "GABMidLongRiserHeight" + "GABRiserBossOffset"
"D1@LowerRightBoss-Extrude10" = "GABMidShortRiserHeight" - "GABRiserBossOffset"
"D1@LinearRailMountingHoles-Sketch10" =  ( "GABHeight" - "LinearGBMountHolesXDistance" )  / 2
"D2@LinearRailMountingHoles-Sketch10"="LinearGBMountHolesYDistance"
"D3@LinearRailMountingHoles-Sketch10" = "LinearGBMountHolesXDistance"
"D4@LinearRailMountingHoles-Sketch10" =  ( "GABWidth" - "LinearGBMountHolesXDistance" )  / 2
"D7@LinearRailMountingHoles-Sketch10" = "GBMountingHoleDiameter"
"D1@LinearRailMountingHolesCut-Extrude1" = "StandardWallThickness"
"D1@TopRightInset-Cut-Extrude1" = "7mmx1mmSpacerHeight"
"D1@TopLeftInset-Cut-Extrude2" = "7mmx1mmSpacerHeight"
"D1@LowerRightInsetCut-Extrude4" = "7mmx1mmSpacerHeight"
"D1@TopRightRiser"="7mmx1mmSpacerDiameter"
"D7@Top-Sketch1"="GABDepth" - "GABDistanceToFrontClampHoles"
"LinearGBMountHolesYDistance"= 20mm'Spec
"D1@PushPinHoleSketch1" = "StealPinPushHoleDiameter"
"StealPinPushHoleDiameter"= 2mm
"M3HeatInsertHoleDiameter"= 4mm'Spec
"D5@Top-Sketch1"="M3HeatInsertHoleDiameter"
