"BeltTensionerWidth"= "MidRailToAlignWithGantryBlock" + "BeltTensionerInnerWidth" / 2 + "RailThickness"
"BeltTensionerHeight"= 60mm
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"BeltTensionerInnerWidth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"BeltTensionerInnerHeight"= "20TGT2PulleyWidth" * 2 + "1mmSpacer" * 3
"BeltTensionerBackWallThickness"= 4mm
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"RailThickness"= .125in'Spec
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"LinearGBWithRailDepth"= 12.75mm'Spec
"GABDistanceFromBackToFirstPulley"= 13.5mm
"MidRailToAlignWithGantryBlock"= "LinearGBWithRailDepth" + "GABDistanceFromBackToFirstPulley"'All outside cogs must align
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerMountingHoleDiameter"= 4.0mm
"BeltTensionerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge"
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"1mmSpacer"= 1mm
"SteelShaft5mmHoleDiameter"= 5mm
"BeltTensionerMountingHoleOuterBoreDepth"= 2mm
"BeltTensionerMountingHoleOuterBoreDiameter"= 7.75mm
"7mmx1mmSpacerDiameter"= 7mm
"7mmx1mmSpacerHeight"= 1mm
"D1@MainBlock" = "BeltTensionerWidth"
"D2@MainBlock" = "BeltTensionerHeight"
"D3@MainBlock" = "BeltTensionerInnerHeight"
"D4@MainBlock" = "BeltTensionerMountingHoleDiameter"
"D5@MainBlock" = "BeltTensionerInnerWidth"
"D6@MainBlock"="BeltTensionerMountingHoleOffsetFromEdge" + "RailThickness"
"D7@MainBlock"="BeltTensionerMountingHoleOffstFromTopOrBottom"
"D8@MainBlock"="BeltTensionerMountingHoleOffstFromTopOrBottom"
"D1@MainBlockBoss-Extrude1" = "BeltTensionerDepth"
"D1@TopHoleCut-Sketch2" = "BeltTensionerDepth" / 2
"D3@TopHoleCut-Sketch2" = "SteelShaft5mmHoleDiameter"
"D1@TopSpacerSketch4" = "7mmx1mmSpacerDiameter"
"D1@TopSpacerBoss-Extrude2" = "7mmx1mmSpacerHeight"
"D1@LowerSpacerBoss-Extrude3" = "7mmx1mmSpacerHeight"
"D1@MountHoleBoreSketch1" = "BeltTensionerMountingHoleOuterBoreDiameter"
"D1@MountHoleBoreCut-Extrude1" = "BeltTensionerMountingHoleOuterBoreDepth"
"SteelPinPushHoleDiameter"= 2mm
"D1@PushPinHoleSketch1" = "SteelPinPushHoleDiameter"
"D2@TopHoleCut-Sketch2"="BeltTensionerWidth" - "MidRailToAlignWithGantryBlock" - "RailThickness"
"BeltTensionerMountingHoleOffstFromTopOrBottom"= ( "BeltTensionerHeight" - "BeltTensionerInnerHeight" ) / 4
"BeltTensionerSteelShaftHoleDepthFromTop"= ( "SteelShaftLength" - "BeltTensionerInnerHeight" ) / 2 + ( "BeltTensionerHeight" - "BeltTensionerInnerHeight" ) / 2 + "BeltTensionerInnerHeight"'Equals 45
"SteelShaftLength"= 30mm
"D1@TopHoleCut-Extrude1"="BeltTensionerSteelShaftHoleDepthFromTop"
"D1@ScrewCollisionSketch1" = "BeltTensionerDepth" * .8
"MidLeftOrRightSideRailHeight"= 2.0in
"MidSideRailVerticalOffset"= "LinearRailWidth" + 3mm'Allows space for RodStabilizer to attach to bottom of MidSideRail
"LinearRailWidth"= 12mm'Spec
"D2@MidRailInsetSketch1"="DistanceAboveMidSideRailToTopOfBeltTensioner"
"DistanceAboveMidSideRailToTopOfBeltTensioner"= "MidSideRailVerticalOffset" + "BeltTensionerHeight" / 2 - "MidLeftOrRightSideRailHeight" / 2
