"BeltTensionerWidth"= "MidRailToAlignWithGantryBlock" + "BeltTensionerInnerWidth" / 2
"BeltTensionerHeight"= "BeltTensionerInnerHeight" + "BeltTensionerUpperLowerWallThickness" * 2
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"BeltTensionerUpperLowerWallThickness"= 7mm
"BeltTensionerInnerWidth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"BeltTensionerInnerHeight"= "20TGT2PulleyWidth" * 2 + "1mmSpacer" * 3
"BeltTensionerBackWallThickness"= 4mm
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"RailThickness"= .125in'Spec
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"LinearGBWithRailDepth"= 12.75mm'Spec
"GABDistanceFromBackToFirstPulley"= 13.5mm
"MidRailToAlignWithGantryBlock"= "LinearGBWithRailDepth" + "GABDistanceFromBackToFirstPulley"'All outside cogs must align
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerMountingHoleDiameter"= 4.0mm
"BeltTensionerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge"
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"1mmSpacer"= 1mm
"SteelShaft5mmHoleDiameter"= 5mm
"BeltTensionerMountingHoleOuterBoreDepth"= 2mm
"BeltTensionerMountingHoleOuterBoreDiameter"= 7.75mm
"7mmx1mmSpacerDiameter"= 7mm
"7mmx1mmSpacerHeight"= 1mm
"D1@MainBlock" = "BeltTensionerWidth"
"D2@MainBlock" = "BeltTensionerHeight"
"D3@MainBlock" = "BeltTensionerInnerHeight"
"D4@MainBlock" = "BeltTensionerMountingHoleDiameter"
"D5@MainBlock" = "BeltTensionerInnerWidth"
"D6@MainBlock"="BeltTensionerMountingHoleOffsetFromEdge"
"D7@MainBlock" = "HoleOffsetFromEdge"
"D8@MainBlock" = "HoleOffsetFromEdge"
"D1@MainBlockBoss-Extrude1" = "BeltTensionerDepth"
"D1@TopHoleCut-Sketch2" = "BeltTensionerDepth" / 2
"D2@TopHoleCut-Sketch2" = "MidRailToAlignWithGantryBlock"
"D3@TopHoleCut-Sketch2" = "SteelShaft5mmHoleDiameter"
"D1@TopSpacerSketch4" = "7mmx1mmSpacerDiameter"
"D1@TopSpacerBoss-Extrude2" = "7mmx1mmSpacerHeight"
"D1@LowerSpacerBoss-Extrude3" = "7mmx1mmSpacerHeight"
"D1@MountHoleBoreSketch1" = "BeltTensionerMountingHoleOuterBoreDiameter"
"D1@MountHoleBoreCut-Extrude1" = "BeltTensionerMountingHoleOuterBoreDepth"
"StealPinPushHoleDiameter"= 2mm
"D1@PushPinHoleSketch1" = "StealPinPushHoleDiameter"
