"GABWidth"= "GABDistanceFromBackToFirstPulley" + "GABPulleyWDistanceBetween" + "GABDistanceFromPulleyToOutside"'Equals 35.5
"GABLowerHeight"= 31.5mm
"GABUpperHeight"= 17mm'From the100
"GABMidWallHeight"= 19mm'From the100
"StandardWallThickness"= 3mm
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 0.8
"GABMidLongRiserHeight"= "GABMidWallHeight" - "GABMidShortRiserHeight" - "20TGT2PulleyWidth"'Equals 9.5
"GABDistanceFromBackToFirstPulley"= "StandardWallThickness" + 10.5mm
"GABPulleyDDistanceBetween"= 12.5mm'From the100
"GABPulleyWDistanceBetween"= "SteelShaft5mmHoleDiameter" + "RodShaft8mmDiameter" + 1mm'the100 has this as 12.5. Increase to 14 so XAxis rod fits between
"SteelShaft5mmHoleDiameter"= 5mm
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"7mmx1mmSpacerDiameter"= 7mm + .1mm'Add .1mm for printing
"7mmx1mmSpacerHeight"= 1mm
"GABRiserBossOffset"= 0.4mm'Aligns Pulleys inside edges to be 2.5mm (.5mm apart top to bottom)
"D2@Top-Sketch1" = "GABPulleyDDistanceBetween"
"D3@Top-Sketch1" = "SteelShaft5mmHoleDiameter" + .2mm
"D4@Top-Sketch1" = "GABPulleyWDistanceBetween"
"D1@Boss-Extrude4"="GABUpperHeight"
"D1@TopRightRiserBoss-Extrude5" = "GABMidLongRiserHeight" + "GABRiserBossOffset"
"D1@TopLeftBoss-Extrude6" = "GABMidShortRiserHeight" - "GABRiserBossOffset"
"D1@MidWall" = "StandardWallThickness"
"D1@MidWallBoss-Extrude7" = "GABMidWallHeight"
"D1@BottomBoss-Extrude8" = "GABLowerHeight"
"D1@LowerLeftRiserBoss-Extrude9" = "GABMidLongRiserHeight" + "GABRiserBossOffset"
"D1@LowerRightRightBoss-Extrude10" = "GABMidShortRiserHeight" - "GABRiserBossOffset"
"D1@TopRightInset-Cut-Extrude1" = "7mmx1mmSpacerHeight"
"D1@TopLeftInset-Cut-Extrude2" = "7mmx1mmSpacerHeight"
"D1@LowerRightInsetCut-Extrude4" = "7mmx1mmSpacerHeight"
"D1@TopRightRiser"="7mmx1mmSpacerDiameter"
"LM8UUDiameter"= 15mm
"D1@LM8UUHoleSketch1"="LM8UUDiameter" +.125mm
"LM8UUOffsetFromGABBack"= 11mm'From the100
"D2@LM8UUHoleSketch1"="LM8UUOffsetFromGABBack"
"RodShaft8mmDiameter"= 8mm
"D1@XAxisRodSketch2" = "RodShaft8mmDiameter" + .2mm
"GABDistanceBetweenXAxisRods"= 34.6mm'From the100
"D5@XAxisRodSketch2" = "GABDistanceBetweenXAxisRods"
"LM8UUOffsetFromBottomMidSection"= 21.5mm'From the100
"D3@LM8UUHoleSketch1"="LM8UUOffsetFromBottomMidSection"
"XAxisRodDistanceFromTopMidSection"= 7.75mm'From the100
"D4@XAxisRodSketch2"="XAxisRodDistanceFromTopMidSection"
"D1@SteelShaftPushPinHoleSketch4"="SteelPushPinHoleDiameter"
"D1@LM8UUM3FastenerSketch4"="LM8UUDiameter" /2 + "LM8UUFasteningHoleDiameter" / 2 - 1mm
"D2@LM8UUM3FastenerSketch4"="LM8UUFasteningHoleDiameter"
"LM8UUFasteningHoleDiameter"= 4.2mm'10/24 set screw hole diameter
"GABDistanceFromPulleyToOutside"= 8mm'the100 has this as 12.5. Decrease to 8 so WDistanceBetween can be increased
"D2@XAxisRodSketch2"="GABPulleyWDistanceBetween"/2
"D1@LM8UUM3FastenerCut-Extrude1"="LM8UUDiameter"
"D5@Top-Sketch1"="GABDistanceFromPulleyToOutside"
"D6@Top-Sketch1"="GABDistanceFromPulleyToOutside"
"D11@Top-Sketch1"="GABWidth"
"D1@Top-Sketch1"="GABDistanceFromBackToFirstPulley"
"SteelPushPinHoleDiameter"= "SteelShaft5mmHoleDiameter" - 1mm
