"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"D1@Sketch1" = "LowerRailHeight"
"D2@Sketch1" = "FrontOrBackRailLength"
"FrameFastenerHoleDiameter"= 8mm
"D3@Sketch1"="FrameFastenerHoleDiameter"
"D4@Sketch1" = "LowerRailHeight" / 2
"D5@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D6@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D1@Boss-Extrude2"="RailThickness"
"FrameFastenerHoleOffsetFromEdge"= "VSWidth" / 2 - "GapBetweenVerticalSupportsAndRails" / 2
"LowerRailHeight"= 2.0in
"FrontOrBackRailLength"= 20.5in
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
