"LowerRailWidth"= 2.00in
"RailThickness"= .125in'Spec
"StepperHoleDiameter"= 24mm
"StepperMountingHoleDiameter"= 3.175mm
"SideRailLength"= 550mm
"StepperMountingHoleDistance"= 31mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"FasteningHoleDiameter"= .125in
"D2@BotthomHoles-Sketch2" = "StepperMountingHoleOffsetFromLeftOrRightSide"
"D5@BotthomHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D6@BotthomHoles-Sketch2" = "StepperMountingHoleDistance"
"D7@BotthomHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D8@BotthomHoles-Sketch2" = "StepperMountingHoleDistance"
"D9@BotthomHoles-Sketch2" = "StepperMountingHoleDiameter"
"D10@BotthomHoles-Sketch2" = "StepperHoleDiameter"
"D1@Boss-Extrude1"="SideRailLength"
"BedThirdSize"= 70mm
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"BedInnerSquareLength"= "BedInnerSquareWidth"
"BedLWidth"= "BedThirdSize"'Equals 70
"BedLength"= "BedInnerSquareLength" + "BedLWidth" * 2 + "BedIncreasedByLength"'Equals 350
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 316
"DistanceFromBedFrontToFirstLeftStepperHole"= "LeadScrewNutPadSize" + 10mm'Equals 34
"DistanceFromFrontSideToBedFront"= "RailThickness" + "BeltTensionerDepth" + 10mm'Equals 36.575
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerBackWallThickness"= 4mm
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"BedIncreasedByLength"= 0mm
"LowerCornerBlockWidth"= "LowerRailWidth" - "RailThickness" * 2'Room for left front stepper
"D12@BotthomHoles-Sketch2"="CornerEnclosureOffset"
"D13@BotthomHoles-Sketch2"="FasteningHoleDiameter"
"CornerEnclosureOffset"= "LowerCornerBlockWidth" - "HoleOffsetFromEdge" + "RailThickness"
"LowerCornerBlockY1FromSide"= "HoleOffsetFromSide"
"D15@BotthomHoles-Sketch2"="StepperMountingHoleDistance"
"D16@BotthomHoles-Sketch2"="StepperMountingHoleDistance"/2
"D17@BotthomHoles-Sketch2"="DistanceBetweenFrontToBackStepperHoles"
"DistanceFromFrontSideToFirstLeftStepperHole"= "DistanceFromFrontSideToBedFront" + "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 70.575
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"D3@BotthomHoles-Sketch2"="DistanceFromFrontSideToFirstLeftStepperHole"
"LowerEnclosureThickness"= 5mm
"FrontBackRailLength"= 510mm
"D4@BotthomHoles-Sketch2"="LowerCornerBlockY1FromSide"
"D1@Sketch1"="FrontBackRailLength"
"D18@BotthomHoles-Sketch2"="StepperMountingHoleOffsetFromLeftOrRightSide"
"D19@BotthomHoles-Sketch2"="StepperMountingHoleDistance"/2
"D20@BotthomHoles-Sketch2"="StepperMountingHoleDistance"
"D21@BotthomHoles-Sketch2"="LowerCornerBlockY1FromSide"
"D22@BotthomHoles-Sketch2"="CornerEnclosureOffset"
"D23@BotthomHoles-Sketch2"="CornerEnclosureOffset"
"FrontOrBackEnclosureOffsets"= "FrontBackRailLength" / 4
"D24@BotthomHoles-Sketch2"="FrontOrBackEnclosureOffsets"
"D25@BotthomHoles-Sketch2"="FrontOrBackEnclosureOffsets"
"D26@BotthomHoles-Sketch2"="FrontOrBackEnclosureOffsets"
"D27@BotthomHoles-Sketch2"="LowerCornerBlockY1FromSide"
"D28@BotthomHoles-Sketch2"="LowerCornerBlockY1FromSide"
"D29@BotthomHoles-Sketch2"="FasteningHoleDiameter"
"D2@Sketch1"="LowerEnclosureThickness"
"24VPSUMountingHolesShortDistanceBetween"= 50mm'Yours may differ
"24VPSUMountingHolesLongDistanceBetween"= 152mm'Yours may differ
"24VPSUMountingHoleOffsetFromEitherSide"= 30mm'Yours may differ
"24VPSUMountingHoleOffsetFromEdge"= "24VPSUMountingHoleOffsetFromEitherSide" + "LowerRailWidth" + 10mm'Yours may differ
"24VPSUMountingHoleDiameter"= 3mm'Yours may differ
"D2@BottomPSUHolesSketch2" = "24VPSUMountingHolesShortDistanceBetween"
"D1@BottomPSUHolesSketch2" = "24VPSUMountingHolesLongDistanceBetween"
"D3@BottomPSUHolesSketch2" = "24VPSUMountingHoleOffsetFromEdge"
"D6@BottomPSUHolesSketch2" = "24VPSUMountingHoleDiameter"
"RPi4BoardLength"= 85mm'Spec
"RPi4BoardWidth"= 56mm'Spec
"RPi4BoardMountingHoleOffsetFromEdge"= 3.5mm'Spec
"RPi4BoardMountingHoleDiameter"= 2.7mm'Spec
"OctopusV1.1BoardMountingHoleOffsetFromAllEdges"= 3.5mm'Spec
"OctopusV1.1BoardMountingHoleLengthDistanceBetween"= 150mm'Spec
"OctopusV1.1BoardMountingHoleWidthDistanceBetween"= 90mm'Spec
"D4@RPIHolesSketch2" = "RPi4BoardMountingHoleLengthDistanceBetween"
"D5@RPIHolesSketch2" = "RPi4BoardWidth" - "RPi4BoardMountingHoleOffsetFromEdge" * 2
"D7@RPIHolesSketch2" = "RPi4BoardMountingHoleDiameter"
"RPi4BoardMountingHoleLengthDistanceBetween"= 58mm'Spec
"OctopusV1.1BoardMountingHoleDiameter"= 2.7mm'Spec
"D8@RPIHolesSketch2" =  ( "FrontBackRailLength" - "RPi4BoardLength" )  / 2 + "RPi4BoardMountingHoleOffsetFromEdge"
"D10@RPIHolesSketch2" = "LowerRailWidth" + "RPi4BoardMountingHoleOffsetFromEdge" + "EnclosurePartsOffsetFromFrameInnerEdge"
"RCNUN5VMountingHoleDiameter"= 6.5mm'Spec
"RCNUN5VHeight"= 57mm'Spec
"RCNUN5VMountingHoleWidthDistance"= 54mm'Spec. STL Is incorrect?
"D7@BottomPSUHolesSketch2"="RCNUN5VMountingHoleWidthDistance"
"D8@BottomPSUHolesSketch2"=("RCNUN5VMountingHoleWidthDistance" - "24VPSUMountingHolesShortDistanceBetween")/2
"D9@BottomPSUHolesSketch2"="LowerRailWidth" + "RCNUN5VHeight"/2 + "EnclosurePartsOffsetFromFrameInnerEdge"
"EnclosurePartsOffsetFromFrameInnerEdge"= 20mm
"D5@BottomPSUHolesSketch2"= "LowerRailWidth" + "EnclosurePartsOffsetFromFrameInnerEdge" + ( "24VPSULength" - "24VPSUMountingHolesLongDistanceBetween" ) / 2
"24VPSULength"= 213mm'Spec
"LowerRailCableHoleDiameter"= 8mm
"LowerRailCableHoleOffsetFromSide"= 8mm
"LowerRailCableHoleOffsetFromEdge"= 16mm
"D1@CableHolesSketch2"="LowerRailCableHoleOffsetFromEdge"
"D2@CableHolesSketch2"="LowerRailCableHoleOffsetFromEdge"
"D3@CableHolesSketch2"="LowerRailCableHoleOffsetFromEdge"
"D4@CableHolesSketch2"="LowerRailCableHoleOffsetFromSide"
"D5@CableHolesSketch2"="LowerRailCableHoleOffsetFromSide"
"D6@CableHolesSketch2"="LowerRailCableHoleDiameter"
"D7@CableHolesSketch2"="LowerRailCableHoleOffsetFromSide"
"D1@OctopusHolesSketch2"="OctopusV1.1BoardMountingHoleLengthDistanceBetween"
"D2@OctopusHolesSketch2"="OctopusV1.1BoardMountingHoleWidthDistanceBetween"
"D3@OctopusHolesSketch2"="OctopusV1.1BoardMountingHoleDiameter"
"24VPSUMountingHoleOffsetFromFront"= 30mm
"D5@OctopusHolesSketch2"="24VPSUMountingHoleOffsetFromFront" - "OctopusV1.1BoardMountingHoleOffsetFromAllEdges"
"DistanceBetween24VPSUAndOctopus"= "24VPSUMountingHoleOffsetFromEitherSide" + "OctopusV1.1BoardMountingHoleOffsetFromAllEdges" + 78'78mm gave me a nice distance to print a cable guide
"D4@OctopusHolesSketch2"="DistanceBetween24VPSUAndOctopus"
