"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"LowerRailHeight"= 2.0in
"D1@Sketch1"="LowerRailHeight"
"D2@Sketch1"= "FrontOrBackRailLength"
"FrameFastenerHoleDiameter"= 8mm
"D3@Sketch1"="FrameFastenerHoleDiameter"
"D4@Sketch1"="LowerRailHeight"/2
"D5@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D6@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D1@Boss-Extrude2"="RailThickness"
"FrontOrBackRailLength"= 20.5in
"FrameFastenerHoleOffsetFromEdge"= "VSWidth" / 2 - "GapBetweenVerticalSupportsAndRails" / 2
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
"ACPowerOutletHeight"= 30mm
"D2@ACOutletSketch2"="ACPowerOutletHeight"
"ACPowerOutletWidth"= 46.8mm
"D1@ACOutletSketch2"="ACPowerOutletWidth"
"D3@ACOutletSketch2"=("LowerRailHeight"-"ACPowerOutletHeight")/2
"AngleBracketSmallHoleDiameter"= 4mm
"AngleBracketSlotDistanceBetweenHoles"= 30mm
"AngleBracketSlotDistanceFromTop"= 13mm
"AngleBracketSlotDistanceFromCorner"= "AngleBracketSlotDistanceFromBack" - "GapBetweenVerticalSupportsAndRails" / 2'Equals 61.825
"AngleBracketSlotDistanceFromBack"= 65mm
"D8@Sketch1"="AngleBracketSlotDistanceBetweenHoles"
"D9@Sketch1"="AngleBracketSlotDistanceBetweenHoles"
"D10@Sketch1"="AngleBracketSlotDistanceFromCorner" -2mm
"D11@Sketch1"="AngleBracketSlotDistanceFromCorner" -2mm
"D12@Sketch1"="AngleBracketSmallHoleDiameter"
"D13@Sketch1"="AngleBracketSlotDistanceFromTop"
