"LowerRailWidth"= 2.00in
"LowerRailHeight"= 1.00in
"RailThickness"= .125in'Spec
"SideRailHoleY1FromEdge"= "HoleOffsetFromEdge"
"SideRailHoleX1FromSide"= "HoleOffsetFromSide"
"StepperHoleDiameter"= 24mm
"StepperMountingHoleDiameter"= 3.175mm
"SideRailLength"= 550mm
"StepperMountingHoleDistance"= 31mm'Spec
"VSWidth"= 1.25in'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"SideRailHoleX2FromSide"= "VSWidth" - "HoleOffsetFromEdge" - "RailThickness"'Equals 20.6375
"FasteningHoleDiameter"= .125in
"SideRailHoleY2FromSide"= "HoleOffsetFromSide"
"LHeight@Sketch1"="LowerRailHeight"
"LWidth@Sketch1"="LowerRailWidth"
"D1@Chamfer7"="LowerRailWidth"
"D1@Chamfer8"="LowerRailWidth"
"D2@BotthomHoles-Sketch2" = "StepperMountingHoleOffsetFromLeftOrRightSide"
"D3@BotthomHoles-Sketch2" = "StepperMountingHoleDistance"
"D4@BotthomHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D5@BotthomHoles-Sketch2"= "StepperMountingHoleDistance" / 2
"D6@BotthomHoles-Sketch2" = "StepperMountingHoleDistance"
"D7@BotthomHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D8@BotthomHoles-Sketch2" = "StepperMountingHoleDistance"
"D9@BotthomHoles-Sketch2" = "StepperMountingHoleDiameter"
"D10@BotthomHoles-Sketch2" = "StepperHoleDiameter"
"D2@LeftSideHoles-Sketch3" = "SideRailHoleX2FromSide"
"D4@LeftSideHoles-Sketch3" = "SideRailHoleY2FromSide"
"D7@LeftSideHoles-Sketch3" = "FasteningHoleDiameter"
"D1@Boss-Extrude1"="SideRailLength"
"D6@LeftSideHoles-Sketch3"="SideRailHoleX2FromSide"
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 316
"BedOverlap"= 20mm
"BedThirdSize"= 70mm
"BedLWidth"= "BedThirdSize" + "BedOverlap"'Equals 90
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"BedInnerSquareLength"= "BedInnerSquareWidth"
"BedLength"= "BedInnerSquareLength" + "BedLWidth" * 2 - "BedOverlap" * 2 + "BedIncreasedByLength"'Equals 350
"D12@BotthomHoles-Sketch2"="DistanceBetweenFrontToBackStepperHoles"
"DistanceFromFrontSideToFirstLeftStepperHole"= "DistanceFromFrontSideToBedFront" + "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 70.575
"D13@BotthomHoles-Sketch2"="DistanceFromFrontSideToFirstLeftStepperHole"
"DistanceFromBedFrontToFirstLeftStepperHole"= "LeadScrewNutPadSize" + 10mm'Equals 34
"DistanceFromFrontSideToBedFront"= "RailThickness" + "BeltTensionerDepth" + 10mm'Equals 36.575
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"BeltTensionerBackWallThickness"= 4mm
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"BedIncreasedByLength"= 0mm
"LowerCornerBlockWidth"= "LowerRailWidth" - "RailThickness" * 2'Room for left front stepper
"D17@BotthomHoles-Sketch2"="CornerEnclosureOffset"
"CornerEnclosureOffset"= "LowerCornerBlockWidth" - "HoleOffsetFromEdge" + "RailThickness"
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"LeftOrRightEnclosureOffsets"= "SideRailLength" / 4
"D8@LeftSideHoles-Sketch3"="LeftOrRightEnclosureOffsets"
"D9@LeftSideHoles-Sketch3"="LeftOrRightEnclosureOffsets"
"D10@LeftSideHoles-Sketch3"="LeftOrRightEnclosureOffsets"
"D5@LeftSideHoles-Sketch3"="SideRailHoleX1FromSide"
"D11@LeftSideHoles-Sketch3"="SideRailHoleX1FromSide"
"D3@LeftSideHoles-Sketch3"="SideRailHoleY1FromEdge"
