"LowerRailWidth"= 2.00in
"RailThickness"= .125in'Spec
"StepperHoleDiameter"= 24mm
"StepperMountingHoleDiameter"= 3.175mm
"SideRailLength"= 550mm
"StepperMountingHoleDistance"= 31mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"FasteningHoleDiameter"= .125in
"D2@BotthomHoles-Sketch2" = "StepperMountingHoleOffsetFromLeftOrRightSide"
"D5@BotthomHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D6@BotthomHoles-Sketch2" = "StepperMountingHoleDistance"
"D7@BotthomHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D8@BotthomHoles-Sketch2" = "StepperMountingHoleDistance"
"D9@BotthomHoles-Sketch2" = "StepperMountingHoleDiameter"
"D10@BotthomHoles-Sketch2" = "StepperHoleDiameter"
"D1@Boss-Extrude1"="SideRailLength"
"BedOverlap"= 20mm
"BedThirdSize"= 70mm
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"BedInnerSquareLength"= "BedInnerSquareWidth"
"BedLWidth"= "BedThirdSize" + "BedOverlap"'Equals 90
"BedLength"= "BedInnerSquareLength" + "BedLWidth" * 2 - "BedOverlap" * 2 + "BedIncreasedByLength"'Equals 350
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 316
"DistanceFromBedFrontToFirstLeftStepperHole"= "LeadScrewNutPadSize" + 10mm'Equals 34
"DistanceFromFrontSideToBedFront"= "RailThickness" + "BeltTensionerDepth" + 10mm'Equals 36.575
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerBackWallThickness"= 4mm
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"BedIncreasedByLength"= 0mm
"LowerCornerBlockWidth"= "LowerRailWidth" - "RailThickness" * 2'Room for left front stepper
"D12@BotthomHoles-Sketch2"="CornerEnclosureOffset"
"D13@BotthomHoles-Sketch2"="FasteningHoleDiameter"
"CornerEnclosureOffset"= "LowerCornerBlockWidth" - "HoleOffsetFromEdge" + "RailThickness"
"LowerCornerBlockY1FromSide"= "HoleOffsetFromSide"
"D15@BotthomHoles-Sketch2"="StepperMountingHoleDistance"
"D16@BotthomHoles-Sketch2"="StepperMountingHoleDistance"/2
"D17@BotthomHoles-Sketch2"="DistanceBetweenFrontToBackStepperHoles"
"DistanceFromFrontSideToFirstLeftStepperHole"= "DistanceFromFrontSideToBedFront" + "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 70.575
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"D3@BotthomHoles-Sketch2"="DistanceFromFrontSideToFirstLeftStepperHole"
"LowerEnclosureThickness"= 5mm
"FrontBackRailLength"= 510mm
"D4@BotthomHoles-Sketch2"="LowerCornerBlockY1FromSide"
"D1@Sketch1"="FrontBackRailLength"
"D18@BotthomHoles-Sketch2"="StepperMountingHoleOffsetFromLeftOrRightSide"
"D19@BotthomHoles-Sketch2"="StepperMountingHoleDistance"/2
"D20@BotthomHoles-Sketch2"="StepperMountingHoleDistance"
"D21@BotthomHoles-Sketch2"="LowerCornerBlockY1FromSide"
"D22@BotthomHoles-Sketch2"="CornerEnclosureOffset"
"D23@BotthomHoles-Sketch2"="CornerEnclosureOffset"
"FrontOrBackEnclosureOffsets"= "FrontBackRailLength" / 4
"D24@BotthomHoles-Sketch2"="FrontOrBackEnclosureOffsets"
"D25@BotthomHoles-Sketch2"="FrontOrBackEnclosureOffsets"
"D26@BotthomHoles-Sketch2"="FrontOrBackEnclosureOffsets"
"D27@BotthomHoles-Sketch2"="LowerCornerBlockY1FromSide"
"D28@BotthomHoles-Sketch2"="LowerCornerBlockY1FromSide"
"D29@BotthomHoles-Sketch2"="FasteningHoleDiameter"
"D2@Sketch1"="LowerEnclosureThickness"
