"MidBackRailWidth"= 2.00in
"MidBackRailHeight"= 1.00in
"RailThickness"= .125in'Spec
"SideRailHoleY1FromEdge"= "HoleOffsetFromEdge"
"SideRailHoleX1FromSide"= "HoleOffsetFromSide"
"StepperHoleDiameter"= 24mm
"StepperMountingHoleDiameter"= 3.175mm
"StepperMountingHoleDistance"= 31mm'Spec
"VSWidth"= 1.25in'Spec
"StepperMountingHoleOffsetFromLeftRightEdge"= "StepperMountingHoleOffsetFromItsSide"
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"SideRailHoleX2FromSide"= "VSWidth" - "HoleOffsetFromEdge" - "RailThickness"'Equals 20.6375
"FasteningHoleDiameter"= .125in
"SideRailHoleY2FromSide"= "HoleOffsetFromSide"
"FrontBackRailLength"= 510mm
"LHeight@Sketch1"="MidBackRailHeight"
"LWidth@Sketch1"="MidBackRailWidth"
"D2@BotthomHoles-Sketch2" = "StepperMountingHoleOffsetFromLeftRightEdge"
"D3@BotthomHoles-Sketch2" = "StepperMountingHoleDistance"
"D4@BotthomHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D5@BotthomHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D6@BotthomHoles-Sketch2" = "StepperMountingHoleDistance"
"D7@BotthomHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D9@BotthomHoles-Sketch2" = "StepperMountingHoleDiameter"
"D10@BotthomHoles-Sketch2" = "StepperHoleDiameter"
"D4@SideHoles-Sketch3" = "SideRailHoleY2FromSide"
"D7@SideHoles-Sketch3" = "FasteningHoleDiameter"
"D1@Boss-Extrude1"= "FrontBackRailLength"
"D3@SideHoles-Sketch3"="SideRailHoleY1FromEdge"
"D1@SideHoles-Sketch3"="SideRailHoleX1FromSide"
"D2@SideHoles-Sketch3"= "SideRailHoleX2FromSide"
"D6@SideHoles-Sketch3"="SideRailHoleX2FromSide"
"D5@SideHoles-Sketch3"="SideRailHoleX1FromSide"
"StepperHoleToAlignHorizontallyWithGantryBlock"= "MidRailToAlignWithGantryBlock" + "RailThickness"'MidSideRail buts up against MidBackRail
"D13@BotthomHoles-Sketch2"="StepperHoleToAlignHorizontallyWithGantryBlock" 
"D8@BotthomHoles-Sketch2"="StepperMountingHoleDistance"
"D11@BotthomHoles-Sketch2"="StepperHoleToAlignHorizontallyWithGantryBlock" 
"LinearGBWithRailDepth"= 12.75mm'Spec
"GABDistanceFromBackToFirstPulley"= 13.5mm
"MidRailToAlignWithGantryBlock"= "LinearGBWithRailDepth" + "GABDistanceFromBackToFirstPulley"'All outside cogs must align
