"MidBackRailWidth"= 2.00in
"MidBackRailHeight"= 1.00in
"RailThickness"= .125in'Spec
"SideRailHoleY1FromEdge"= "HoleOffsetFromEdge"
"SideRailHoleX1FromSide"= "HoleOffsetFromSide"
"StepperHoleDiameter"= 24mm
"StepperMountingHoleDiameter"= 3.175mm
"StepperMountingHoleDistance"= 31mm'Spec
"VSWidth"= 1.25in'Spec
"StepperMountingHoleOffsetFromLeftRightEdge"= "StepperMountingHoleOffsetFromItsSide"
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"SideRailHoleX2FromSide"= "VSWidth" - "HoleOffsetFromEdge" - "RailThickness"'Equals 20.6375
"FasteningHoleDiameter"= .125in
"SideRailHoleY2FromSide"= "HoleOffsetFromSide"
"FrontBackRailLength"= 510mm
"LHeight@Sketch1"="MidBackRailHeight"
"LWidth@Sketch1"="MidBackRailWidth"
"D2@TopHoles-Sketch2" = "StepperMountingHoleOffsetFromLeftRightEdge"
"D3@TopHoles-Sketch2" = "StepperMountingHoleDistance"
"D4@TopHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D5@TopHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D6@TopHoles-Sketch2" = "StepperMountingHoleDistance"
"D7@TopHoles-Sketch2" = "StepperMountingHoleDistance" / 2
"D9@TopHoles-Sketch2" = "StepperMountingHoleDiameter"
"D10@TopHoles-Sketch2" = "StepperHoleDiameter"
"D4@BackSideHoles-Sketch3" = "SideRailHoleY2FromSide"
"D7@BackSideHoles-Sketch3" = "FasteningHoleDiameter"
"D1@Boss-Extrude1"= "MidBackRailLength"
"D3@BackSideHoles-Sketch3"="SideRailHoleY1FromEdge"
"D1@BackSideHoles-Sketch3"="SideRailHoleX1FromSide" - "RailThickness"
"D2@BackSideHoles-Sketch3"="SideRailHoleX2FromSide" - "RailThickness"
"D6@BackSideHoles-Sketch3"="SideRailHoleX2FromSide" - "RailThickness"
"D5@BackSideHoles-Sketch3"="SideRailHoleX1FromSide" - "RailThickness"
"StepperHoleToAlignHorizontallyWithGantryBlock"= "LinearGBWithRailDepth" + "GABDistanceFromBackToFirstPulley"'Equals 26.25
"D13@TopHoles-Sketch2"="StepperHoleToAlignHorizontallyWithGantryBlock" 
"D8@TopHoles-Sketch2"="StepperMountingHoleDistance"
"D11@TopHoles-Sketch2"="StepperHoleToAlignHorizontallyWithGantryBlock" 
"LinearGBWithRailDepth"= 12.75mm'Spec
"GABDistanceFromBackToFirstPulley"= 13.5mm
"MidBackRailLength"= "FrontBackRailLength" - "RailThickness" * 2'MidBackRail buts up against MidSideRail
