"MidLeftOrRightSideRailHeight"= 2.0in
"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"LHeight@Sketch1"="MidLeftOrRightSideRailHeight"
"LMaterialThickness@Sketch1"="RailThickness"
"D1@Boss-Extrude1" = "SideRailLength"
"SideRailLength"= 21.75in
"D7@SideHoles-Sketch4"="MidLeftOrRightSideRailHeight"/2
"DistanceFromFrontSideToBedFrontYSValue"= 48.525mm
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "BuildPlateStandoffHolesDistanceFromFrontOrBackSide" * 2'Equals 270
"DistanceFromFrontSideToFirstLeftStepperHoleMountYSValue"= 74.025mm
"FrameFastenerHoleOffsetFromEdge"= "VSWidth" / 2 - "GapBetweenVerticalSupportsAndRails" / 2
"D2@SideHoles-Sketch4"="FrameFastenerHoleOffsetFromEdge"
"FrameFastenerHoleDiameter"= 8mm
"D3@SideHoles-Sketch4"="FrameFastenerHoleDiameter"
"D4@SideHoles-Sketch4"="FrameFastenerHoleOffsetFromEdge"
"StepperMountSlotDiameterOnRails"= 4.2mm
"StepperMountSlotWidth"= 6mm
"D5@SideHoles-Sketch4"="StepperMountSlotWidth"
"D6@SideHoles-Sketch4"="StepperMountSlotDiameterOnRails"
"D13@SideHoles-Sketch4" = "Nema17StepperMountSlotDistance"
"D16@SideHoles-Sketch4" = "Nema17StepperMountSlotDistance"
"D19@SideHoles-Sketch4"="DistanceBetweenFrontToBackStepperHoles"
"D15@SideHoles-Sketch4"="DistanceFromFrontSideToFirstLeftStepperHoleMountYSValue"
"D10@SideHoles-Sketch4"="SK8MountHoleFromEitherEnd"
"RodShaft440mmLength"= 440mm
"SK8RodShaftSupportLength"= 15mm
"D11@SideHoles-Sketch4"="DistanceFromFrontSideToBedFrontYSValue" - ("SK8RodShaftSupportLength" /2) + 3mm
"D12@SideHoles-Sketch4"="RodShaft440mmLength"-"SK8RodShaftSupportLength"
"BuildPlateStandoffHolesDistanceFromFrontOrBackSide"= 41mm
"SK8MountHoleFromEitherEnd" = 5.5mm
"BuildPlateLength"= 352mm'Spec
"BedLength"= "BuildPlateLength"
"Nema17StepperMountSlotDistance"= 31mm'Spec
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
"D14@SideHoles-Sketch4"=27.8
"D18@SideHoles-Sketch4"="Nema17StepperMountSlotDistance"
"DistanceFromBackToFirstGantryStepperHole"= "VSWidth" - "RailThickness" + ( "Nema17MountWidth" - "Nema17StepperMountSlotDistance" ) / 2 - "GapBetweenVerticalSupportsAndRails" / 2'Equals 34.9. Push Gantry stepper as far back as possible
"D17@SideHoles-Sketch4"="DistanceFromBackToFirstGantryStepperHole"
"Nema17MountWidth"= 50mm'Spec
