"RailThickness"= .125in'Spec
"SideRailHoleY1FromEdge"= "HoleOffsetFromEdge"
"SideRailHoleX1FromSide"= "HoleOffsetFromSide"
"MidSideRailLength"= "SideRailLength"
"VSWidth"= 1.25in'Spec
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"SideRailHoleX2FromSide"= "VSWidth" - "HoleOffsetFromEdge" - "RailThickness"'Equals 20.6375
"FasteningHoleDiameter"= .125in
"D2@LeftSideHoles-Sketch4" = "FasteningHoleDiameter"
"LHeight@Sketch1"="MidLeftOrRightSideRailHeight"
"LMaterialThickness@Sketch1"="RailThickness"
"D1@Boss-Extrude1"="MidSideRailLength"
"D4@LeftSideHoles-Sketch4" = "SideRailHoleY1FromEdge"
"D1@LeftSideHoles-Sketch4"="SideRailHoleX1FromSide"
"D6@LeftSideHoles-Sketch4"="SideRailHoleX2FromSide" 
"D3@LeftSideHoles-Sketch4"="SideRailHoleX1FromSide" 
"D5@LeftSideHoles-Sketch4"="SideRailHoleX2FromSide" 
"D7@LeftSideHoles-Sketch4"="HoleOffsetFromEdge"
"LinearRailXMountHole"= "StepperWidth" + "LinearRailFirstHoleOffsetFromEdge"
"D8@LeftSideHoles-Sketch4"="LinearRailXMountHole"
"LinearRailHoleDistance"= 25mm'Spec
"D12@LeftSideHoles-Sketch4"="LinearRailHoleDistance"
"LinearRailFirstHoleOffsetFromEdge"= 12.5mm'Spec
"SideRailLength"= 550mm
"MidLeftOrRightSideRailHeight"= 2.0in
"StepperWidth"= 42mm'Spec
"StepperHolePadSize"= "StepperHoleDiameter"
"MidRailRodStabilizerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge"
"D13@LeftSideHoles-Sketch4"="MidRailRodStabilizerMountingHoleOffsetFromEdge"
"D14@LeftSideHoles-Sketch4"="FasteningHoleDiameter"
"DistanceFromBedFrontToFirstLeftStepperHole"= "LeadScrewNutPadSize" + 10mm'Equals 34
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerBackWallThickness"= 4mm
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"DistanceFromFrontSideToBedFront"= "RailThickness" + "BeltTensionerDepth" + 10mm'Equals 36.575
"DistanceFromFrontSideToFirstLeftStepperHole"= "DistanceFromFrontSideToBedFront" + "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 70.575
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 316
"BedLength"= "BedInnerSquareLength" + "BedLWidth" * 2 + "BedIncreasedByLength"'Equals 350
"BedThirdSize"= 70mm
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"BedLWidth"= "BedThirdSize"'Equals 70
"BedIncreasedByLength"= 0mm
"BedInnerSquareLength"= "BedInnerSquareWidth"
"DistanceFromFrontSideToFirstLeftRodStabilizerMountingHole"= "DistanceFromFrontSideToFirstLeftStepperHole" - "DistanceFromStepperHoleToRodStabilizerMountingHole"'Equals 53.5125
"D15@LeftSideHoles-Sketch4"="DistanceFromFrontSideToFirstLeftRodStabilizerMountingHole"
"D17@LeftSideHoles-Sketch4"="DistanceBetweenFrontToBackStepperHoles"
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"D20@LeftSideHoles-Sketch4"="RodStabilizerLength" - "HoleOffsetFromEdge" * 2
"DistanceFromStepperHoleToRodStabilizerMountingHole"= "RodStabilizerLength" / 2 - "HoleOffsetFromEdge"'Equals 17.0625
"RodStabilizerLength"= 50mm
"D16@LeftSideHoles-Sketch4"="RodStabilizerLength" - "HoleOffsetFromEdge" * 2
"LinearRailWidth"= 12mm'Spec
"MidSideRailVerticalOffset"= "LinearRailWidth" + 3mm'Allows space for RodStabilizer to attach to bottom of MidSideRail
"D9@LeftSideHoles-Sketch4"="MidSideRailVerticalOffset"
