"RailThickness"= .125in'Spec
"SideRailHoleY1FromEdge"= "HoleOffsetFromEdge"
"SideRailHoleX1FromSide"= "HoleOffsetFromSide"
"MidSideRailLength"= "SideRailLength" - "RailThickness"'Equals 546.825 => MidSideRail buts up against MidBackRail
"VSWidth"= 1.25in'Spec
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"SideRailHoleX2FromSide"= "VSWidth" - "HoleOffsetFromEdge" - "RailThickness"'Equals 20.6375
"FasteningHoleDiameter"= .125in
"D2@LeftSideHoles-Sketch4" = "FasteningHoleDiameter"
"LHeight@Sketch1"="MidLeftOrRightSideRailHeight"
"LMaterialThickness@Sketch1"="RailThickness"
"D1@Boss-Extrude1"="MidSideRailLength"
"D4@LeftSideHoles-Sketch4" = "SideRailHoleY1FromEdge"
"D1@LeftSideHoles-Sketch4"="SideRailHoleX1FromSide"
"D6@LeftSideHoles-Sketch4"="SideRailHoleX2FromSide" 
"D3@LeftSideHoles-Sketch4"="SideRailHoleX1FromSide" - "RailThickness"
"D5@LeftSideHoles-Sketch4"="SideRailHoleX2FromSide" - "RailThickness"
"D7@LeftSideHoles-Sketch4"="HoleOffsetFromSide"
"LinearRailXMountHole"= "StepperWidth" + "LinearRailFirstHoleOffsetFromEdge"
"D8@LeftSideHoles-Sketch4"="LinearRailXMountHole"
"D9@LeftSideHoles-Sketch4"="V6.3 GantryMiddleToToTopOfMidSideRail"
"LinearRailHoleDistance"= 25mm'Spec
"D12@LeftSideHoles-Sketch4"="LinearRailHoleDistance"
"LinearRailFirstHoleOffsetFromEdge"= 12.5mm'Spec
"SideRailLength"= 550mm
"MidLeftOrRightSideRailHeight"= 2.0in
"StepperWidth"= 42mm'Spec
"StepperHolePadSize"= "StepperHoleDiameter"
"MidRailRodStabilizerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge"
"D13@LeftSideHoles-Sketch4"="MidRailRodStabilizerMountingHoleOffsetFromEdge"
"D14@LeftSideHoles-Sketch4"="FasteningHoleDiameter"
"DistanceFromBedFrontToFirstLeftStepperHole"= "LeadScrewNutPadSize" + 10mm'Equals 34
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerBackWallThickness"= 4mm
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"DistanceFromFrontSideToBedFront"= "RailThickness" + "BeltTensionerDepth" + 10mm'Equals 36.575
"DistanceFromFrontSideToFirstLeftStepperHole"= "DistanceFromFrontSideToBedFront" + "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 70.575
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 316
"BedLength"= "BedInnerSquareLength" + "BedLWidth" * 2 - "BedOverlap" * 2 + "BedIncreasedByLength"'Equals 350
"BedOverlap"= 20mm
"BedThirdSize"= 70mm
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"BedLWidth"= "BedThirdSize" + "BedOverlap"'Equals 90
"BedIncreasedByLength"= 0mm
"LM8UUDiameter"= 15mm
"RodStabilizerDepth"= "LM8UUDiameter" * 2
"BedInnerSquareLength"= "BedInnerSquareWidth"
"DistanceFromFrontSideToFirstLeftRodStabilizerMountingHole"= "DistanceFromFrontSideToFirstLeftStepperHole" - "DistanceFromStepperHoleToRodStabilizerMountingHole"'Equals 53.5125
"D15@LeftSideHoles-Sketch4"="DistanceFromFrontSideToFirstLeftRodStabilizerMountingHole"
"D17@LeftSideHoles-Sketch4"="DistanceBetweenFrontToBackStepperHoles"
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"GABUpperHeight"= 6mm
"GABLowerHeight"= 3mm
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"GABRiserBossOffset"= 0.8mm'Aligns Pulleys
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"V6.1 FromGantryPulleyToGantryMiddle"= "GABHeight" / 2 - "GABMidShortRiserHeight" - "GABLowerHeight" + "GABRiserBossOffset" / 2
"V6.2 GantryMiddleToTopOfMidBackRail"= "StepperShaftLength" - "V6.1 FromGantryPulleyToGantryMiddle"
"V6.3 GantryMiddleToToTopOfMidSideRail"= "V6.2 GantryMiddleToTopOfMidBackRail" - "RailThickness"
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"RodStabilizerMountingHoleOffsetInsideX"= 14.125mm'Backward compatible
"RodStabilizerMountingHoleOffsetOutsideX"= 12mm
"D20@LeftSideHoles-Sketch4"="RodStabilizerLength" - "HoleOffsetFromEdge" * 2
"DistanceFromStepperHoleToRodStabilizerMountingHole"= "RodStabilizerLength" / 2 - "HoleOffsetFromEdge"'Equals 17.0625
"RodStabilizerLength"= 50mm
"D16@LeftSideHoles-Sketch4"="RodStabilizerLength" - "HoleOffsetFromEdge" * 2
