"MidLeftOrRightSideRailHeight"= 2.0in
"RailThickness"= .125in'Spec
"SideRailHoleY1FromEdge"= "HoleOffsetFromEdge"
"SideRailHoleX1FromSide"= "HoleOffsetFromSide"
"MidSideRailLength"= "SideRailLength"
"VSWidth"= 1.25in'Spec
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"SideRailHoleX2FromSide"= "VSWidth" - "HoleOffsetFromEdge" - "RailThickness"'Equals 20.6375
"FasteningHoleDiameter"= .125in
"StepperWidth"= 42mm'Spec
"D2@SideHoles-Sketch4"="FasteningHoleDiameter"
"LHeight@Sketch1"="MidLeftOrRightSideRailHeight"
"LMaterialThickness@Sketch1"="RailThickness"
"D1@Boss-Extrude1"="MidSideRailLength"
"D4@SideHoles-Sketch4"="SideRailHoleY1FromEdge"
"D3@SideHoles-Sketch4"="SideRailHoleX1FromSide" 
"D5@SideHoles-Sketch4"="SideRailHoleX2FromSide" 
"D1@SideHoles-Sketch4"="SideRailHoleX1FromSide" 
"D6@SideHoles-Sketch4"="SideRailHoleX2FromSide"
"LinearRailXMountHole"= "StepperWidth" + "LinearRailFirstHoleOffsetFromEdge"
"D9@SideHoles-Sketch4"="V6.3 GantryMiddleToToTopOfMidSideRail"
"D8@SideHoles-Sketch4"="LinearRailXMountHole"
"LinearRailHoleDistance"= 25mm'Spec
"D12@SideHoles-Sketch4"="LinearRailHoleDistance"
"SideRailLength"= 550mm
"LinearRailFirstHoleOffsetFromEdge"= 12.5mm'Spec
"D7@SideHoles-Sketch4"= "MidRailRodStabilizerMountingHoleOffsetFromEdge"
"DistanceFromBedFrontToFirstLeftStepperHole"= "LeadScrewNutPadSize" + 10mm'Equals 34
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerBackWallThickness"= 4mm
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"DistanceFromFrontSideToBedFront"= "RailThickness" + "BeltTensionerDepth" + 10mm'Equals 36.575
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 316
"BedLength"= "BedInnerSquareLength" + "BedLWidth" * 2 + "BedIncreasedByLength"'Equals 350
"BedThirdSize"= 70mm
"BedInnerSquareWidth"= "BedThirdSize" * 3'Equals 210
"BedLWidth"= "BedThirdSize"'Equals 70
"BedIncreasedByLength"= 0mm
"D14@SideHoles-Sketch4"= "FasteningHoleDiameter"
"D15@SideHoles-Sketch4"= "HoleOffsetFromEdge"
"BedInnerSquareLength"= "BedInnerSquareWidth"
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"GABUpperHeight"= 6mm
"GABLowerHeight"= 3mm
"GABRiserBossOffset"= 0.8mm'Aligns Pulleys
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"V6.1 FromGantryPulleyToGantryMiddle"= "GABHeight" / 2 - "GABMidShortRiserHeight" - "GABLowerHeight" + "GABRiserBossOffset" / 2
"V6.2 GantryMiddleToTopOfMidBackRail"= "StepperShaftLength" - "V6.1 FromGantryPulleyToGantryMiddle"
"V6.3 GantryMiddleToToTopOfMidSideRail"= "V6.2 GantryMiddleToTopOfMidBackRail" - "RailThickness"
"DistanceFromFrontSideToFirstLeftStabilizerMountingHole"= "DistanceFromFrontSideToFirstLeftStepperHole" - "DistanceFromStepperHoleToRodStabilizerMountingHole"'Equals 53.5125
"DistanceFromFrontSideToFirstLeftStepperHole"= "DistanceFromFrontSideToBedFront" + "DistanceFromBedFrontToFirstLeftStepperHole"'Equals 70.575
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"D17@SideHoles-Sketch4"="DistanceFromFrontSideToFirstLeftStabilizerMountingHole"
"D18@SideHoles-Sketch4"="DistanceBetweenFrontToBackStepperHoles"
"MidRailRodStabilizerMountingHoleOffsetFromEdge"= "HoleOffsetFromEdge"
"RodStabilizerLength"= 50mm
"DistanceFromStepperHoleToRodStabilizerMountingHole"= "RodStabilizerLength" / 2 - "HoleOffsetFromEdge"'Equals 17.0625
"D13@SideHoles-Sketch4"="RodStabilizerLength" - "HoleOffsetFromEdge" * 2
"D16@SideHoles-Sketch4"="RodStabilizerLength" - "HoleOffsetFromEdge" *2
