"D2@Sketch1" = "PowerCableGuideWidth"
"PowerCableGuideWidth"= "DistanceBetweenPowerSupplyLeads" * "NumberOfPowerLeadSpaces" + "PowerCableDiameter" * 2 + "DistanceFromCaseToFirstPowerTerminal" + "PowerCableGuideMountSupportWidth" * 2
"PowerCableGuideLength"= 60mm
"PowerCableDiameter"= 3mm
"NumberOfPowerLeadSpaces"= 10
"M3HeatInsertHoleDiameter"= 4mm + .1mm'Add .1mm for printing
"DistanceBetweenPowerSupplyLeads"= 9.5mm'Spec
"PowerCableGuideDepth"= 15mm
"DistanceFromCaseToFirstPowerTerminal"= 13mm + "PowreCableGuideAdditionalPowerWidth"
"PowerCableGuideMountSupportWidth"= 12mm
"D1@Sketch1"="PowerCableGuideLength"
"D1@ProfileBoss-Extrude1" = "PowerCableGuideDepth"
"D1@LeedCut-Extrude1" = "PowerCableDiameter" * 2
"D2@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D4@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D5@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D3@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D1@Sketch2"="PowerCableDiameter"
"D8@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D9@Sketch2"="PowerCableGuideMountSupportWidth"
"D13@Sketch2"="PowerCableDiameter"
"D10@Sketch2"="DistanceFromCaseToFirstPowerTerminal"
"PowreCableGuideAdditionalPowerWidth"= 7mm
"D3@MountHoleSketch3" = "PowerCableGuideLength" / 2
"D4@MountHoleSketch3" = "M3HeatInsertHoleDiameter"
"PowerCableGuideMountHoleDistanceBetween"= "PowerCableGuideWidth" - "PowerCableGuideMountSupportWidth"
"D2@MountHoleSketch3" = "PowerCableGuideMountHoleDistanceBetween"
"D1@MountHoleSketch3" = "PowerCableGuideMountSupportWidth" / 2
"D14@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D15@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D16@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D6@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D11@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D18@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D7@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D12@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D22@Sketch2"="DistanceBetweenPowerSupplyLeads"
"D17@Sketch2"="DistanceBetweenPowerSupplyLeads"
"M3HeatInsertHoleDepth"= 4mm
