"D1@Sketch1"="ClampWidth"
"RibbonCableWidth"= 5.25mm
"RibbonCableInnerHypotonus"= sqr ( "RibbonCableHoleWidth" ^ 2 * 2 )
"M2.5HeatInsertHoleDiameter" = 4mm + .1mm'Add .1mm for printing
"FastenerTabHoleCenterFromSide"= 2mm
"ClampWallWidth"= 2mm
"ClampWidth"= "RibbonCableHoleWidth" + "ClampWallWidth" * 2 + "RibbonCableWidthExtension"
"ClampHeight"= "BaseBoss" + "RibbonCableUpperWallHeight" + "ClampBridgeHeight"
"BaseBoss"= "M2.5HeatInsertHoleDepth" + 1mm
"RibbonCableLowerWallHeight"= 1mm
"RibbonCableOuterHypotonus"= sqr ( ( "ClampWallWidth" ^ 2 ) * 2 ) + "RibbonCableInnerHypotonus" + sqr ( ( "ClampWallWidth" ^ 2 ) * 2 )
"RibbonCableHeight"= 1.5mm
"D1@BaseBoss-Extrude1" = "BaseBoss"
"D1@Sketch2"="ClampWallWidth"
"D2@Sketch2"="ClampWallWidth"
"D3@Sketch2"="ClampWallWidth"
"D4@Sketch2"="ClampWallWidth"
"D1@WallsBoss-Extrude2"="RibbonCableUpperWallHeight"
"D1@AngleSketch3" = "RibbonCableInnerHypotonus"
"RibbonCableWidthExtension"= 5mm
"D3@AngleSketch3" = "ClampWallWidth"
"D1@AngleBoss-Extrude3" = "ClampWallWidth"
"D1@Sketch4"="RibbonCableHeight"
"D3@Sketch4"="RibbonCableHeight"/2 + "ClampWallWidth"
"D4@Sketch4" = "RibbonCableHoleWidth" - "RibbonCableHeight"
"D1@InCut-Extrude1" = "ClampWallWidth"
"D1@Sketch5"="RibbonCableHeight"
"D2@Sketch5" = "RibbonCableHoleWidth" - "RibbonCableHeight"
"D3@Sketch5" = ( "ClampWidth" - "RibbonCableHoleWidth" + "RibbonCableHeight" ) / 2
"D1@OutCut-Extrude2" = "ClampWallWidth"
"ClampBridgeHeight"= 2mm
"RibbonCableUpperWallHeight"= "RibbonCableLowerWallHeight" + "RibbonCableHeight" + .5mm
"D1@TopWireOpeningSketch6" = "RibbonCableHoleWidth" * "RibbonCableSlotPercentage"
"D2@TopWireOpeningSketch6" = ( "ClampWidth" - "RibbonCableHoleWidth" * "RibbonCableSlotPercentage" ) / 2
"D1" = "RibbonCableHeight" + 2mm
"RibbonCableHoleWidth"= "RibbonCableWidth" + 1mm
"D3@TopWireOpeningSketch6"= "RibbonCableHeight" / 2 + "ClampWallWidth" + ( "RibbonCableHoleWidth" - "RibbonCableHeight" ) / 2 - "RibbonCableHoleWidth" * "RibbonCableSlotPercentage" / 2
"M2.5HeatInsertHoleDepth"= 4.1mm'Spec
"D2@Sketch4"="RibbonCableLowerWallHeight"
"D4@Sketch5"="RibbonCableLowerWallHeight"
"D1@MountHoleSketch8" = "M2.5HeatInsertHoleDiameter"
"D1@MountHoleCut-Extrude1" = "M2.5HeatInsertHoleDepth"
"RibbonCableSlotPercentage"= .44
