"RibbonCableWidth"= 6.75mm
"RibbonCableHypotonus"= sqr ( "RibbonCableWidth" ^ 2 * 2 )
"FastenerTabWidth"= 5mm
"FastenerTabHoleDiameter"= "FastenerTabWidth" / 2
"FastenerTabHoleCenterFromSide"= 2mm
"ClampBridgeWidth"= 2mm
"ClampWidth"= "RibbonCableWidth" + "ClampBridgeWidth" * 2
"ClampBridgeHeight"= 8mm
"BaseBoss"= 1mm
"D1@ProfileBoss-Extrude1" = 1mm
"D2@Sketch1"="ClampBridgeWidth"
"D1@AngleBoss-Extrude3" = "ClampBridgeHeight" - "BaseBoss"
"D1@UnderRollerSketch10" = "ClampBridgeWidth"
"D1@UnderRollerCut-Extrude5" = "ClampBridgeWidth"
"D6@Sketch1"="FastenerTabHoleDiameter"
"D4@Sketch1"="ClampBridgeWidth"*2
"D1@Sketch8"="ClampBridgeWidth"
"D2@Sketch8"="RibbonCableWidth"
"D1@KnotchSketch13" = "ClampBridgeWidth"
"D3@Sketch8"="RibbonCableLowerWallHeight" + 1mm
"RibbonCableLowerWallHeight"= 3mm
"D1@AngleSketch7"="ClampBridgeWidth"
"D2@AngleSketch7"="ClampBridgeWidth"
"D3@Sketch1"="ClampWidth"/2
