"RibbonCableWidth"= 5.25mm
"M2.5HeatInsertHoleDiameter" = 4mm + .1mm'Add  .1mm for printing
"ClampBridgeWidth"= 2mm
"ClampWidth"= "RibbonCableHoleWidth" + "ClampBridgeWidth" * 2
"ClampBridgeHeight"= 5.5mm
"BaseBoss"= "M2.5HeatInsertDepth" + .2mm'Add .2mm to cover mounting hole
"D1@ProfileBoss-Extrude1"="BaseBoss"
"D1@AngleBoss-Extrude3"="ClampBridgeHeight" 
"D1@UnderRollerSketch10" = "ClampBridgeWidth"
"D1"= "ClampBridgeWidth"
"D4@Sketch1"="ClampBridgeWidth"*2
"RibbonCableLowerWallHeight"= 2mm
"D2@AngleSketch7"="ClampBridgeWidth"
"D1@OutChamfer1"="RibbonCableLowerWallHeight"
"D3@UnderRollerSketch10"="ClampBridgeWidth"
"D2@Sketch2"="RibbonCableHoleWidth" *.33
"D1@Sketch2"=("ClampWidth" - "RibbonCableHoleWidth" *.33)/2
"RibbonCableHoleWidth"= "RibbonCableWidth" + 1mm
"D2@Sketch1"="ClampWidth" + "ClampBridgeWidth"
"M2.5HeatInsertDepth" = 4mm'Spec
"D1@Sketch1"="ClampWidth"
"D1@ClampMountHoleSketch3" = "M2.5HeatInsertHoleDiameter"
"D2@ClampMountHoleSketch3" = "ClampWidth" / 2
"D1@Cut-Extrude1"="M2.5HeatInsertDepth"
