"GABDepth"= "GABDistanceFromBackToFirstPulley" + "GABPulleyDDistanceBetween" + "GABDistanceFromPulleyToFront"
"GABWidth"= "StandardWallThickness" + "GABDistanceFromLSideToPulley" + "GABPulleyWDistanceBetween" + "GABDistanceFromPulleyToRSide"
"StandardWallThickness"= 3mm
"LinearRailWidth"= 12mm'Spec
"LinearRailHeight"= 8mm'Spec
"GABLRClampHoleOffsetFromSide"= 5mm
"GABDistanceFromBackToFirstPulley"= 13.5mm
"GABPulleyDDistanceBetween"= 12.5mm'From the100
"GABPulleyWDistanceBetween"= 14.5mm'From the100
"GABDistanceFromPulleyToFront"= 8mm
"GABDistanceFromLSideToPulley"= 9.5mm + "StandardWallThickness"
"GABDistanceFromPulleyToRSide"= 7.5mm
"GABClampBaseHeight"= 2mm
"LinearRailHoleDiameter"= 3.5mm'Spec
"GABDistanceToFrontRearClampHoles"= 8.5mm
"D1@TopSketch1" = "GABWidth"
"D2@TopSketch1"="GABDepth"
"D5@TopSketch1" = "GABDistanceToFrontRearClampHoles"
"D7@TopSketch1" = "GABLRClampHoleOffsetFromSide"
"D8@TopSketch1" = "GABLRClampHoleOffsetFromSide"
"D1@TopBoss-Extrude1" = "GABClampBaseHeight"
"RailThickness"= .125in'Spec
"D4@TopSketch1"="LinearRailHeight"
"D1@LinearRailHeightBoss-Extrude2" = "LinearRailWidth"
"D1@LinearRailHolesSketch3" = "LinearRailHoleDiameter"
"D2@LinearRailHolesSketch3" = "LinearRailWidth" / 2
"D9@TopSketch1"="GABDistanceToFrontRearClampHoles"
"D2@LinearRailHEightSketch2"="GABDepth"/3
"D11@TopSketch1"=("GABWidth")/2 - "LinearRailHeight"+1/2
"LinearRailHoleDistance"= 25mm'Spec
"D1@ConnectingPlateSketch2" = "LinearRailHoleDistance"
"D1@ConnectingPlateCut-Extrude1"="LinearRailHeight"/2
"D1@Fillet2"="RailThickness"
"LinearRailSupportNutWidth"= 6.2mm
"D1@Sketch1"="LinearRailSupportNutWidth"
"LinearRailSupportNutHoleDepth" = "LinearRailHeight" / 4
"D1@Cut-Extrude1"="LinearRailSupportNutHoleDepth"
