"BeltTensionerWidth"= "MidRailToAlignWithGantryBlock" + "BeltTensionerInnerWidth" / 2 + "RailThickness"
"BeltTensionerHeight"= 60mm
"BeltTensionerDepth"= "BeltTensionerBackWallThickness" + "BeltTensionerInnerDepth"'Equals 23.4
"BeltTensionerInnerWidth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"BeltTensionerInnerHeight"= "20TGT2PulleyWidth" * 2 + "1mmSpacer" * 3
"BeltTensionerBackWallThickness"= 4mm
"BeltTensionerInnerDepth"= "20TGT2PulleyDiameter" + "BeltTensionerSpaceBetweenPulleyAndWall"
"RailThickness"= .125in'Spec
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"LinearGBWithRailDepth"= 12.75mm'Spec
"GABDistanceFromBackToFirstPulley"= 13.5mm
"MidRailToAlignWithGantryBlock"= "LinearGBWithRailDepth" + "GABDistanceFromBackToFirstPulley"'All outside cogs must align
"20TGT2PulleyDiameter"= 17.9mm'Spec
"BeltTensionerSpaceBetweenPulleyAndWall"= 1.5mm
"BeltTensionerMountingHoleDiameter"= 4.0mm
"BeltTensionerMountingHoleOffsetFromTopOrBottom"= ( "BeltTensionerHeight" - "BeltTensionerInnerHeight" ) / 4
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"1mmSpacer"= 1mm
"SteelShaft5mmHoleDiameter"= 5mm
"BeltTensionerMountingHoleOuterBoreDepth"= 2mm
"BeltTensionerMountingHoleOuterBoreDiameter"= 7.75mm
"7mmx1mmSpacerDiameter"= 7mm
"7mmx1mmSpacerHeight"= 1mm
"D1@MainBlock" = "BeltTensionerWidth"
"D4@MainBlock" = "BeltTensionerMountingHoleDiameter"
"D5@MainBlock" = "BeltTensionerInnerWidth"
"D6@MainBlock"="HoleOffsetFromEdge" + "RailThickness"
"D7@MainBlock"="BeltTensionerMountingHoleOffsetFromTopOrBottom"
"D8@MainBlock"="BeltTensionerMountingHoleOffsetFromTopOrBottom"
"D1@MainBlockBoss-Extrude1" = "BeltTensionerDepth"
"D1@TopHoleCut-Sketch2" = "BeltTensionerDepth" / 2
"D3@TopHoleCut-Sketch2" = "SteelShaft5mmHoleDiameter"
"D1@MountHoleBoreSketch3" = "BeltTensionerMountingHoleOuterBoreDiameter"
"D1@MountHoleBoreCut-Extrude2"="BeltTensionerMountingHoleOuterBoreDepth"
"D1@TopSpacerSketch4" = "7mmx1mmSpacerDiameter"
"D1@TopSpacerBoss-Extrude2" = "7mmx1mmSpacerHeight"
"D1@LowerSpacerBoss-Extrude3" = "7mmx1mmSpacerHeight"
"SteelPinPushHoleDiameter"= 2mm
"D1@PushPinHoleSketch1" = "SteelPinPushHoleDiameter"
"BeltTensionerSteelShaftHoleDepthFromTop"= ( "SteelShaftLength" - "BeltTensionerInnerHeight" ) / 2 + ( "BeltTensionerHeight" - "BeltTensionerInnerHeight" ) / 2 + "BeltTensionerInnerHeight"'Equals 45
"SteelShaftLength"= 30mm
"D1@TopHoleCut-Extrude1"="BeltTensionerSteelShaftHoleDepthFromTop"
"D2@TopHoleCut-Sketch2"="BeltTensionerWidth" -"MidRailToAlignWithGantryBlock" - "RailThickness"
"D1@MidRailIndentSketch1"="DistanceAboveMidSideRailToBeltTensioner"
"LinearRailWidth"= 12mm'Spec
"MidSideRailVerticalOffset"= "LinearRailWidth" + 3mm'Allows space for RodStabilizer to attach to bottom of MidSideRail
"DistanceAboveMidSideRailToBeltTensioner"= "VS ToTopOfBeltTensionerAlignedWithYAxisGantryBlockUpperPulley" - "V8 ToTopOfMidSideRail"'Equals 14.9
"DistanceFromBeltTensionerTopPulleyToBeltTensionerTop"= "7mmx1mmSpacerHeight" + "BeltTensionerTopHeight"'Equals 20.8
"BeltTensionerTopHeight"= ( "BeltTensionerHeight" - "BeltTensionerInnerHeight" ) / 2'Equals 19.8
"GABUpperHeight"= 4mm
"D9@MainBlock"="BeltTensionerTopHeight"
"D3@MainBlock"="BeltTensionerInnerHeight"
"D2@MainBlock"="BeltTensionerHeight"
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"V1 BottomOfLowerRail"= "LegHeight"
"LowerEnclosureThickness"= 5mm
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"ZAxisLeadScrewLength"= 200mm
"LM8UUHeight"= 24mm'Spec
"V2 ToBedAtTopOfZAxis"= "V1 BottomOfLowerRail" - "LowerEnclosureThickness" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2'Equals 277
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"HotEndToTopOfXAxisGB"= 71.68487mm'Equals 71.68487. Measured after installed onto X-Axis linear rail guide block
"LinearGBWidth"= 27mm'Spec
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2'Equals 19.5
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"'Equals 352.18487
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"GABLowerHeight"= 4mm
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"V6 ToMiddleOfYAxisGantryBlock"= "V5 ToBottomOfXAxisLinearRail" - "GABHeight" / 2'Equals 334.18487
"V8 ToTopOfMidSideRail"= "V6 ToMiddleOfYAxisGantryBlock" + "MidSideRailVerticalOffset"'Equals 349.18487
"VS ToTopOfBeltTensionerAlignedWithYAxisGantryBlockUpperPulley"= "V5 ToBottomOfXAxisLinearRail" - "DistanceFromXAxisLinearRailBottomAndTopOfGantryPulley" + "DistanceFromBeltTensionerTopPulleyToBeltTensionerTop"'Equals 364.08487
"DistanceFromXAxisLinearRailBottomAndTopOfGantryPulley"= "GABUpperHeight" + "GABMidShortRiserHeight" - "GABRiserBossOffset"'Equals 8.9
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"GABRiserBossOffset"= 0.4mm'Aligns Pulleys inside edges to be 2.5mm (.5mm apart top to bottom)
