"GABDepth"= "GABDistanceFromBackToFirstPulley" + "GABPulleyDDistanceBetween" + "GABDistanceFromPulleyToFront"
"GABWidth"= "StandardWallThickness" + "GABDistanceFromLSideToPulley" + "GABPulleyWDistanceBetween" + "GABDistanceFromPulleyToRSide"
"GABLowerHeight"= 4mm
"GABUpperHeight"= 4mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"StandardWallThickness"= 3mm
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"LinearGBMountHolesXDistance"= 20mm'Spec
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"GBMountingHoleDiameter"= 2mm
"GABMidLongRiserHeight"= "GABMidWallHeight" - "GABMidShortRiserHeight" - "20TGT2PulleyWidth"'Equals 14
"GABLRClampHoleOffsetFromSide"= 5mm
"GABDistanceFromBackToFirstPulley"= 13.5mm
"GABPulleyDDistanceBetween"= 12.5mm'From the100
"GABPulleyWDistanceBetween"= 14.5mm'From the100
"GABDistanceFromPulleyToFront"= 8mm
"GABDistanceFromLSideToPulley"= 9.5mm + "StandardWallThickness"
"GABDistanceFromPulleyToRSide"= 7.5mm
"GABDistanceToFrontRearClampHoles"= 8.5mm
"SteelShaft5mmHoleDiameter"= 5mm
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"7mmx1mmSpacerDiameter"= 7mm
"7mmx1mmSpacerHeight"= 1mm
"GABRiserBossOffset"= 0.4mm'Aligns Pulleys inside edges to be 2.5mm (.5mm apart top to bottom)
"D2@TopSketch1" = "GABPulleyDDistanceBetween"
"D3@TopSketch1" = "GABPulleyDDistanceBetween"
"D4@TopSketch1" = "GABLRClampHoleOffsetFromSide"
"D5@TopSketch1" = "GABLRClampHoleOffsetFromSide"
"D8@TopSketch1" = "SteelShaft5mmHoleDiameter"
"D10@TopSketch1" = "GABWidth"
"D9@TopSketch1" = "GABDistanceFromLSideToPulley"
"D12@TopSketch1"="GABDistanceFromBackToFirstPulley"
"D1@Boss-Extrude1"="GABUpperHeight"
"D1@TopLeftRiser" = "7mmx1mmSpacerDiameter"
"D1@TopLeftRiserBoss-Extrude2" = "GABMidShortRiserHeight" - "GABRiserBossOffset"
"D1@topRightRiserBoss-Extrude3" = "GABMidLongRiserHeight" + "GABRiserBossOffset"
"D1@MidWallBoss-Extrude4" = "GABMidWallHeight"
"D1@BottomBoss-Extrude5" = "GABLowerHeight"
"D1@LowerLeftRiserBoss-Extrude6" = "GABMidLongRiserHeight" + "GABRiserBossOffset"
"D1@LowerRightRiserBoss-Extrude7" = "GABMidShortRiserHeight" - "GABRiserBossOffset"
"D1@GBMountingHolesSketch7" = "LinearGBMountHolesXDistance"
"D2@GBMountingHolesSketch7" =  ( "GABWidth" - "LinearGBMountHolesXDistance" )  / 2
"D3@GBMountingHolesSketch7" =  ( "GABHeight" - "LinearGBMountHolesXDistance" )  / 2
"D4@GBMountingHolesSketch7"="LinearGBMountHolesYDistance"
"D7@GBMountingHolesSketch7"="GBMountingHoleDiameter"
"D1@TopLeftInsetCut-Extrude1" = "7mmx1mmSpacerHeight"
"D1@TopRightInsetCut-Extrude2" = "7mmx1mmSpacerHeight"
"D1@LowerLeftInsetCut-Extrude3" = "7mmx1mmSpacerHeight"
"D1@LowerRightInsetCut-Extrude4" = "7mmx1mmSpacerHeight"
"D1@GBMountingHolesCut-Extrude5" = "StandardWallThickness"
"D6@TopSketch1"="GABDepth" - "GABDistanceToFrontRearClampHoles"
"D11@TopSketch1"="GABDistanceFromPulleyToFront"
"LinearGBMountHolesYDistance"= 20mm'Spec
"StealPinPushHoleDiameter"= 2mm
"D1@PushPinHoleSketch1" = "StealPinPushHoleDiameter"
"M3HeatInsertHoleDiameter"= 4mm'Spec
"D7@TopSketch1"="M3HeatInsertHoleDiameter"
"D1@TopBackClampHoleSketch13" = "GABWidth" / 2
"D2@TopBackClampHoleSketch13" = "GABDistanceToFrontRearClampHoles"
"D1@TopBackClampHoleCut-Extrude1" = "GABUpperHeight"
