"GABWidth"= "GABDistanceFromBackToFirstPulley" + "GABPulleyWDistanceBetween" + "GABDistanceFromPulleyToOutside"'Equals 35.5
"GABLowerHeight"= 31.5mm
"GABUpperHeight"= 17mm'From the100
"GABMidWallHeight"= 19mm'From the100
"StandardWallThickness"= 3mm
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 0.8
"GABMidLongRiserHeight"= "GABMidWallHeight" - "GABMidShortRiserHeight" - "20TGT2PulleyWidth"'Equals 9.5
"GABDistanceFromBackToFirstPulley"= "StandardWallThickness" + 10.5mm
"GABPulleyDDistanceBetween"= 12.5mm'From the100
"GABPulleyWDistanceBetween"= "SteelShaft5mmHoleDiameter" + "RodShaft8mmDiameter" + 1mm'the100 has this as 12.5. Increase to 14 so XAxis rod fits between
"GABDistanceFromPulleyToOutside"= 8mm'the100 has this as 12.5. Decrease to 8 so WDistanceBetween can be increased
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"7mmx1mmSpacerDiameter"= 7mm + .1mm'Add .1mm for printing
"GABRiserBossOffset"= 0.4mm'Aligns Pulleys inside edges to be 2.5mm (.5mm apart top to bottom)
"D2@TopSketch1" = "GABPulleyDDistanceBetween"
"D3@TopSketch1"="GABPulleyWDistanceBetween"
"D8@TopSketch1" = "SteelShaft5mmHoleDiameter"
"D10@TopSketch1" = "GABWidth"
"D9@TopSketch1" = "GABDistanceFromPulleyToOutside"
"D12@TopSketch1"="GABDistanceFromBackToFirstPulley"
"D1@Boss-Extrude1"="GABUpperHeight"
"D1@TopLeftRiser" = "7mmx1mmSpacerDiameter"
"D1@TopLeftRiserBoss-Extrude2" = "GABMidShortRiserHeight" - "GABRiserBossOffset"
"D1@topRightRiserBoss-Extrude3" = "GABMidLongRiserHeight" + "GABRiserBossOffset"
"D1@MidWallBoss-Extrude4" = "GABMidWallHeight"
"D1@BottomBoss-Extrude5" = "GABLowerHeight"
"D1@LowerLeftRiserBoss-Extrude6" = "GABMidLongRiserHeight" + "GABRiserBossOffset"
"D1@LowerRightRiserBoss-Extrude7" = "GABMidShortRiserHeight" - "GABRiserBossOffset"
"D11@TopSketch1"="GABDistanceFromPulleyToOutside"
"SteelShaft5mmHoleDiameter"= 5mm
"LM8UUOffsetFromGABBack"= 11mm'From the100
"LM8UUDiameter"= 15mm
"D1@LM8UUHoleSketch1"= "LM8UUDiameter" 
"RodShaft8mmDiameter"= 8mm
"D1@XAxisRodCutSketch2"= "RodShaft8mmDiameter" 
"GABDistanceBetweenXAxisRods"= 34.6mm'From the100
"D4@XAxisRodCutSketch2"="GABDistanceBetweenXAxisRods"
"D2@LM8UUHoleSketch1"="LM8UUOffsetFromGABBack"
"LM8UUOffsetFromBottomMidSection"= 21.5mm'From the100
"D3@LM8UUHoleSketch1"="LM8UUOffsetFromBottomMidSection"
"XAxisRodDistanceFromTopMidSection"= 7.75mm'From the100
"D3@XAxisRodCutSketch2"="XAxisRodDistanceFromTopMidSection"
"D1@SteelShaftPushPinSketch6" = "SteelPushPinHoleDiameter"
"D1@XEndStopMountSketch2"="M3HeatInsertHoleDiameter"
"D2@XEndStopMountSketch2"="GABLength" / 3
"D3@XEndStopMountSketch2"="GABWidth" / 4
"M3HeatInsertHoleDepth"= 4mm
"M3HeatInsertHoleDiameter"= 4mm + .1mm'Add .1mm for printing
"GABLength"= "GABDistanceFromBackToFirstPulley" + "GABPulleyDDistanceBetween" + "GABDistanceFromPulleyToOutside"'Equals 34
"D1@XEndStopMountCut-Extrude1"="M3HeatInsertHoleDepth"
"D1@LM8UUFastenerSketch1"="LM8UUFasteningHoleDiameter"
"D2@LM8UUFastenerSketch1"="LM8UUDiameter" / 2 + "LM8UUFasteningHoleDiameter"/2 -1mm
"LM8UUFasteningHoleDiameter"= 4.2mm'10/24 set screw hole diameter
"D2@XAxisRodCutSketch2"="GABPulleyWDistanceBetween"/2
"7mmx1mmSpacerHeight"= 1mm
"D1@LowerLeftInsetCut-Extrude1"="7mmx1mmSpacerHeight"
"D1@LowerRightInsetCut-Extrude2" = "7mmx1mmSpacerHeight"
"D1@TopLeftInsetCut-Extrude3" = "7mmx1mmSpacerHeight"
"D1@TopRightInsetCutCut-Extrude4" = "7mmx1mmSpacerHeight"
"SteelPushPinHoleDiameter"= "SteelShaft5mmHoleDiameter" - 1mm
