"RailThickness"= .125in'Spec
"LM8UUDiameter"= 15mm
"MidLeftOrRightSideRailHeight"= 2.0in
"RodStabilizerLength"= 50mm
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleDistance"= 31mm'Spec
"LM8UUHeight"= 24mm'Spec
"ZAxisLeadScrewLength"= 200mm
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"V1 BottomOfLowerRail"= "LegHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"V1 BottomOfLowerRail"= "LegHeight"
"V2 ToBedAtTopOfZAxis"= "V1 BottomOfLowerRail" - "LowerEnclosureThickness" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2
"HotEndToTopOfXAxisGB"= 63.315144mm'Measured from the100.Should be 63.315144
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"
"LinearRailWidth"= 12mm'Spec
"V6 ToBottomOfGantryPulley"= "V5 ToBottomOfXAxisLinearRail" - "DistanceFromGABTopToLowerPulley"
"GABUpperHeight"= 6mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"GABRiserBossOffset"= 0.8mm'Aligns Pulleys
"DistanceFromGABTopToLowerPulley"= "GABUpperHeight" + "GABMidWallHeight" - "GABMidShortRiserHeight" + "GABRiserBossOffset" / 2
"V7 ToTopOfMidBackRail"= "V6 ToBottomOfGantryPulley" + "StepperShaftLength"
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"FasteningHoleDiameter"= .125in
"RodStabilizerHeight"= "LM8UUHeight"
"LowerEnclosureThickness"= 5mm
"D1@Profile-Sketch1" = "LM8UUDiameter"
"D3@Profile-Sketch1" = "RodStabilizerLength"
"D4@Profile-Sketch1" = "RodStabilizerLength" / 2
"RodStabilizerWidthFromMidRailToZAxisRodCenter"= "StepperMountingHoleOffsetFromLeftOrRightSide" + "StepperMountingHoleDistance" / 2 - "RailThickness"
"StandardWallThickness"= 3mm
"D6@Profile-Sketch1" = "StandardWallThickness" * 2
"D1@Profile-Boss-Extrude2"= "RodStabilizerHeight"
"D6@FasteningHoleSketch3"="HoleOffsetFromEdge"
"D2@LM8UUFasteningHoleSketch5"="LM8UUHeight"/2
"V8 ToTopOfMidSideRail"= "V7 ToTopOfMidBackRail" - "RailThickness"
"RodStabilizerMountingHoleOffsetInsideX"= 14.125mm'Backward compatible
"RodStabilizerMountingHoleOffsetOutsideX"= 12mm
"D5@Profile-Sketch1"="RodStabilizerWidthFromMidRailToZAxisRodCenter"
"V3 ToTopOfZAxisLM8UU"= "V2 ToBedAtTopOfZAxis" + "LM8UUHeight"
"RodStabilizerMountingHoleYOffsetFromBottom"= "RodStabilizerHeight" - ( "V3 ToTopOfZAxisLM8UU" - "V8 ToTopOfMidSideRail" + "MidLeftOrRightSideRailHeight" ) + "HoleOffsetFromEdge"
"D2@FasteningHoleSketch3"="RodStabilizerMountingHoleYOffsetFromBottom"
"D3@FasteningHoleSketch3"="FasteningHoleDiameter"
