"RailThickness"= .125in'Spec
"LM8UUDiameter"= 15mm
"MidLeftOrRightSideRailHeight"= 2.0in
"RodStabilizerLength"= 50mm
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleDistance"= 31mm'Spec
"LM8UUHeight"= 24mm'Spec
"ZAxisLeadScrewLength"= 200mm
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"V1 BottomOfLowerRail"= "LegHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"V1 BottomOfLowerRail"= "LegHeight"
"V2 ToBedAtTopOfZAxis"= "V1 BottomOfLowerRail" - "LowerEnclosureThickness" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2
"HotEndToTopOfXAxisGB"= 63.315144mm'Measured from the100.Should be 63.315144
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"
"LinearRailWidth"= 12mm'Spec
"V6 ToMiddleOfYAxisGantryBlock"= "V5 ToBottomOfXAxisLinearRail" - "GABHeight" / 2'Equals 325.31514
"GABUpperHeight"= 6mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"FasteningHoleDiameter"= .125in
"RodStabilizerHeight"= "V8 ToBottomOfMidSideRail" - "V2 ToBedAtTopOfZAxis" + "HoleOffsetFromEdge" * 2
"LowerEnclosureThickness"= 5mm
"D1@Profile-Sketch1" = "LM8UUDiameter"
"D3@Profile-Sketch1" = "RodStabilizerLength"
"D4@Profile-Sketch1" = "RodStabilizerLength" / 2
"RodStabilizerWidthFromMidRailToZAxisRodCenter"= "StepperMountingHoleOffsetFromLeftOrRightSide" + "StepperMountingHoleDistance" / 2 - "RailThickness"
"StandardWallThickness"= 3mm
"D6@Profile-Sketch1" = "StandardWallThickness" * 2
"D1@Profile-Boss-Extrude2"= "RodStabilizerHeight"
"D6@FasteningHoleSketch3"="HoleOffsetFromEdge"
"D2@LM8UUFasteningHoleSketch5"="LM8UUHeight"/2
"V8 ToTopOfMidSideRail" = "V6 ToMiddleOfYAxisGantryBlock" + "MidSideRailVerticalOffset"
"D5@Profile-Sketch1"="RodStabilizerWidthFromMidRailToZAxisRodCenter"
"RodStabilizerMountingHoleYOffsetFromBottom"= "RodStabilizerHeight" - "HoleOffsetFromEdge"
"D2@FasteningHoleSketch3"="RodStabilizerMountingHoleYOffsetFromBottom"
"D3@FasteningHoleSketch3"="FasteningHoleDiameter"
"GABLowerHeight"= 3mm
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"V8 ToBottomOfMidSideRail"= "V8 ToTopOfMidSideRail" - "MidLeftOrRightSideRailHeight"'Equals 289.51514
"D1@LM8UUFasteningHoleSketch5"="RodStabilizerLength"/2
"MidSideRailVerticalOffset"= "LinearRailWidth" + 3mm'Allows space for RodStabilizer to attach to bottom of MidSideRail
