"RailThickness"= .125in'Spec
"LM8UUDiameter"= 15mm
"MidLeftOrRightSideRailHeight"= 2.0in
"RodStabilizerLength"= 50mm
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"Nema17StepperMountSlotDistance"= 31mm'Spec
"LM8UUHeight"= 24mm'Spec
"RodStabilizerHeight"= "V8 ToTopOfMidSideRailYSValue" - "MidLeftOrRightSideRailHeight" - "V2 ToBedAtTopOfZAxisYSValue" + "MidLeftOrRightSideRailHeight" / 2 + "RailThickness" * 1.5 + .77517'Equals 37.32237. Add .77517 for LM8UU to be at bottom of RodStabilizer
"D1@Profile-Sketch1"= "LM8UUDiameter"
"D3@Profile-Sketch1" = "RodStabilizerLength"
"D4@Profile-Sketch1" = "RodStabilizerLength" / 2
"D6@Profile-Sketch1" = "M3HeatInsertHoleDepth"
"D1@Profile-Boss-Extrude2"= "RodStabilizerHeight"
"V8 ToTopOfMidSideRailYSValue"= 376.9847mm
"D5@Profile-Sketch1"="Nema17MountStepperHoleFromBack"
"RodStabilizerMountingHoleYOffsetFromBottom"= "RodStabilizerHeight" - "HoleOffsetFromEdge"
"D2@FasteningHoleSketch3"="RodStabilizerMountingHoleYOffsetFromBottom"
"D3@FasteningHoleSketch3"="M3HeatInsertHoleDiameter"
"M3HeatInsertHoleDiameter"= 4mm + .1mm'Add .1mm for printing
"D1@Cut-Extrude1"="RodStabilizerHeight"-"LM8UUHeight"
"8mmLeadScrewHoleDiameter"= 8mm + 1mm'Add 1mm for spacing
"D1@LM8UUPlugSketch1"="8mmLeadScrewHoleDiameter"
"D4@FasteningHoleSketch3"="Nema17StepperMountSlotDistance"
"D1@FasteningHoleSketch3"=("RodStabilizerLength" - "Nema17StepperMountSlotDistance")/2
"Nema17MountStepperHoleFromBack"= 30mm
"M3HeatInsertHoleDepth"= 4mm
"V2 ToBedAtTopOfZAxisYSValue"= 319.8mm
