"RailThickness"= .125in'Spec
"D1@Profile-Sketch1"="RailThickness"
"LM8UUCollarDiameter"= 14.2mm
"LM8UUDiameter"= 15mm
"MidSideRailHeight"= 1.25in
"RodStabilizerWidth"= "StepperMountingHoleOffsetFromLeftOrRightSide" + "StepperMountingHoleDistance" / 2 + "RailThickness" - "RodStabilizerCollarOffset" + 1mm
"RodStabilizerDepth"= "LM8UUDiameter" * 2
"D2@Profile-Sketch1" = "RodStabilizerWidth"
"D3@Profile-Sketch1" = "RodStabilizerLength"
"D1@Profile-Boss-Extrude1" = "RodStabilizerDepth"
"D1@CollarSketch2" = "LM8UUCollarDiameter"
"D3@CollarSketch2" = "RodStabilizerDepth" / 2
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleDistance"= 31mm'Spec
"RodStabilizerCollarOffset"= 0.5mm
"D2@CollarSketch2"="RodStabilizerCollarOffset"
"LM8UUHeight"= 24mm'Spec
"ZAxisLeadScrewLength"= 200mm
"LM8UUEndToStartOfCollar"= 2.5mm
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"V1 BottomOfLowerRail"= "LegHeight"
"LM8UUCollarWidth"= 1.3mm
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"V1 BottomOfLowerRail"= "LegHeight"
"V2 ToBedAtTopOfZAxis" = "V1 BottomOfLowerRail" - "LowerEnclosureThickness" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2
"HotEndToTopOfXAxisGB"= 63.315144mm'Measured from the100.Should be 63.315144
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"
"LinearRailWidth"= 12mm'Spec
"V6 ToBottomOfGantryPulley"= "V5 ToBottomOfXAxisLinearRail" - "DistanceFromGABTopToLowerPulley"
"GABUpperHeight"= 6mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"GABRiserBossOffset"= 0.8mm'Aligns Pulleys
"DistanceFromGABTopToLowerPulley"= "GABUpperHeight" + "GABMidWallHeight" - "GABMidShortRiserHeight" + "GABRiserBossOffset" / 2
"V7 ToTopOfMidBackRail"= "V6 ToBottomOfGantryPulley" + "StepperShaftLength"
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"D1@MountingHoles-Sketch3"="HoleOffsetFromEdge"
"D2@MountingHoles-Sketch3"="HoleOffsetFromEdge"
"D3@MountingHoles-Sketch3"="HoleOffsetFromEdge"
"FasteningHoleDiameter"= .125in
"D4@MountingHoles-Sketch3"="FasteningHoleDiameter"
"D4@Profile-Sketch1"="LM8UUCollarWidth"*2
"RodStabilizerLength"= "V7 ToTopOfMidBackRail" - "RailThickness" - "MidSideRailHeight" - "V2 ToBedAtTopOfZAxis" - "LM8UUHeight" + "HoleOffsetFromEdge" * 2 + "LM8UUEndToStartOfCollar" + "LM8UUCollarWidth" / 2 + "LM8UUCollarWidth"'Equals 23.11514
"D1@Collar-Chamfer2"="LM8UUCollarWidth"
"LowerEnclosureThickness"= 5mm
