"D1@ProfileSketch1"="BedSupportLeadScrewPadSize"
"StandardWallThickness"= 3mm
"BedToBuildPlateStandoffPadSize"= 10mm
"BuildPlateStandoffHolesDistanceFromLeftOrRight"= 7mm
"BuildPlateStandoffHolesDistanceFromFrontOrBack"= 41mm
"DistanceFromBuildPlateSideToStepperHole"= ( "DistanceBetweenLeftToRightStepperHoles" - "BuildPlateWidth" ) / 2'Equals 55.825
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperMountingHoleDistance"'Equals 461.65
"FrontBackRailLength"= 510mm
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"StepperMountingHoleDistance"= 31mm'Spec
"StepperMountingHoleOffsetFromItsSide"= 5.5mm'Spec
"RailThickness"= .125in'Spec
"LeadScrewNutPadSize"= "LeadScrewNutMountingHoleFlangeDiameter" + 2mm'Equals 24
"LeadScrewNutInnerShaftFlangeDiameter"= 10.2mm'Spec
"LeadScrewNutMountHoleDiameter"= "M3HeatInsertHoleDiameter"
"LeadScrewNutMountingHoleFlangeDiameter"= 22mm'Spec
"LeadScrewNutMountingHoleDistance"= 16mm'Spec
"M3HeatInsertHoleDiameter"= 4mm'Spec
"D1@Fillet1"="BedSupportLeadScrewPadSize"/2
"D1@Fillet2"="BedSupportLeadScrewPadSize"/2
"D1@FlangeNutHoleSketch4"="BedSupportLeadScrewPadSize"  / 2
"D2@FlangeNutHoleSketch4"="BedSupportLeadScrewPadSize" / 2
"D3@FlangeNutHoleSketch4" = "LeadScrewNutInnerShaftFlangeDiameter"
"D2@DomeIndentSketch6" = "BedSupportLeadScrewPadSize" / 2
"D3@DomeIndentSketch6" = "BedSupportLeadScrewPadSize" / 2
"BedSpringHoleSize"= 3mm
"BuildPlateWidth"= 350mm'Spec
"BuildPlateLength" = 352mm'Spec
"BuildPlateBoreDiameter"= 5mm'Spec
"BuildPlateBoreDepth"= 3mm'Spec
"BuildPlateDepth"= 8mm'Spec
"BuildPlateFlankingHoles"= 38mm
"BuildPlateStandoffHolesDistanceFromFront"= 7mm
"BedSupportLeadScrewPadSize"= "LeadScrewNutPadSize" + 10mm
"D1@ProfileExtrude-Thin1"="BedSupportLeadScrewPadSize"
"BuildPlateBallDiameter"= 12mm
"BedSupportBuildPlatePadSize"= "BuildPlateBallDiameter" + 20mm
"D4@ProfileSketch1"="BedSupportBuildPlatePadSize"
"D3@ProfileSketch1"="HypotonusOfStepperAndBuildPlateHoles"
"D1@Fillet3"="BedSupportLeadScrewPadSize"/2
"D1@Fillet4"="BedSupportLeadScrewPadSize"/2
"HypotonusOfStepperAndBuildPlateHoles"= sqr ( ( "DistanceFromBuildPlateSideToStepperHole" + "BuildPlateStandoffHolesDistanceFromLeftOrRight" ) ^ 2 + ( "BuildPlateStandoffHolesDistanceFromFrontOrBack" - "BedSupportLeadScrewPadSize" / 2 ) ^ 2 )
"D1@FlangeNutHolesCut-Extrude1" = "M3HeatInsertHoleDiameter"
"D1@FlangeNutHolesSketch2"="LeadScrewNutMountingHoleDistance"/2
"D2@FlangeNutHolesSketch2"="M3HeatInsertHoleDiameter"
"D4@FlangeNutHolesSketch2"="LeadScrewNutMountingHoleDistance"/2
"BallNutDiameter"= "BallJointDiameter" + .2mm'Added .2mm for filament expansion
"D1@DomeIndentSketch6"="BallNutDiameter"
"D1@DomePadExtensionBoss-Extrude1" = "BedSupportBuildPlatePadSize" - "BallNutDiameter" + 2mm
"BallJointDiameter"= 25mm
