"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"D2@Sketch1"= "FrontOrBackRailLength"
"FrameFastenerHoleDiameter"= 8mm
"D3@Sketch1"="FrameFastenerHoleDiameter"
"D5@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D6@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D1@Boss-Extrude2"="RailThickness"
"FrontOrBackRailLength"= 20.5in
"FrameFastenerHoleOffsetFromEdge"= "VSWidth" / 2 - "GapBetweenVerticalSupportsAndRails" / 2
"UpperBackRailHeight"= 2.5in
"D4@Sketch1"="UpperBackRailHeight" /2
"D1@Sketch1"="UpperBackRailHeight"
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
"ExtruderHorizontalMountHolesDistance"= 15mm'Spec
"ExtruderVerticalMountHolesDistance"= 53mm'Spec
"ExtruderMountHolesDiameter"= 4mm
"D7@Sketch1"="ExtruderHorizontalMountHolesDistance"
"D8@Sketch1"="ExtruderHorizontalMountHolesDistance"
"D9@Sketch1"="FrontOrBackRailLength"/2
"D10@Sketch1"=("UpperBackRailHeight" - "ExtruderVerticalMountHolesDistance")/2
"D11@Sketch1"="ExtruderVerticalMountHolesDistance"
"D12@Sketch1"="ExtruderMountHolesDiameter"
"AngleBracketSmallHoleDiameter"= 4mm
"D21@Sketch1"="AngleBracketSmallHoleDiameter"
"AngleBracketSlotDistanceBetweenHoles"= 30mm
"D24@Sketch1"="AngleBracketSlotDistanceBetweenHoles"
"D23@Sketch1"="AngleBracketSlotDistanceBetweenHoles"
"AngleBracketSlotDistanceFromTop"= 13mm
"D20@Sketch1"="AngleBracketSlotDistanceFromTop"
"AngleBracketSlotDistanceFromCorner"= "AngleBracketSlotDistanceFromBack" - "GapBetweenVerticalSupportsAndRails" / 2'Equals 61.825
"D19@Sketch1"= "AngleBracketSlotDistanceFromCorner" - 2mm 'Minus 2mm to get screw hole in middle of slot
"D18@Sketch1"= "AngleBracketSlotDistanceFromCorner" - 2mm'Minus 2mm to get screw hole in middle of slot
"AngleBracketSlotDistanceFromBack"= 65mm
