"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"SideRailLength"= 21.75in
"StepperHolePadSize"= "StepperHoleDiameter"
"D1@Sketch1"="TopRailHeight"
"D2@Sketch1"="SideRailLength"
"FrameFastenerHoleDiameter"= 8mm
"D3@Sketch1"="FrameFastenerHoleDiameter"
"D4@Sketch1"="TopRailHeight"/2
"D5@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D6@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D1@Boss-Extrude2"="RailThickness"
"FrameFastenerHoleOffsetFromEdge"= "VSWidth" / 2 - "GapBetweenVerticalSupportsAndRails" / 2
"TopRailHeight"= 1.25in
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
"AngleBracketSmallHoleDiameter"= 4mm
"AngleBracketSlotDistanceBetweenHoles"= 30mm
"AngleBracketSlotDistanceFromTop"= 13mm
"D8@Sketch1"="AngleBracketSlotDistanceBetweenHoles"
"D9@Sketch1"="AngleBracketSmallHoleDiameter"
"D10@Sketch1"="AngleBracketSlotDistanceFromTop"
"AngleBracketSlotDistanceFromCorner"= "AngleBracketSlotDistanceFromBack" - "GapBetweenVerticalSupportsAndRails" / 2'Equals 61.825
"D11@Sketch1"= "AngleBracketSlotDistanceFromCorner" - 2mm 'Minus 2mm to get screw hole in middle of slot
"AngleBracketSlotDistanceFromBack"= 65mm
"D14@Sketch1"= "AngleBracketSlotDistanceFromCorner" - 2mm'Minus 2mm to get screw hole in middle of slot
"D15@Sketch1"="AngleBracketSlotDistanceBetweenHoles"
"D2@Sketch2"= ( "SideRailLength" - "LightStripLength" + "LightStripGuideMountingHoleFromLeftOrRightSide" * 2 ) / 2
"LightStripLength"= 270mm'Spec
"LightStripGuideMountingHoleFromLeftOrRightSide"= 50mm
"D3@Sketch2"=("LightStripLength" - "LightStripGuideMountingHoleFromLeftOrRightSide"*2)/2
"D1@Sketch2"="LightStripLength" - "LightStripGuideMountingHoleFromLeftOrRightSide" * 2
"M3HoleDiameter"= 3mm
"D6@Sketch2"="M3HoleDiameter"
"LightStripGuideMountingHoleFromTop" = 4.5mm
"D5@Sketch2"="LightStripGuideMountingHoleFromTop"
