"RailThickness"= .125in'Spec
"VSWidth"= 1.25in'Spec
"SideRailLength"= 21.75in
"D1@Sketch1"="TopRailHeight"
"D2@Sketch1"="SideRailLength"
"FrameFastenerHoleDiameter"= 8mm
"D3@Sketch1"="FrameFastenerHoleDiameter"
"D4@Sketch1"="TopRailHeight"/2
"D5@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D6@Sketch1"="FrameFastenerHoleOffsetFromEdge"
"D1@Boss-Extrude2"="RailThickness"
"FrameFastenerHoleOffsetFromEdge" = "VSWidth" / 2 - "GapBetweenVerticalSupportsAndRails" / 2
"TopRailHeight"= 1.25in
"GapBetweenVerticalSupportsAndRails"= "RailThickness" * 2
"AngleBracketSmallHoleDiameter"= 4mm
"AngleBracketSlotDistanceBetweenHoles"= 30mm
"AngleBracketSlotDistanceFromTop"= 13mm
"AngleBracketSlotDistanceFromCorner" = "AngleBracketSlotDistanceFromBack" - "GapBetweenVerticalSupportsAndRails" / 2'Equals 61.825
"D7@Sketch1"="AngleBracketSmallHoleDiameter"
"D8@Sketch1"="AngleBracketSlotDistanceBetweenHoles"
"D10@Sketch1"="AngleBracketSlotDistanceFromTop"
"D9@Sketch1"= "AngleBracketSlotDistanceFromCorner" - 2mm 'Minus 2mm to get screw hole in middle of slot
"AngleBracketSlotDistanceFromBack"= 65mm
"D13@Sketch1"= "AngleBracketSlotDistanceFromCorner" - 2mm'Minus 2mm to get screw hole in middle of slot
"D14@Sketch1"="AngleBracketSlotDistanceBetweenHoles"
