"V1 BottomOfLowerRail"= "LegHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"ZAxisLeadScrewLength"= 200mm
"LM8UUHeight"= 24mm'Spec
"V2 ToBedAtTopOfZAxis"= "V1 BottomOfLowerRail" - "LowerEnclosureThickness" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2'Equals 277
"V3 ToTopOfZAxisLM8UUCollar"= "V2 ToBedAtTopOfZAxis" + "LM8UUHeight" - "LM8UUEndToStartOfCollar"
"LM8UUEndToStartOfCollar"= 2.5mm
"HeightOfHotEndAssembly"= 140mm'From HotEndTip to top of shroud
"HotEndToTopOfXAxisGB"= 71.68487mm'Equals 71.68487. Measured after installed onto X-Axis linear rail guide block
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2'Equals 19.5
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"'Equals 352.18487
"TopOfXAxisGBToBottomCarrierBeltHole"= "LinearGBWidth" + "CarrierLowerBodyLength" - "CarrierRibbonHoleOffsetFromBottom"
"CarrierLowerBodyLength"= "CarrierRibbonHoleWidth" * 2 + "CarrierRibbonHoleDistance" + 5mm * 2
"V6 ToBottomCarrierBeltHole"= "V5 ToBottomOfXAxisLinearRail" + "TopOfGBToBottomOfLinearRail" - "TopOfXAxisGBToBottomCarrierBeltHole"
"V6 ToMiddleOfYAxisGantryBlock"= "V5 ToBottomOfXAxisLinearRail" - "GABHeight" / 2'Equals 334.18487
"GABUpperHeight"= 4mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"D5@Sketch1"="V2 ToBedAtTopOfZAxis"
"D4@Sketch1"="V1 BottomOfLowerRail"
"D8@Sketch1"="V3 ToTopOfZAxisLM8UUCollar"
"D6@Sketch1"="V5 ToBottomOfXAxisLinearRail"
"CarrierRibbonHoleOffsetFromBottom"= 7.4mm
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"GABLowerHeight"= 4mm
"V7 ToInvertedTopOfMidBackRail"= "V6 ToMiddleOfYAxisGantryBlock" + "20GT2PulleyExternalDiameter" - "StepperShaftLength"
"D13@Sketch1"="V6 ToMiddleOfYAxisGantryBlock"
"D15@Sketch1"="V6 ToBottomCarrierBeltHole"
"D9@Sketch1"="V4 ToTopOfBuildPlate/HotEndTip"
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"V6 ToBottomOfStepperShaft"= "V7 ToInvertedTopOfMidBackRail" - "StepperShaftLength"
"D10@Sketch1"="V6 ToBottomOfStepperShaft"
"V8 ToTopOfMidSideRail"= "V6 ToMiddleOfYAxisGantryBlock" + "MidSideRailVerticalOffset"'Equals 349.18487
"D11@Sketch1" = "V8 ToTopOfMidSideRail"
"LinearRailWidth"= 12mm'Spec
"VSLength"= 450mm
"D2@Sketch1"="VSLength"
"D17@Sketch1"="HeightOfHotEndAssembly"
"LowerEnclosureThickness"= 5mm
"20GT2PulleyExternalDiameter"= 14.2mm'Spec
"MidSideRailVerticalOffset"= "LinearRailWidth" + 3mm'Allows space for RodStabilizer to attach to bottom of MidSideRail
"CarrierRibbonHoleWidth"= 7mm
"CarrierRibbonHoleDistance"= 2.5mm'Equals 2.5. Must equal distance created by GABRiserBossOffset
