"V1 BottomOfLowerRail"= "LegHeight"
"StepperShaftLength"= 24mm'Pulley will be attached to the end
"ZAxisLeadScrewLength"= 200mm
"LM8UUHeight"= 24mm'Spec
"V2 ToBedAtTopOfZAxis"= "V1 BottomOfLowerRail" + "StepperShaftLength" + "ZAxisLeadScrewLength" - "LM8UUHeight" / 2
"V3 ToTopOfZAxisLM8UUCollar"= "V2 ToBedAtTopOfZAxis" + "LM8UUHeight" - "LM8UUEndToStartOfCollar"
"LM8UUEndToStartOfCollar"= 2.5mm
"HeightOfHotEndAssembly" = 140mm'From HotEndTip to top of shroud
"HotEndToTopOfXAxisGB"= 63.315144mm'Measured from the100.Should be 63.315144
"TopOfGBToBottomOfLinearRail"= "LinearGBWidth" / 2 + "LinearRailWidth" / 2
"LinearGBWidth"= 27mm'Spec
"V5 ToBottomOfXAxisLinearRail"= "V4 ToTopOfBuildPlate/HotEndTip" + "HotEndToTopOfXAxisGB" - "TopOfGBToBottomOfLinearRail"
"TopOfXAxisGBToBottomCarrierBeltHole"= "LinearGBWidth" + "CarrierLowerBodyLength" - "CarrierRibbonHoleOffsetFromBottom"
"CarrierLowerBodyLength"= 29mm
"V6 ToBottomCarrierBeltHole"= "V5 ToBottomOfXAxisLinearRail" + "TopOfGBToBottomOfLinearRail" - "TopOfXAxisGBToBottomCarrierBeltHole"
"V6 ToBottomOfGantryPulley"= "V5 ToBottomOfXAxisLinearRail" - "DistanceFromGABTopToLowerPulley"
"GABUpperHeight"= 6mm
"GABMidWallHeight"= 28mm'Must equal 28 or changes alignment
"20TGT2PulleyWidth"= 8.7mm'The STL of the Pulley in the diagram is a bit larger
"GABMidShortRiserHeight"= "GABMidWallHeight" / 2 - "20TGT2PulleyWidth"'Equals 5.3
"LegHeight"= 70mm'Space needed for PSU/Stepper/Electronics
"D5@Sketch1"="V2 ToBedAtTopOfZAxis"
"D4@Sketch1"="V1 BottomOfLowerRail"
"D8@Sketch1"="V3 ToTopOfZAxisLM8UUCollar"
"D6@Sketch1"="V5 ToBottomOfXAxisLinearRail"
"GABRiserBossOffset"= 0.8mm'Aligns Pulleys
"CarrierRibbonHoleOffsetFromBottom"= 7.4mm
"DistanceFromGABTopToLowerPulley"= "GABUpperHeight" + "GABMidWallHeight" - "GABMidShortRiserHeight" + "GABRiserBossOffset" / 2
"GABHeight"= "GABLowerHeight" + "GABMidWallHeight" + "GABUpperHeight"
"GABLowerHeight"= 3mm
"V7 ToTopOfMidBackRail"= "V6 ToBottomOfGantryPulley" + "StepperShaftLength"
"RailThickness"= .125in'Spec
"D13@Sketch1"="V6 ToBottomOfGantryPulley"
"D15@Sketch1"="V6 ToBottomCarrierBeltHole"
"D9@Sketch1"="V4 ToTopOfBuildPlate/HotEndTip"
"BedToBuildPlateStandoffLength"= 15mm
"BuildPlateHeight"= 8mm'Spec
"V4 ToTopOfBuildPlate/HotEndTip"= "V2 ToBedAtTopOfZAxis" + "BedToBuildPlateStandoffLength" + "BuildPlateHeight"
"V6 ToBottomOfStepperShaft"= "V7 ToTopOfMidBackRail" - "StepperShaftLength"
"D10@Sketch1"="V6 ToBottomOfStepperShaft"
"V8.1 ToMidSideRailHolesAdjustedToGABHeight"= "V8 ToTopOfMidSideRail" - "V6.3 GantryMiddleToToTopOfMidSideRail"
"V8 ToTopOfMidSideRail"= "V7 ToTopOfMidBackRail" - "RailThickness"
"V6.1 FromGantryPulleyToGantryMiddle"= "GABHeight" / 2 - "GABMidShortRiserHeight" - "GABLowerHeight" + "GABRiserBossOffset" / 2
"V6.2 GantryMiddleToTopOfMidBackRail"= "StepperShaftLength" - "V6.1 FromGantryPulleyToGantryMiddle"
"V6.3 GantryMiddleToToTopOfMidSideRail"= "V6.2 GantryMiddleToTopOfMidBackRail" - "RailThickness"
"D11@Sketch1"="V8.1 ToMidSideRailHolesAdjustedToGABHeight"
"LinearRailWidth"= 12mm'Spec
"VSLength" = 450mm
"D2@Sketch1"="VSLength"
"D17@Sketch1"="HeightOfHotEndAssembly"
