"GABWidthValue"= 37.5mm
"D1@Sketch1" = "XEndStopSupportWidth"
"M2HeatInsertHoleDiameter"= 3mm + .1mm'Add .1mm for printing
"M2HeatInsertHoleDepth"= 3.1mm'Spec
"MicroSwitchMountingHoleOffsetFromBottom"= 7mm
"MicroSwitchTerminalHeight"= 3.5mm
"MicroSwitchDepth"= 2.8mm
"MicroSwitchCutOutLength"= 13.05mm
"MicroSwitchHeight"= 6.55mm
"MicroSwitchMountingHoleOffsetFromSide"= 3.35mm
"MicroSwitchExtraMountingHeight"= 2mm
"MicroSwitchCutOutHeight"= "MicroSwitchExtraMountingHeight" + "MicroSwitchTerminalHeight" + "MicroSwitchHeight"
"EndStopCableDepth"= 1.75mm
"EndStopCableWidth"= 3.75mm
"GABLengthValue"= 34mm
"D2@Sketch1"= "XEndStopSupportLength"
"D1@Boss-Extrude1"="MicroSwitchHeight" -1mm
"D1@MicroSwitchCutSketch2" = "MicroSwitchCutOutLength"
"D2@MicroSwitchCutSketch2" = ( "XEndStopSupportWidth" - "MicroSwitchCutOutLength" ) / 2
"D3@MicroSwitchCutSketch2" = "MicroSwitchCutOutHeight"
"D1@MicroSwitchCut-Extrude1"="MicroSwitchDepth"
"D1@MicroSwitchMountingHolesSketch3" = "MicroSwitchMountingHoleOffsetFromSide"
"D2@MicroSwitchMountingHolesSketch3" = "MicroSwitchMountingHoleOffsetFromSide"
"D4@MicroSwitchMountingHolesSketch3" = "M2HeatInsertHoleDiameter"
"D1@MicroSwitchMountingHolesCut-Extrude2" = "M2HeatInsertHoleDepth"
"D3@MicroSwitchMountingHolesSketch3"="MicroSwitchMountingHoleOffsetFromBottom"
"XEndStopSupportWidth"= "GABWidthValue" / 2
"XEndStopSupportLength"= "GABLengthValue" / 2 + "MicroSwitchCutOutHeight"
"M3HoleDiameter"= 3mm
"D1@GantryMountSlotSketch4" = "M3HoleDiameter"
"D2@GantryMountSlotSketch4" = "XEndStopSupportWidth" / 2
"D1@Sketch2"="M3HoleDiameter" + 2mm
"D2@Sketch2"=1mm
"D1@SlidingMountHoleBoreCut-Extrude4"="MicroSwitchDepth"
"D1@Sketch3"="EndStopCableDepth"
"D1@ThinCableCut-Extrude5" = "EndStopCableDepth"
"D1@Sketch4"="EndStopCableWidth"
"D1@ThickCableCut-Extrude6" = "EndStopCableDepth"
